### ISSUE TITLE
Communicate decision to standardize on GitHub issues

### ISSUE THREAD

**Issue by kdmccormick** [openedx/tcril-engineering#10]
In standup we reached consensus that we (tCRIL engineering) will:
* use GH issues to capture bugs / tasks / feature requests and recommend that other community members to do the same;
* use GH project boards to prioritize and track  those issues, and encourage community working groups to do the same;
* prefer opening issues in the repositories most related to the issue; eg, a visual bug or feature request for the Learning MFE will be opened as an issue in `frontend-app-learning`;
* use an agnostic repository like `platform-roadmap` and/or `public-engineering` to capture issues that are not repository-specific; and
* use the `tcril-engineering` repo for our tCRIL-team-specific tasks.

We need to:
- [ ] choose whether we'll use `platform-roadmap`, `public-engineering`, or both.
- [ ] see if there are any wrinkles around issue automation that we need to iron out.
- [ ] communicate this decision.

**Comment by kdmccormick** [comment]
This relates to https://github.com/openedx/open-edx-proposals/pull/280

**Comment by sarina** [comment]
Assigning myself and @jmakowski1123 to this (although Jenna doesn't autocomplete in the comments box for me nor show up as an assignee - I don't know why). I assume others will be added as assignees as well but for now I think the two of us are reasonably starting on this.

**Comment by nedbat** [comment]
I think communicating this:
> prefer opening issues in the repositories most related to the issue; eg, a visual bug or feature request for the Learning MFE will be opened as an issue in frontend-app-learning;

will go better if it comes with a proposal about who will be monitoring, triaging, and addressing the issues.

**Comment by sarina** [comment]
@nedbat that's a good idea, and actually something that we're beginning on now. Stay tuned.

**Comment by jmakowski1123** [comment]
#32, #10, #39 related to Ownership Proposal (in progress, cc @e0d )

**Comment by sarina** [comment]
Start of this by Feanil in https://discuss.openedx.org/t/new-blip-on-tech-radar-github-issues-provisional/6508/4 https://github.com/openedx/openedx-tech-radar/pull/11

**Comment by feanil** [comment]
I agree, I think this can be closed.

**Comment by kdmccormick** [comment]
👍🏻
