### ISSUE TITLE
add user rayzhou-bit

### ISSUE THREAD

**Issue by rayzhou-bit** [openedx/tcril-engineering#102]
### User list

* Raymond Zhou, @rayzhou-bit

### Firm name

edX
T&L Team
Example: edX, tCRIL, etc

### Start date

02/02/2022
Date of first need for GitHub access.

### Special access & notes

For now, all new edX and tCRIL employees will be granted access to `push-pull-all`.

If these users need to be added to any specific teams or given any elevated privileges, note them here. 

### Follow-up

Once you create this request, the tCRIL engineering team will triage it and handle it as appropriate. If your request is especially urgent, please note that above!

**Comment by kdmccormick** [comment]
Invite sent. In addition to push-pull-all I also added you to the teaching-and-learning team.

Welcome to the project @rayzhou-bit !
