### ISSUE TITLE
Transfer Hooks Framework Repos to the openedx org

### ISSUE THREAD

**Issue by ormsbee** [openedx/tcril-engineering#108]
These repos are a key part of edx-platform's extensibility story, and should be in the openedx org. eduNEXT agrees with this assessment as well. But because it was done as a work-for-hire for edX, we need to make sure that the paperwork is squared away before this transfer can take place.

- [x] Get legal approval to transfer.
- [x] Transfer the `openedx-events` and `openedx-filters` repos from eduNEXT's GitHub org to openedx's.
- [x] Ensure that any CI continues to work.
- [x] Ensure that @felipemontoya and @mariajgrimaldi continue to have commit/maintainer access.

~~Shift PyPI deployments to use the openedx org (?) – (I don't think we have this set up on the openedx side yet)~~. *Going to punt the PyPI issue for now.*

**Comment by ormsbee** [comment]
@felipemontoya, @mariajgrimaldi: We have legal approval to transfer the repos now. Could you please start the transfer process for these two repos to the `openedx` org at your earliest convenience?

Thank you.

**Comment by felipemontoya** [comment]
@ormsbee thanks for the updates.

I'll start with the transfer with the events repo.

**Comment by felipemontoya** [comment]
I get a "You don’t have the permission to create public repositories on openedx" error when I try.

I would have expected that the transfer would initiate and ask you to accept it or something. Did you get any such notification?

**Comment by ormsbee** [comment]
@felipemontoya: Yeah, I thought that was how it worked too, but it looks like you'd need permissions in both to do the transfer. Could you please add me as an admin for the two repos, and then I can transfer them in?

**Comment by felipemontoya** [comment]
I just added you. Don't break anything ;)

**Comment by ormsbee** [comment]
@felipemontoya: May I get a list of the eduNEXT org-level users that should also have access to this repository (aside from yourself)? I want to make sure I'm not cutting off access for anyone who has it today.

**Comment by felipemontoya** [comment]
I think that @mariajgrimaldi, @JuanDavidBuitrago and myself would be enough. Previously only Maria and I had admin, while JuanDavid had write only.

**Comment by ormsbee** [comment]
@felipemontoya, @mariajgrimaldi: Repos have been transferred. I sent invitations to make the access list match up, but you're both admins, so you should be able to add people if I missed anyone.

Thanks folks!

**Comment by ormsbee** [comment]
Made a forum post about this: https://discuss.openedx.org/t/hooks-framework-filters-moved-to-the-openedx-github-org/6734

**Comment by ormsbee** [comment]
Per @mariajgrimaldi, [CI is working](https://discuss.openedx.org/t/hooks-framework-filters-moved-to-the-openedx-github-org/6734/2?u=dave). Closing this ticket.
