### ISSUE TITLE
Request: migrate commerce-coordinator repo from edx to openedx

### ISSUE THREAD

**Issue by dianekaplan** [openedx/tcril-engineering#109]
The purchase squad's newest repo [commerce-coordinator](https://github.com/edx/commerce-coordinator) is still living under edx. When possible, this needs to be migrated to the openedx organization. Let me know if any other info is needed, or if this should be requested somewhere else. 

Thanks in advance for your help!

**Comment by inventhouse** [comment]
Note that this project/repo is _not yet_ ready to include in an Open edX named release.

**Comment by kdmccormick** [comment]
Thanks @dianekaplan @inventhouse ! I will bring this to the team.

In the meantime, help me understand your request a little better:
* Is the repository move a blocker for you in any way?
* It sounds you do plan to include this in a named release eventually. Do you have an idea of what the timeline for its readiness might be? 
* When the repository moves to `openedx`, do you plan to accept contributions from community members outside of 2U?

**Comment by dianekaplan** [comment]
@kdmccormick sorry I didn't see your note! 

A few responses to your questions: 
- Basically we had noticed that this wasn't included in the Big Move of all the repos, and I figured I'd put in the request while that effort was still fresh. We have no particular urgency- we can continue working on it if it's in edx or openedx- just wanted to make sure it didn't get lost. 
- based on our early timelines, we think this may be ready in the O or P release
- We're in the very earliest stages of development right now so it's just us, but we're planning to eventually accept community contributions. If that setting is hard to change in Github (if we move it now for only us and then update later to accept community contributions) we can wait to move it under openedx- we're happy to take your recommendation on this

**Comment by kdmccormick** [comment]
Sounds good @dianekaplan , thanks for the info! This is the first request for an `edx`->`openedx` transfer so I am glad you opened it early, and please forgive our slowness as we figure out how to want to run this process. Let me get back to you on this.

**Comment by kdmccormick** [comment]
@dianekaplan @inventhouse I am going to close this, but feel free to initiate the transfer whenever your ready, or reopen the ticket if you'd like to discuss more.
