### ISSUE TITLE
[GH Request] Onboard yagnesh77

### ISSUE THREAD

**Issue by yagnesh77** [openedx/tcril-engineering#1107]
### Firm Name

ManpraX

### User List (case sensitive!) - Please also include in ticket title

Yagnesh Nayi yagnesh77

### Start Date

04 April 2024

### Urgency

Low (2 weeks)

### Special Requests

https://discuss.openedx.org/t/core-contributor-nomination-yagnesh-nayi/12596

**Comment by sarina** [comment]
@yagnesh77 - your user @Yagnesh1998 is already a member of the Open edX organization. Which GitHub username would you like to use with us in GitHub? You may only use one.

**Comment by yagnesh77** [comment]
@yagnesh77  this one please :)

**Comment by sarina** [comment]
Closing in favor of https://github.com/openedx/axim-engineering/issues/1106
