### ISSUE TITLE
Edit/prune the current FormAssembly questions to make the survey process as quick and easy as possible

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/tcril-engineering#115]
This is a task in epic https://github.com/openedx/tcril-engineering/issues/107

Limit the first-pass survey to query-based questions that can be answered by providers quickly and easily.

The assumption is that providers will be given one survey to fill out per Instance. The current survey contains a mix of questions that could be answered with a simple query, as well as more complicated questions that may take additional time to research. In order to facilitate uptake of the survey, reduce the survey questions to only the questions that can be answered quickly and with a query.

**Comment by jmakowski1123** [comment]
First pass at a pruned survey here: https://tcril.tfaforms.net/forms/builder/5.0.0/13

**Comment by feanil** [comment]
One more suggestion, The ` This Site Serves:` section might be well served with an `Other` response.
