### ISSUE TITLE
[GH Request] Core Contributor rights expansion & maintainership

### ISSUE THREAD

**Issue by navinkarkera** [openedx/tcril-engineering#1168]
### Firm Name

Opencraft

### Urgency

Low (2 weeks)

### Requested Change

Please add `navinkarkera` user (me) as a maintainer to the [RecommenderXBlock](https://github.com/openedx/RecommenderXBlock) repository.

### Reasoning

https://discuss.openedx.org/t/core-contributor-rights-expansion-maintainership-navin-karkera/12869

**Comment by arbrandes** [comment]
@navinkarkera, you now have write access to the repo, congrats!  Feel free to get started on https://docs.openedx.org/en/latest/developers/how-tos/maintain-a-repo.html for it when ready.  Thank you!
