### ISSUE TITLE
Create a Google Sheet template and method for collecting data from multi-tenancy Instances

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/tcril-engineering#117]
This is a task in epic #107 

The assumption is that we will be sending Providers [this survey](https://tcril.tfaforms.net/forms/builder/5.0.0/13) (built in FormAssembly). The expectation will be that one survey will be filled out for each Instance. However, for Providers who run multi-tenancy Instances, it will not be possible for them to fill out one survey for each site.

One suggestion to solve this challenge is to create a "a simple "power user" option where they can submit a Google Sheet with the same rows and columns as our authoritative sheet. This would allow, say, eduNEXT to dump all the tenant sites into a single sheet rather than filling out the form 1000 times. This approach increases our work only the tiniest bit." (suggested in #62) 

Sub-tasks:

- [ ] Clarify the exact format of the output/results when the surveys are submitted (https://tcril.tfaforms.net/forms/builder/5.0.0/13)
- [ ] Create a corresponding mirror Google Sheet

**Comment by feanil** [comment]
@jmakowski1123 Is [this](https://docs.google.com/spreadsheets/d/1xtzYX-lZ2yU0CC82IM0UmVfpY5P3S3hQwgLHWdKNJew/edit#gid=0) what you had in mind for the multi instance version of this sheet?

**Comment by feanil** [comment]
Updated to match wording and I added drop-downs where possible.  Ready to be reviewed again.

[Link](https://docs.google.com/spreadsheets/d/1xtzYX-lZ2yU0CC82IM0UmVfpY5P3S3hQwgLHWdKNJew/edit#gid=0)

**Comment by feanil** [comment]
Also added a link to the full instructions in the README tab.

**Comment by jmakowski1123** [comment]
This looks great, thanks @feanil !
