### ISSUE TITLE
Define methods and processes for communicating with all Service Providers

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/tcril-engineering#118]
We need to identify all public channels of communication for circulating links to the Survey with a Call To Action to complete by March 18.

As a starting point, here is draft text for a blog post: https://docs.google.com/document/d/1p_qAd_113rtKvHtJfepgMlPpGiwLCDW-L4dlS2a3O_M/edit

**Comment by jmakowski1123** [comment]
Eden - What other channels should we be using?

**Comment by jmakowski1123** [comment]
@e0d - Would love your feedback on blog text, link above.

**Comment by ehuthmacher** [comment]
@jmakowski1123 I can circulate the links on all of our social media channels (FB, Twitter, and LinkedIn). We can also leverage [discourse](https://discuss.openedx.org/), and an SF email marketing campaign. Additionally, there are several Slack channels you can circulate the link to: [#general](https://openedx.slack.com/archives/C02SNA1U4), [#core-contributors](https://openedx.slack.com/archives/C015KC8CN76), [#frontend-working-group](https://openedx.slack.com/archives/C02BMP2RD5Y), [#wg-build-test-release](https://openedx.slack.com/archives/C01AGTSB1LL), (https://openedx.slack.com/archives/C02BMP2RD5Y), [#marketing]

**Comment by jmakowski1123** [comment]
3/8:

- Open edX blog post published
- Social media posted on Open edX Linkedin, facebook, twitter
- Jenna posted on personal Linkedin
- Email campaign sent through SF
- Jenna emailed Dhawal Shah at ClassCentral

**Comment by jmakowski1123** [comment]
To do by end of week 3/11:

-Jenna to reach out 1:1 to 15 providers
-Jenna to reach out to UN contacts to fill IGO holes

**Comment by e0d** [comment]
I've shared the request with the TOC.
