### ISSUE TITLE
[GH Request] UX/UI WG Co-Lead Confluence Access

### ISSUE THREAD

**Issue by sdaitzman** [openedx/tcril-engineering#1235]
### Firm Name

Schema, Arbisoft

### Urgency

High (< 3 days)

### Problem/Request

**Confluence edit/create subpage permissions**

Confluence page: https://openedx.atlassian.net/wiki/spaces/COMM/pages/3755016235/Subgroup+UX+UI
Asma Ahmed: asma.ahmed@arbisoft.com
Sam Daitzman: sam.daitzman@schema.education

### Reasoning

Asma Ahmed (@asma-ahmedd, asma.ahmed@arbisoft.com) and I (sam.daitzman@schema.education) are the new co-leads for the UX/UI subgroup of the Product Working Group, and are requesting updated Confluence permissions to create and edit pages within that project. I've marked urgency as "< 3 days" so we can take notes for the next meeting this Thursday, Aug 22.

Previous meeting notes (including decision to hand off the subgroup): https://openedx.atlassian.net/wiki/spaces/COMM/pages/4377182213/2024-08-08+-+UX+UI+Working+Group+Meeting

CC @jmakowski1123 @ali-hugo

**Comment by kdmccormick** [comment]
Sorry @sdaitzman , there was a mix up in our on-call rotation.

From what the Confluence permissions inspector tells me, both you and Asma should be able to create and edit pages anywhere in the COMM space, including under the [UI working group page](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3755016235/Subgroup+UX+UI). Are you still finding that you're unable to do so?

**Comment by sdaitzman** [comment]
No worries, thanks @kdmccormick. I think we're able to edit UX/UI WG pages now.
