### ISSUE TITLE
Remove RV Folks

### ISSUE THREAD

**Issue by e0d** [openedx/tcril-engineering#1271]
With the RV transfers for some 2U staff, we need to remove them from GitHub teams/org as they're no longer covered under the 2U entity CLA

> To confirm, this is the list of users that will lose CLA access.  Apologies, I do not have their GitHub handles off the top of my head but I happy to get them if needed:
> 
> - Colin Brash
> - Kaleb Davenport
> - Andrew Heykamp
> - Bianca Severino 
> - Daniel Newsome
> - Chris Pappas
> - Glenn Martin
> - Juliana Kang
> - Jacky Ng
>

**Comment by arbrandes** [comment]
@e0d, I could not find a "Daniel Newsome" in the database, but there's a homophone, "Daniel Nuzzo".  Should I remove them?

The others have already been removed.

**Comment by e0d** [comment]
I'll check with Colin.

Ed.

**Comment by arbrandes** [comment]
Done!
