### ISSUE TITLE
Update our references and contact details on the Open edX Code of Conduct

### ISSUE THREAD

**Issue by e0d** [openedx/tcril-engineering#13]
Just noticed that our code of conduct reference older email address and may need some day 2 language changes.

https://open.edx.org/code-of-conduct/

This ticket is inclusive of discovery, proposal and implementation.  A light review only should be necessary as we hopefully won't be changing anything substantive in the document.

**Comment by sarina** [comment]
Without seeing this ticket, I already updated a few weeks ago. I:

* Removed Nimisha
* Kept Ned
* Kept Sarina & Ed, but changed our email addresses

**Comment by sarina** [comment]
@e0d I did a review pass and the only things I can see that may need changing:

### The Mission

Currently says, `edX and the Open edX community seek to foster an open and welcoming environment to as wide a range of participants as possible. This mission takes priority over the letter of the rules.` 

Should I remove `edX`?

### Contact email

Should I s/`oscm@edx.org`/ `oscm@tcril.org`/ - or are we using a different list?

**Comment by e0d** [comment]
:+1: Let's spot change those references and consider a larger rework later.  I think most of the content is still correct.
