### ISSUE TITLE
Build a Talk Proposal for a Docs Talk

### ISSUE THREAD

**Issue by feanil** [openedx/tcril-engineering#142]
@feanil and @jmakowski1123 to build a talk on the current state of docs, what we've done so far and what's coming up over the next few quarters.

**Comment by jmakowski1123** [comment]
@feanil here's a very drafty first pass. I think we should also add a bit about the audit/IA discovery work too? Even if vague... https://docs.google.com/document/d/1ICpwHGjVDftYOebu8apg0fcxJz4SC7WsnjEWvm__dvs/edit

**Comment by sarina** [comment]
Hey, looks like this was moved to "done" on the board. Remember you also need to close out the ticket if it's done.

**Comment by feanil** [comment]
Closed since this was submitted.
