### ISSUE TITLE
Talk proposal: State of the Frontend

### ISSUE THREAD

**Issue by arbrandes** [openedx/tcril-engineering#144]
### Title

Open edX State of the Frontend (As I Found It)

### Abstract

(To expand.)

A 40-minute talk on where we were (compare to David Joy's talk 2 years ago), where we are, and where we are going.

### Copresenters

Intend to invite one or more of: @davidjoy, @adamstankiewicz...

**Comment by arbrandes** [comment]
@davidjoy, are you officially accepting my invitation to co-present? 🤞🏼  (You don't have to, btw, though I'm going to try and pick your brain, anyway.  But I figured it'd be cool.)

**Comment by davidjoy** [comment]
@arbrandes  Yes, I suppose I am!  Just talked it over with the family and we're going to try to make it happen.  I need to renew my passport. 😜

**Comment by arbrandes** [comment]
Talk submitted with [this content](https://docs.google.com/document/d/1q41dvBwJ1rR6-7Rvr3Vzvjl2VfqioD21W-ii-B7P1vY/edit?usp=sharing).
