### ISSUE TITLE
[GH Request]

### ISSUE THREAD

**Issue by syedsajjadkazmii** [openedx/tcril-engineering#153]
### Firm Name

edX, Arbisoft

### User List

Name: Syed Sajjad Hussain Shah
Email: ssajjad@edx.org

### Start Date

10 February 2022

### Urgency

High urgency - please do asap

### Special Requests

<img width="1259" alt="Screen Shot 2022-02-17 at 3 17 09 PM" src="https://user-images.githubusercontent.com/52817156/154455303-9688367a-0255-4351-b23c-87709bcf3fca.png">

**Comment by kdmccormick** [comment]
@syedsajjadkazmii I sent you an invitation to https://github.com/openedx/ and the `push-pull-all` team. This should give you write access to all the repos you need.
