### ISSUE TITLE
State of Open edX 

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/tcril-engineering#155]
Possible areas of coverage:

- Updates on ToC/Board
- Updates on Community
- Updates on Survey

**Comment by sarina** [comment]
do we still need to answer questions like, what is tcril? who is tcril? what is the toc and what do they do?

community by the numbers - what kinds of numbers could we add, # core contributors, # of unique contributors past year, etc? (can't think of anything interesting off the top of my head)

something about core contributors, if my talk is not accepted

6-12 month horizon for community, what tcril is doing to support it

relevant architecture updates? (nim went into this in depth at 2021's state of open edx, but given the conference has a broad audience i'm not sure how much time that should really be given)

any big community wins to call out?
