### ISSUE TITLE
Lightning Talk Proposal: Handling Changes to Live Content as a Developer

### ISSUE THREAD

**Issue by ormsbee** [openedx/tcril-engineering#156]
# Session Title: Handling Changes to Live Content as a Developer

![wile_e](https://user-images.githubusercontent.com/41625/154830646-42aa34db-d604-464a-a597-82152ab6793e.png)

## Description

Course teams sometimes change content after it's been released to students. This can expose code to situations in which the user or application state associated with a piece of content is no longer consistent with that content, for example:

* A student's score if the "correct" answer has been altered.
* An application's reference to content that has since been deleted, or had its permissions changed.
* A position index into a list of content that has been altered.
 
Many developers don't think about these scenarios until it's too late, leading to runtime errors, state corruption, and a confusing patchwork of bug fixes. In this talk, I'll be covering a handful of ways we've learned to deal with these situations in Open edX. We'll cover real examples, and why certain mitigations are appropriate for each situation.

## Detailed Description

**Format: Lightning Talk**

I can't attend the conference this year. I'd pre-record, unless someone else is interested in giving this one. 😞 

**Audience: Developers**

A lightning talk is too short to go into too much detail, but my hope is to get people to be aware of the issue, and to get them thinking about some of the high level options that they have in dealing with them.

**Outline**

I'd cover the following approaches:

1. Eliminate Incompatible State at Runtime
  *Example: Saved positions*
2. Ignore Incompatible State at Runtime
  *Example: Saved answers*
3. Provide a Mechanism for State Correction
  *Example: Re-scoring*
4. Use Explicit Versioning
  *Example: Content Libraries*
5. Make Defensive Copies
  *Example: Open Response Assessment Rubrics*

-------------

I'll use comments in this ticket to keep track of ideas that I want to include, as I think of them.

**Comment by ormsbee** [comment]
Self-Note: Mention storing explicit IDs (e.g. UsageKeys), instead of relying on random seed values (see Python 2 → 3 upgrade) or indexing into lists (whose elements may change).

**Comment by arbrandes** [comment]
The header pic could not be more appropriate. 👍🏼

**Comment by ormsbee** [comment]
Just saw an ADR for another situation in which someone's gotten bitten by this issue:

* https://github.com/openedx/edx-platform/pull/29928
