### ISSUE TITLE
[GH Request] Grant @mariajgrimaldi commit access to edx-platform 

### ISSUE THREAD

**Issue by ormsbee** [openedx/tcril-engineering#160]
### Firm Name

tCRIL

### Urgency

Medium

### Requested Change

Grant @mariajgrimaldi commit access to edx-platform.

### Reasoning

@mariajgrimaldi has been [added as a Core Contributor](https://discuss.openedx.org/t/core-contributor-nomination-maria-grimaldi/6548/14?u=dave) and should be granted commit access to the edx-platform repo (as well as openedx-events and openedx-filters, but those are both still in the eduNEXT org).

### Checklist

- [x] Reach out to any relevant CEO/CTO of new CC’s company to get approval for the new developer member to be nominated for the program.
- [x] Per OEP-54, nominate the developer for various access.
- [x] Send Core Contributor Program Agreement for signature
- [x] Set up access for Committer in privacy & a11y courses:

(Details: via instructor dashboard, add the Committer via email, Ensure the Committer is added to the right cohort in the course: ([Privacy & security - separate cohort ("core committer", historic)](https://courses.edx.org/courses/course-v1:edX+edXPrivacy101+2021/instructor#view-cohort_management), [a11y - tell them to take the Engineering specific content](https://courses.edx.org/courses/course-v1:edX+AC104+3T2020/instructor#view-membership)) Upon their confirmation, welcome them to the Core Contributor Program via email, cc’ing current Committers, company CEO/CTO, tCRIL eng team [+others TBD]. Welcome them to the program. Send them to this runbook and attach any missing legal documents that Legal has indicated are missing.)

### Upon receipt of missing legal documents and confirmation that training courses have been taken:

- [x] Invite the Committer to the Open edX #core-contributors Slack channel and the @core-contributor-committers Slack user group, as well as the relevant [shared Slack channel(s)](https://docs.google.com/spreadsheets/d/1ryqbaxMp4x-8Apwss2Br2IOU2UA7zXEI-VDo8dJPb9U/edit?usp=sharing) corresponding to their merge accesses (read more about this change [here](https://docs.google.com/document/d/1-G-v3nrP8RN_j0P8gEsdI0ahdOoJFePiDHFOuPlUjlk/edit#heading=h.wsc5ai1lrvb6)). Welcome them in Slack!
- [x] Add them to the Google group: https://groups.google.com/a/tcril.org/g/core-contributors-dev - this is very low traffic, meant primarily for announcements we want to be sure get to all developers.
-  [x] Have edX ensure merge rights for Committers:

Details: Create a new 1-person GitHub “team” for the new Committer under the existing https://github.com/orgs/edx/teams/core-contributor-program-committers GitHub team. Follow the existing naming convention for CC teams: CCP Committer: <github username>.Give the Committer [GitHub write access](https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/repository-permission-levels-for-an-organization#permission-levels-for-repositories-owned-by-an-organization) to designated repositories (using their new GitHub team).

If applicable, add them to the MERGERS variable in the pr-automerge-open-release.yml file ([.github/pr-automerge-open-release.yml at master · openedx/.github](https://github.com/openedx/.github/blob/master/.github/workflows/pr-automerge-open-release.yml#L11-L15) ) for access to all Open edX release branches.

- [x] Send the CC the link to request a Core Contributor t-shirt!

**Comment by ormsbee** [comment]
@kdmccormick: Should I manually create a "CCP Committer: mariajgrimaldi" group for @mariajgrimaldi and place her in it? Or do we have fancier automation/accounting of this now?

**Comment by kdmccormick** [comment]
I think we'll want the group, although I'm gonna pull in @sarina because I think she has a certain process here that she's done with the other coding CCs.
