### ISSUE TITLE
Explore Google Open Source Season of Docs

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/tcril-engineering#165]
Explore either applying or studying the case studies for inspiration and guidance. 

https://opensource.googleblog.com/2022/02/the-2022-season-of-docs-application-for-organizations-is-open.html

**Comment by feanil** [comment]
The [Oppia](https://docs.google.com/document/d/1TaZq7QuQRxVNawXOLRHbj7PSvFdI17XG2516D-CGM_E/edit) and [Numpy](https://github.com/numpy/numpy/wiki/Google-Season-of-Docs-2021:-NumPy-Case-Study) case studies were both pretty interesting.

In general, it looks like having a clear vision of what docs need to be written and having access to the subject matter experts seem to be keys to success.  The measurements seem to be in the form of which docs get written in some cases and in terms of how many users use it in other cases.  I think we're getting close to figuring out which docs need to be written but I'm not sure if we have the right experts lined up to start building out those docs.

**Comment by jmakowski1123** [comment]
I agree, I think that we need to scope content types and a process for finding authors. One idea could be to make some of these BD projects - for example I think curricu.me would be great to partner with to write instructional design materials. I'm going to suggest we find some dedicated time to actually scope and grroom the next set of Milestones for documentation - either with Mark on Monday, or we find a separate hour to hammer at it? @feanil
