### ISSUE TITLE
Migrate DEPR issues from Jira to appropriate repos

### ISSUE THREAD

**Issue by sarina** [openedx/tcril-engineering#167]
See https://docs.google.com/spreadsheets/d/14lv5Q257hq_X_JoF8UbGD3ulR7e8vqfa7hcaxpntMbI/edit#gid=310406614

- [ ] Migrate DEPR tickets for edx-platform to public-engineering
- [ ] Migrate other repo tickets to that repo

For repos that have a DEPR ticket but do not have Issues turned on, you should turn on Issues. There's a special config in those repos which'll only show DEPR templates and disallow other types of issues.

**Comment by feanil** [comment]
For now we've moved all historic tickets to the public-engineering board.  Many of them need to be reviewed and so we'll move them to the relevant repo as the working group goes through the tickets.  New tickets will be made in the relevant repo.
