### ISSUE TITLE
Request CC Access: Feanil

### ISSUE THREAD

**Issue by sarina** [openedx/tcril-engineering#171]
Per https://discuss.openedx.org/t/tcril-and-core-contributors/6686/, start a new Discourse thread, following OEP-54's procedures, to get consensus on your existing GitHub access: both write access and org-admin access.

Template:

Per the [conversation here](https://discuss.openedx.org/t/tcril-and-core-contributors/6686/) as well as [OEP-54](https://open-edx-proposals.readthedocs.io/en/latest/processes/oep-0054-core-contributors.html), I'm asking that the community take a look at my access levels and determine if they are appropriate. I appreciate your consideration, and am here to answer any questions you might have. You may PM me or anyone at tCRIL if you have specific concerns about this request.

**Comment by feanil** [comment]
CC Access has been granted! https://discuss.openedx.org/t/coding-cc-rights-feanil-patel/6718/8
