### ISSUE TITLE
[GH Request] Onboarding 2 users

### ISSUE THREAD

**Issue by tnamgyal** [openedx/tcril-engineering#174]
### Firm Name

edx/2U

### User List

Abdou Seck @abdouseck
Hamza Kazmi @Hamza442

### Start Date

3/1/2022

### Urgency

Medium - They need access for on-call schedule starting next week

**Comment by sarina** [comment]
@tnamgyal when you make requests, could you please add a title? And I assume - @tnamgyal @kdmccormick - that these requests are always for push-pull-all access because there's no field to explain what access is needed?

**Comment by tnamgyal** [comment]
@sarina - apologies! Edited to add title and yes, they both need push-pull-all access.

**Comment by kdmccormick** [comment]
Will take a look tomorrow 👍🏻

**Comment by kdmccormick** [comment]
Invites sent!
