### ISSUE TITLE
[GH Request] aws ecr secrets needed for codejail repo

### ISSUE THREAD

**Issue by aht007** [openedx/tcril-engineering#181]
### Firm Name

2U

### Urgency

Priority Issue to unblock codejail CI. Need this to be done as soon as possible

### Requested Change

The secret credentials for aws ecr account `TOOLS_EDX_ECR_USER_AWS_ACCESS_KEY_ID` and `TOOLS_EDX_ECR_USER_AWS_SECRET_ACCESS_KEY` are not available for codejail repository and we need these to be made available in this repository.

### Reasoning

These secrets are now needed as we are shifting the `codejail` CI from jenkins to docker image and we need to pull that image from the ecr repository. Currently our [workflow job ](https://github.com/openedx/codejail/runs/5389121344?check_suite_focus=true) is failing due to missing secrets and we would like get this done as soon as possible.

**Comment by kdmccormick** [comment]
Hey @aht007 - please share them via Keeper with kmccormick@tcril.org and I'll make sure they get added to the codejail repo ASAP.

**Comment by kdmccormick** [comment]
@aht007 change of plans: instead of sharing the secret with me, I've added you to the @openedx/temporary-codejail-access team which gives you admin rights on Codejail so you can configure the secrets yourself. Let me know when you don't need them any more.

**Comment by aht007** [comment]
Hey @kdmccormick, we don't want any new secrets to be added to the repository as these secrets are already available at organization level. We just want you to tweak the access policy of these secrets at organization level and make them available to the `codejail` repository

**Comment by kdmccormick** [comment]
Ahh, got it. Thanks for your patience @aht007 . I updated both secrets so that they can be used in codejail. Please re-open this ticket if you need me to do anything else.
