### ISSUE TITLE
Presentation to 2U Architecture Guild

### ISSUE THREAD

**Issue by ormsbee** [openedx/tcril-engineering#182]
Prepare an overview of Open edX to present at a 2U Architecture Guild meeting sometime during the week of 3/14.

Audience:

* Technical
* 2U staff who are new to Open edX and possibly open source community dynamics in general.
* Some edX'ers
* Large group setting, 50+
* Many of these developers will not work on Open edX directly, but might be interested in interfacing with it

Time: 1 hour, but leave time for questions.

We should cover at least:

1. Product: What is the set of things that constitute “Open edX”?
2. Community: Who works on this stuff and why?
3. Process: OEPs, ADRs, etc. – focusing on the delta between what they might be used to in the past.
4. Technical: Standard application stacks, list of services, potential points of integration, standards adoption, etc.

Suggestions/questions from Arch Hour:

* What are some consistent challenges you need to find solutions for?
* How do we approch arch decisions?
* Maybe Cover OEPs and community involvement.

@feanil, @davidjoy: I will use this ticket to track progress and jot down ideas. Please write any suggestions here. Thank you!

**Comment by davidjoy** [comment]
As I mentioned in Slack, I'm also happy to help prepare some content here if it's helpful.
