### ISSUE TITLE
[GH Request] Add @bseverino to frontend-wg as... maintainer?

### ISSUE THREAD

**Issue by davidjoy** [openedx/tcril-engineering#183]
### Firm Name

2U

### Urgency

Low urgency

### Requested Change

We want to add @bseverino to the https://github.com/openedx/frontend-wg repo for Frontend Working Group.  They're a member who needs edit access to the Github Issues, projects, PRs, etc.  I think that's probably "maintainer" permissions?  I'm not 100% sure.  We have a frontend-wg-admin team, but I imagine we want a frontend-wg-members team that we add members to.  I defer to your judgment on exactly what that should be/don't feel strongly, so long as folks we add can edit issues/PRs/projects.

Thanks!

### Reasoning

Bianca is a 2U employee who's a member of Frontend Working Group and helps maintain the backlog.

**Comment by ormsbee** [comment]
Added @bseverino to the frontend-wg-admin team, giving her admin-level access to the openedx/frontend-wg repo.

**Comment by ormsbee** [comment]
Note: I added her to that level of access because the group already existed and had other 2U employees in it.
