### ISSUE TITLE
[GH Request] Transfer tutor-contrib-coursegraph into openedx organization

### ISSUE THREAD

**Issue by kdmccormick** [openedx/tcril-engineering#185]
### Firm Name

tCRIL

### Urgency

Low urgency 

### Requested Change

Move [tutor-contrib-coursegraph](https://github.com/kdmccormick/tutor-contrib-coursegraph) into the openedx organization.

#### Rationale

tutor-contrib-coursegraph is a new Tutor plugin that enables CourseGraph. Although we haven't heard of CourseGraph usage outside of edX, I hypothesize that this is because we haven't made it easy yet. I think that analyzing course structure is something that any Open edX operators with sizeable course catalogs would find useful. This repo aims to make running CourseGraph easy.

This [Open edX Maple blog post](https://openedx.org/blog/announcing-coursegraph-a-new-tool-in-the-maple-release/) does a good job of explaining why community members might want to use CourseGraph.

#### Maintenance

For the time being, I propose that tCRIL maintain this repository. Eventually, once 2U is using Tutor, I think we could make a case for whoever owns CourseGraph at 2U to becoming the maintainer of this repository.

#### Status

See the README for up-to-date status. As of this ticket's writing, the plugin works for local development, ostensibly works for local deployment, and is yet-to-be implemented for kubernetes deployment.

The repo adheres to our standards:
* Its README describes its purpose, installation, usage, status, and contribution workflow.
* It tests the plugin's integration with Tutor on every PR (unit tests aren't really applicable).
* All code is linted, type-checked and format-checked on every PR.
* Commit messages are linted for conventionality.

**Comment by e0d** [comment]
Need some input from @kdmccormick on the provenance of this work when he returns from PTO.

**Comment by e0d** [comment]
@kdmccormick do we have useful scripting to use for the transfer or is a manual transfer the best path for this one?

**Comment by kdmccormick** [comment]
@e0d Nope, the transfer scripts we had written for the org migration were only useful because we needed to carry over various overlapping user/app/team access grants. Manual transfer should be fine for this.

**Comment by e0d** [comment]
@kdmccormick I believe that you need to initiate this, correct?

**Comment by kdmccormick** [comment]
You're right @e0d . And since I have admin rights on the openedx org, the transfer went through immediately.

I'm still glad we went through this process, though, for symmetry with the community.
