### ISSUE TITLE
Process for adding/surveying/removing users to security-notifications@edx.org

### ISSUE THREAD

**Issue by pshiu** [openedx/tcril-engineering#192]
Ahoy, tCRIL,

My name is Phil and I'm a part of the edX Security Working Group. Nice to meet you.

`security-notifications@edx.org` is the Google Group that gives maintainers of Open edX instances a heads up before security vulnerability fixes are released so they have time to patch their instances before the fix becomes live.

I believe we have wanted to add people to this list for some time now!

1.  Does tCRIL have any thoughts at this time for:

    1. the operation or hosting of this Google Group?
    2. a process for adding people to this list?

2. Would it make sense to add language on sign up such as:

    > Hello! Welcome to security-notifications@edx.org. This group provides Open edX security patches in advance of their release to the general public.
    > 
    > By joining this list, you agree not to announce the patch publicly before we officially share it with the general public.
    >
    > Any questions? Please reach out to security@edx.org. Thank you for your support of and participation in the Open edX community!

3. We have previously sent out a survey to better understand who are the people currently subscribed the security notifications mailing list.

    1. Do we want to send out the survey again, or on a regular basis?
    2. Do we want to remove people from the list who do not respond to the survey?

Note for self-reference: This is in re. https://openedx.atlassian.net/browse/SEG-75 and https://openedx.atlassian.net/browse/SEG-29.

Thanks,
Phil

**Comment by feanil** [comment]
Hello,  while I was still at edX, we had spoken with legal about getting some language that new users would have to agree to before being added.  I think that should still be a SEG ticket somewher.  I don't think we see any issues with adding more people to the working group.  As for the process for doing so, I might suggest announcing the existence and requirements for joining as a announcement post on discuss.openedx.org and then asking people to contact the security working group.


> Do we want to send out the survey again, or on a regular basis?
> Do we want to remove people from the list who do not respond to the survey?

Yes, the survey should be sent out annually, and any users that don't respond to it should be removed from the list and considered stale.

**Comment by pshiu** [comment]
@feanil, thank you very much!
