### ISSUE TITLE
Write a template with all basic required data/information to be included on Roadmap tickets

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/tcril-engineering#194]
Scope:

Tickets should convey: Basic definition of work; summary of scope and approach; and intended outcome; metrics.

Choose one epic currently on Roadmap to use as a template for circulation.

**Comment by jmakowski1123** [comment]
Template here: https://docs.google.com/document/d/1CyX3b-SMm9MS17woerL-EovdR-Cetj1k-BO8PPT7_9Q/edit

@sarina , do you mind if I add you to this ticket to transfer the google doc to a GH template? Gabriel and a few OpenCraft folks are currently reviewing the Google doc. Assuming no major edits/changes, this will be ready to move to GH by eod Wed 3/23. Thanks!!

**Comment by sarina** [comment]
@jmakowski1123 yep, just let me know when it's ready. I'll need to know what repo(s) to add this to, as well as what the display title & subtitle should be:

![image](https://user-images.githubusercontent.com/1985317/159548690-9fe7f34c-afb6-4346-a85b-92b3c34df76c.png)

**Comment by jmakowski1123** [comment]
@sarina Got the go-ahead from Gabriel!

1. I think the best repo is platform-roadmap
2. The display title can be "Open edX Roadmap Issue Submission", and the subtitle "Use this template to add in-flight and in-planning Initiatives to the Open edX Roadmap

**Comment by sarina** [comment]
@jmakowski1123 If you can confirm you got a notification for https://github.com/openedx/platform-roadmap/issues/129, I think you can go ahead & close this issue
