### ISSUE TITLE
Resolve CLA issue with new OpenCraft developer

### ISSUE THREAD

**Issue by jristau1984** [openedx/tcril-engineering#196]
### Firm Name

2U/OpenCraft

### Urgency

Medium Urgency (resolve in <one week)

### Requested Change

There is a new OpenCraft developer who believes he has completed his CLA, but still cannot interact with the codebase.

The developer's name is: Hamza Khchine

### Reasoning

Please investigate and resolve this blocking issue so he can move forward with his contracted work.  Thanks!

**Comment by e0d** [comment]
We don't have a record of Hamza associated with the OpenCraft entity CLA.  @jristau1984 OpenCraft needs to submit a request to add him.  I'll take this opportunity to have them review all of their staff.

**Comment by e0d** [comment]
I think I see the issue.  He was added to a shared sheet, but we don't automatically get notified when the sheet is updated.  I'll let Piotr and team know.

**Comment by e0d** [comment]
PR, https://github.com/edx/repo-tools-data/pull/161, has merge, closing this
