### ISSUE TITLE
Fix the i18n descriptions in frontend-app-gradebook

### ISSUE THREAD

**Issue by Carlos-Muniz** [openedx/tcril-engineering#2]
The i18n descriptions in [edx/frontend-app-gradebook](https://github.com/edx/frontend-app-gradebook) are not descriptive enough. The description strings are depended on by the Transifex WG in providing comprehensible multi-language support.

For example:
`
track: {
    id: 'gradebook.GradesTab.FilterBadges.track',
    defaultMessage: 'Track',
    description: 'Track FilterBadge label',
  }
`

**Comment by Carlos-Muniz** [comment]
[Merged!](https://github.com/edx/frontend-app-gradebook/pull/219)

**Comment by sarina** [comment]
🎉 🎊 😄
