### ISSUE TITLE
Create and share a discovery artifact that summarizes findings and recommendations from MFE pain point surveys/conversations

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/tcril-engineering#202]
Update: 6/9 - Change of scope:

The deliverable is an internal write-up/analysis of all the community feedback related to MFEs collected by Adolfo. The write-up is intended to:

-inform a first draft of an MFE Roadmap
-serve as a point of reference for the tCRIL team to discuss future prioritization of MFE work

Another change in scope is less of a focus on the positives and more of a focus on the critical points.
And no longer need to include views on trade-offs or alternatives.

***
After speaking with 6+ community members about their experiences, view and pain points around MFEs, summarize the findings into a discovery artifact. The artifact can include:

- A list/summary of what the community see as the major pain points around implementing MFEs
- Recommendations for removing those barriers
- A point of view on prioritizing which pain points/corresponding tickets have the highest ROI in terms of enabling smoother community workflows. This is not an effort estimation, but rather an estimation of highest value and impact. 

If relevant, include views on trade-offs or alternatives: 

- [ ] #204 

Template for inspiration in creating the discovery artifact: https://openedx.atlassian.net/wiki/spaces/OEPM/pages/3378118892/Discovery+Courses+Based+on+Atomic+Learning+Units

The discovery artifact can be circulated on the Product Management wiki and shared for feedback here: https://openedx.atlassian.net/wiki/spaces/OEPM/pages/3390701611/Areas+of+Improvement+for+Micro-frontends

**Comment by arbrandes** [comment]
Here it is, finally!

https://openedx.atlassian.net/wiki/spaces/OEPM/pages/3390701611/Areas+of+Improvement+for+Micro-frontends

**Comment by jmakowski1123** [comment]
> Here it is, finally!
> 
> https://openedx.atlassian.net/wiki/spaces/OEPM/pages/3390701611/Areas+of+Improvement+for+Micro-frontends

Yay!!
