### ISSUE TITLE
Publish openedx-events docs on readthedocs

### ISSUE THREAD

**Issue by robrap** [openedx/tcril-engineering#210]
I'd like https://github.com/openedx/openedx-events documentation to be published to readthedocs so I can cross-reference the docs from the Event Bus OEP.

Notes: 
* I'd love to have this out soon in preparation for recording my presentation. Is there any way I can help with this?
* You'll notice that the doc index is messed up because of the changelog. I already have an in-progress fix for that, so please ignore.
* I have a backup plan, but I'd like to use the final published docs if possible. Let me know either way.

Thank you!

**Comment by feanil** [comment]
https://github.com/openedx/openedx-events/pull/49 and https://github.com/openedx/openedx-events/pull/50 should resolve this. Waiting on reviews now.

**Comment by feanil** [comment]
Done: https://openedx-events.readthedocs.io/en/latest/

**Comment by robrap** [comment]
Thank you @feanil!
