### ISSUE TITLE
Offboard tuchfarber

### ISSUE THREAD

**Issue by kdmccormick** [openedx/tcril-engineering#22]
### User list

* Matt Tuchfarber, @tuchfarber
* ...

### Firm name

edX

### End date

?

### Retained permissions

By default, these users will be removed from the openedx organization and lose all team memberships and repository permissions. If any of the users should instead retain some permissions as "outside collaborators", please note that here.

### Follow-up

Once you create this request, the tCRIL engineering team will triage it and handle it as appropriate. If your request is especially urgent, please note that above!

**Comment by tuchfarber** [comment]
Ha! I was about to figure out to message you that I'm owner of way too many things on Github still. I noticed when I started getting emails as owner of repos earlier today. See ya friends :wave:

**Comment by kdmccormick** [comment]
Done.
