### ISSUE TITLE
Move Away from using repo-tools-data for CLAs

### ISSUE THREAD

**Issue by feanil** [openedx/tcril-engineering#221]
Currently we are using https://github.com/edx/repo-tools-data/ as the source of truth for the OSPR bot and CLA checks.  We should update our workflow so that we don't need to use a repo that's private to the `edx` org.

AC:
- Zapier automation that makes the PRs makes them against a new repo.
- Any bots that need access to this repo should be given access to the new repo.
- The bot code should be updated to read the data from the new location instead of the old one.
- edX IT should be informed that we no longer need access to the `repo-tools-data` repo so they can revoke access for the relevant tCRIL folks.

**Comment by e0d** [comment]
@feanil we'll need to communicate this change to @natabene as well, she follows to understand CLA status.  So, this may be a special case of permissions that we don't have to date.

**Comment by Carlos-Muniz** [comment]
Pretty sure this is the line we would have to change, if we merely recreate the schema in a different repo: [openedx/openedx-webhooks/info.py:41](https://github.com/openedx/openedx-webhooks/blob/edfb18cff95ad49fc1d160a1f59dae0a2e9af606/openedx_webhooks/info.py#L41)

**Comment by natabene** [comment]
Please make sure I continue to have access to the CLA statuses, either in this repo or a new one you set up.

**Comment by feanil** [comment]
openedx-webhooks has been updated to use the new `openedx-webhooks-data` repo as its source of truth.  @natabene and the tcril engineering team has access and the automation has been updated to make new salesforce export PRs to that repo.

There's some further improvements that can be made but this task is complete.
