### ISSUE TITLE
Put eduNEXT instances on subdomains

### ISSUE THREAD

**Issue by sarina** [openedx/tcril-engineering#239]
There are two eduNEXT instances that we want on subdomains. This is private for now so details will be communicated separately.

Subdomains will be training. & sandbox.

Ping Sarina for access to these. Will need to enlist eduNEXT help on the sandbox instance because iirc no one at tCRIL has admin access.

**Comment by sarina** [comment]
Decided this is on-call work this sprint.

**Comment by sarina** [comment]
@feanil is this going to take some time to propagate? when i go to the training URL i get an insecure connection then this page: 

![image](https://user-images.githubusercontent.com/1985317/169160578-0acd9c36-4580-4074-b8af-d8a706b72051.png)

**Comment by feanil** [comment]
@sarina according to their docs once the domains have been updated, there is something tho eduNext has to do.

> 3. Informing the eduNEXT support team about your configuration. Once you’ve made your changes, make sure to inform the eduNEXT support team of the domain or subdomain that you configured so that all the configurations can be tested and applied to production. You can do so by sending a support ticket with this information.

I had not done that because I thought that was a task you would do after this ticket was done but re-reading I see that this was meant to encompass the DNS updates as well as all the follow-up.

I'm gonna re-open it.  I can do the follow-up next week or feel free to take it before then.

**Comment by sarina** [comment]
Ah, I had also missed that instruction. I can do the follow-on, I'm already talking to Juan about another thing.

**Comment by sarina** [comment]
OK, that was easy. I filed the support ticket for the training site and let Juan know about the sandbox. I'll keep this open & assigned to me until that is resolved.

**Comment by sarina** [comment]
Update: We'll need to create some more subdomains, but I am waiting to hear back from Juan on the specifics.

**Comment by sarina** [comment]
I believe we've set everything up properly, but the sandbox domain is not resolving. Just emailed Juan.
