### ISSUE TITLE
[GH Request] Onboard @noisecapella

### ISSUE THREAD

**Issue by noisecapella** [openedx/tcril-engineering#240]
### Firm Name

2U

### User List

@noisecapella

### Start Date

ASAP

### Urgency

Low urgency, no immediate need. This should have been done during onboarding but the step was skipped

**Comment by sarina** [comment]
Hi @noisecapella - this ticket needs to be filed by your manager or IT, to verify you are who you say you are 😄 

Could I ask you to do the following:

* Update any onboarding instructions that told you to file this ticket, replacing it with instructions to have the manager or IT file the ticket;
* Ask your manager or IT to file this ticket.

Thanks!
