### ISSUE TITLE
[GH Request] Archive frontend-learner-portal-base

### ISSUE THREAD

**Issue by Zacharis278** [openedx/tcril-engineering#242]
### Firm Name

2U

### Urgency

low

### Requested Change

Archive the frontend-learner-portal-base library and move it to the unsupported org as it has been deprecated. DEPR ticket here: https://github.com/openedx/frontend-learner-portal-base/issues/31

### Reasoning

This library is no longer in use by any project

**Comment by sarina** [comment]
Acking request. I will get to it this week, possibly not until later.

**Comment by sarina** [comment]
Moved to https://github.com/openedx-unsupported/frontend-learner-portal-base
