### ISSUE TITLE
[GH Request] Onboard HassanJaveed84

### ISSUE THREAD

**Issue by sbishop0905** [openedx/tcril-engineering#243]
### Firm Name

2U

### User List

Full name: Hassan Javeed
github username: HassanJaveed84

### Start Date

4 April 2022

### Urgency

High urgency

### Special Requests

Hi, apologies for the high urgency, he recently joined back as a 2U employee (vs Arbisoft), so did not realize his access had been revoked. I would like to ask he be reinstated quickly in order to unblock him on a ticket

**Comment by sarina** [comment]
@sbishop0905 on it!

As a note, when filing GH Request tickets, it would be great if you could give your ticket a meaningful title. That means editing the default title to replace the placeholder text with text that indicates your request. Thanks!
