### ISSUE TITLE
[GH Request] Granting access to openedx-events to 2u user

### ISSUE THREAD

**Issue by felipemontoya** [openedx/tcril-engineering#244]
### Firm Name

eduNEXT

### Urgency

High

### Requested Change

2u user:
Rebecca Graber
email: rgraber@edx.org
github: rgraber

requested write access to the openedx-events repo for her work on the event-bus bridge

### Reasoning

robrap had asked me long ago for their team members to be added and rgraber did not use the invite. She asked again via slack.

This ticket is to track the changes as instructed in the wiki.

Edit: the initial list requested by robrap was: timmc-edx, dianakhuang, davidjoy, jinder1s, jmbowman, rgraber

**Comment by felipemontoya** [comment]
Just tracking the change. The user was invited to the repo

**Comment by sarina** [comment]
thanks @felipemontoya - can you add to the ticket description what other team members were added too?
