### ISSUE TITLE
[GH Request] Onboard <user or users>

### ISSUE THREAD

**Issue by adzuci** [openedx/tcril-engineering#252]
### Firm Name

2U

### User List

farhanumar

### Start Date

25 April 2022

### Urgency

Any time this week would be great, let me know if that's too aggressive though.

### Special Requests

Farhan is a new SRE joining the edX SRE team at 2U from Arbisoft.  Please also add him to the `site-reliability-engineering`, `devops` and `edx-admin` teams as well.

Side note: Is edx-solutions-admin still in use?  I see I'm in it, but forget what it's for: https://github.com/orgs/openedx/teams?query=%40adzuci

**Comment by ormsbee** [comment]
@adzuci: Invitation sent. He should be on those groups.

**Comment by ormsbee** [comment]
(for future readers of this ticket): edx-solutions-admin gives admin rights to:

* openedx/xblock-adventure 
* openedx/xblock-drag-and-drop-v2 
* openedx/xblock-google-drive 
* openedx/xblock-image-explorer 

Some of those repos are definitely still in use (definitely drag and drop v2). As to whether the people in that group actually use their access for anything, I don't know.
