### ISSUE TITLE
[GH Request] Onboard nickpizzo

### ISSUE THREAD

**Issue by mulby** [openedx/tcril-engineering#257]
### Firm Name

2U

### User List

* Nick Pizzo, @nickpizzo

### Start Date

2022-05-03

### Urgency

High -- blocking 2U dev work

### Special Requests

Nick is a contractor working for 2U, he specifically needs access to merge changes to openedx/course-discovery, but it would be fine to add him to push-pull-all.

**Comment by ormsbee** [comment]
User @nickpizzo invited and added to push-pull-all.
