### ISSUE TITLE
[GH Request] Need write access to openedx/.github

### ISSUE THREAD

**Issue by Jawayria** [openedx/tcril-engineering#259]
### Firm Name

2U 

### Urgency

Moderate

### Requested Change

I need write access to openedx/.github

### Reasoning

I need write access to openedx/.github as I've been working on workflow templates actively. You can refer to the commit history [here](https://github.com/edx/.github/commits/master). Now we've moved most of the repositories under openedx organization so we'll have to add workflow templates here as well. For instance, currently I am working on a workflow template for package-lock file version check but I don't have access to merge it. [Here](https://github.com/openedx/.github/pull/10) is the PR.

**Comment by ormsbee** [comment]
@Jawayria: What is your team and who is your manager?

Thank you.

**Comment by Jawayria** [comment]
Team: Arbi-bom
Manager: Jeremy Bowman

**Comment by Carlos-Muniz** [comment]
Hello @Jawayria, We have created a new team called workflow-maintainers, with write access to openedx/.github. You have been added to this team. In the future, please request that your manager files tickets like this on your behalf.
Thank you!

**Comment by nedbat** [comment]
Oops, I gave @Jawayria incorrect instructions.. Sorry about that.
