### ISSUE TITLE
Prune openedx org teams and users - post repo transfer

### ISSUE THREAD

**Issue by sarina** [openedx/tcril-engineering#26]
#### Context
When we transferred repos from the `edx` org to the `openedx` org to reduce complexity and simplify the work, we copied over all teams and invited all the users form `edx`.  Now that the repo transfer is completed, there are a lot of teams and potentially people that can be reviewed more holistically and potentially removed from the `openedx` org.

AC:

* Any empty teams have been removed.
* Any users that are in the org but don't have access to any repos, or boards are removed from the org.
  *  Be extra careful with bot users and do thorough verification that they're not being used in some weird way before removing them.

Stretch:
* Make any users that have direct access to repos, have that level of access via a team instead.
  * Don't mess with actual outside collaborators, just users that are no longer outside collaborators but have permissions directly to the repo instead of via a team.

**Comment by feanil** [comment]
Ran and merged https://github.com/openedx/terraform-github/pull/31 to remove 49 fully empty teams. There's about 60 more that will get removed today or tomorrow after the comment period is done on it.

**Comment by feanil** [comment]
https://github.com/openedx/terraform-github/pull/33  cleans up any users that don't need to be in the org.

Once we cleanup the teams with members and nothing else, this should be all done.

**Comment by feanil** [comment]
Users and teams have been cleaned up.  I left some of the teams that had users but didn't have associated repos because they were clearly being used just for talking to groups in comments.  ie. the perf-interest group.
