### ISSUE TITLE
[GH Request] Move edx-notifications into unsupported

### ISSUE THREAD

**Issue by dianakhuang** [openedx/tcril-engineering#262]
### Firm Name

2U

### Urgency

Low

### Problem/Request

We have passed the acceptance date on the (corresponding DEPR ticket)[https://github.com/openedx/edx-notifications/issues/253] . It does not seem like there are any blockers to moving this repo to unsupported.

### Reasoning

This repo was previously part of edx-solutions and is no longer particularly well supported. We believe its presence in the openedx organization is more confusing than helpful.

**Comment by Carlos-Muniz** [comment]
Thanks for this request. The repo edx-notifications has been Archived and moved from openedx to openedx-unsupported. In addition a note with links has been left in the README of edx-notifications.
