### ISSUE TITLE
[GH Request] New repository: openedx-test-course

### ISSUE THREAD

**Issue by kdmccormick** [openedx/tcril-engineering#267]
### Firm Name

tCRIL

### Urgency

Medium-High (will help us test Nutmeg, which is due out June 9)

### Problem/Request

Create a new repository named `openedx/openedx-test-course`.

### Reasoning

As we test Nutmeg, we are finding that many test cases require creating course content. In order to avoid recreating this content every time the test instance is recreated, we'd like to store it in a test course.

The vision of this test course repo would be: *A course and libraries that exposes as many built-in Open edX features as possible by providing example usages of the various block types and enabling various course features from Advanced Settings*.

Why not just add to the demo course? The [demo course](https://github.com/openedx/openedx-demo-course), as far as I can tell, is meant to be a curated selection of example content suitable for learners to experience as their first Open edX course. Many instances import it by default. As such, major changes to it should be reviewed by folks with course authoring and/or pedagogical experience. This test course, on the other hand, would just be a pile of test content. There should be some structure to it for our own sanity, but we wouldn't be thinking about the learner experience. 

Example organization of the repo:
* ./test_course/ -> the course root
* ./test_problem_bank/ -> a v1 library of problems, to be used in the course
* ./test_video_bank/ -> a v1 library of videos, to be used in the course
* ./test_mixed_bank/ -> a v1 library of various component types, to be used in the course
* ./README.rst
* ./Makefile -> utilities for validating and tarring, and untarring the courses & libraries

Maintainership: I propose that either the Build Test Release WG or tCRIL would maintain this repo.

**Comment by feanil** [comment]
@kdmccormick currently there is no clear owner/maintainer for the demo course and while the goal you have is not unreasonable, I think it may be more aspirational than the current reality of things.  The most recent updates have been to un-break content that was missing and I think adding more content to showcase various features wouldn't be a bad thing.

I might suggest just using the one course unless there is someone who can maintain a separate course for introduction today.

**Comment by kdmccormick** [comment]
@feanil Maybe I'm not being clear enough about the exact need here. BTR is currently coordinating testing of 200+ Open edX features for Nutmeg. By Olive that list will probably have grown to 400+ as our list is quickly becoming more comprehensive. Many of these test cases require making course content. So far we have been recreating that course content by hand every time we encounter such a test case. This repo would exist specifically to solve that problem

If I changed:

> I propose that either the Build Test Release WG or tCRIL would maintain this repo.

to

> BTR would maintain this repo

would you feel differently?

**Comment by feanil** [comment]
I think I was failing to be clear, I was saying, let's just use the existing course until we have a clear need for a new one because the current course actually has no clear agreed upon purpose today.  But now that I better understand  how big the test course might get, I think I understand why you want them to be separate.  I'll make the new repo.  Who should be the maintainers for that repo?

**Comment by feanil** [comment]
https://github.com/openedx/openedx-test-course has been created and I've added Kyle and Sofiane as maintainers of a team that has write access to the repository.
