### ISSUE TITLE
[GitHub Request] Create repo for Backstage

### ISSUE THREAD

**Issue by e0d** [openedx/tcril-engineering#269]
Backstage presents itself as a mono repo created by their tooling, including tools to keep your code synchronized with the upstream.

The project teams recommendation is to check in your application directory into SCM.

Code changes are required to do many things you might expect to be possible via configuration changes like changing your sign-in provider, integrating with GitHub for catalog management, etc.

Some details on the maintenance process are here, https://backstage.io/docs/getting-started/keeping-backstage-updated

**Comment by feanil** [comment]
Hey Ed, is this going to be a public repo or private?  If it's public, do you need a private counterpart to house the relevant config?

**Comment by e0d** [comment]
The config is probably mostly environment variables.  Repo may be overkill
for that, perhaps a setenv file in Keeper?

I think the main repo can be public.

Ed.

**Comment by feanil** [comment]
Repo created and you should have write access.

FYI, I created it with an Apache 2 license because that is what upstream had but feel free to correct that however it makes sense.

https://github.com/openedx/openedx-backstage
