### ISSUE TITLE
Change PyPI ownership

### ISSUE THREAD

**Issue by sarina** [openedx/tcril-engineering#27]
+ https://pypi.org/user/edx/
+ create Open edX pypi organization
+ do we need to change the name?
+ publishing to PyPI is an ownership responsibiility
+ would 2U need their own PyPI?  Probably.

**Comment by jmakowski1123** [comment]
Later H2

**Comment by sarina** [comment]
@feanil @nedbat what do you think the priority of this is right now?

**Comment by feanil** [comment]
It looks like the PyPI password was change and openedx no longer has access, we'll need the credential or need to work with someone at 2U to transfer ownership of various projects to a new user.  My understanding was that we would retain access to this user.

**Comment by sarina** [comment]
Is this something you think we should tackle by end of year? It would probably be a few hours of work?

**Comment by feanil** [comment]
I think it's worth doing before the end of the year yes.  I think it will be less than a day if we can script it up, but may be more if it's manual.

**Comment by sarina** [comment]
Makes sense.

@jmakowski1123 could we schedule this for early Oct, maybe?

**Comment by nedbat** [comment]
If we make a new openedx account to host the public docs, what happens to the URLs that are out there pointing to edx.readthedocs.io?  Can we redirect them globally? (If forget what readthedocs offers for redirections).

**Comment by nedbat** [comment]
Oops, mis-read!  PyPI ownership wouldn't be an issue, since it's not namespaced for users.  Sorry for the noise.

**Comment by feanil** [comment]
This is done now, there are a few projects that need further attention which we've captured in https://github.com/openedx/public-engineering/issues/174
