### ISSUE TITLE
[GH Request] Archive TLPhotoPicker repo

### ISSUE THREAD

**Issue by sarina** [openedx/tcril-engineering#272]
### Firm Name

tCRIL (on behalf of 2U)

### Urgency

Low

### Problem/Request

TLPhotoPicker repo can be archived & moved to openedx-unsupported

### Reasoning

@jmbowman says, "I got confirmation that the Mobile squad isn't using TLPhotoPicker, you should be clear to move that one to openedx-unsupported."

**Comment by feanil** [comment]
Done.
