### ISSUE TITLE
[GH Request] Onboard abdullahwaheed and BilalQamar95

### ISSUE THREAD

**Issue by jmbowman** [openedx/tcril-engineering#273]
### Firm Name

2U

### User List

* Muhammad Abdullah Waheed Khan, @abdullahwaheed
* Bilal Qamar, @BilalQamar95

### Start Date

26 May 2022

### Urgency

High urgency - already blocking work

### Special Requests

These are Arbisoft contractors for a new FED-BOM squad of front end developers.  Having a "fed-bom" team for them would be useful to ping for PR reviews and such.  There will be one more member shortly, I'm just awaiting confirmation of his GitHub username.

**Comment by feanil** [comment]
Both members invited and they'll be added to the @openedx/fed-bom team when they join.  @jmbowman I've made you a maintainer of that team.

**Comment by jmbowman** [comment]
@feanil It looks like they weren't added to the push-pull-all team; I know there are talks about changing how we do that, but can we add them until we have a new plan for that?  They'll be needing access to a pretty broad variety of repositories with front end code, with immediate plans to do work in at least the following repos:

- edx-analytics-dashboard
- edx-platform
- edx-proctoring
- edx-ui-toolkit
- frontend-app-accounts
- frontend-app-profile
- frontend-build
- studio-frontend

**Comment by feanil** [comment]
I've added them to push-pull-all for now until we figure out what the new plan is.
