### ISSUE TITLE
[GH Request] Onboard mamankhan99

### ISSUE THREAD

**Issue by jmbowman** [openedx/tcril-engineering#274]
### Firm Name

2U

### User List

* Maman Khan, @mamankhan99

### Start Date

26 May 2022

### Urgency

High urgency - already blocking work

### Special Requests

He is an Arbisoft contractor for a new FED-BOM squad of front end developers. Having a "fed-bom" team for them would be useful to ping for PR reviews and such (it may have already been created in my last onboarding request for the other 2 team members).

**Comment by feanil** [comment]
Invited and will be added to @openedx/fed-bom when they accept.

**Comment by jmbowman** [comment]
He'll also need push-pull-all team membership or something comparable, same as for the other two.  More context in https://github.com/openedx/tcril-engineering/issues/273#issuecomment-1144336237
