### ISSUE TITLE
Google Analytics 4 Upgrade

### ISSUE THREAD

**Issue by feanil** [openedx/tcril-engineering#279]
Google Ananlytics will no longer process new data in standard properties beginning July 1, 2023. Prepare now by setting up and switching over to a Google Analytics 4 property.

More Info: https://support.google.com/analytics/answer/11583528

Two important things are happening as a part of this change.
1. We won't be able to collect new data via GA on various properties until we update them.
2. On Jan 1, 2023 we won't be able to access the historic data from the old GA Properties.

Recommended actions:
1. Migrate existing GA properties to GA4
2. Review and determine which properties should have their data backed up and backup the data.

Properties to be migrated and potentially backed up:
- [x] Open edX 2019 Eventbrite (UA-60396627-4)
- [x] Open edX Conference (UA-76355352-1)
- [x] Open edX Conference (UA-60396627-3)
- [x] Open edX Conference Schedule (UA-60396627-5)
- [x] Open edX Discourse (UA-60396627-6)
- [x] Open edX Portal (UA-60396627-2)

**Comment by sarina** [comment]
Do we have property of the openedx.org website? We set GA cookies there

**Comment by feanil** [comment]
The "Open edX Portal" property is for the open edx site.

**Comment by e0d** [comment]
TIL that we've been using edX Google tag manager configuration.  This was a level of indirection I was not aware of.  I'll create the GTM account for us and move our new analytics properties to it.

**Comment by e0d** [comment]
Discourse is configured to use GA directly and not via tagmanager.  I've created a linked GA4 tag for the existing universal tag and updated the configuration in discourse.

![Image](https://user-images.githubusercontent.com/1270274/176041334-cf561477-b674-42d3-87c8-411e8cc620a0.png)

**Comment by e0d** [comment]
There are two separate properties for the Open edX Conference site, con.openedx.org.  I'm move UA-76355352-1 to the trash.

**Comment by e0d** [comment]
- Wordpress integration of the new tag manager code is in progress with the team
- PR is open for updating the conference site, https://github.com/openedx/openedx-conference-website/pull/26

**Comment by e0d** [comment]
This has been completed for openedx.org and con.openedx.org.

Both the new and old properties remain in GA.  GA4 properties are clearly named.  Both of these sites are connected via Google Tag Manager.
