### ISSUE TITLE
Review MFE config API PR

### ISSUE THREAD

**Issue by arbrandes** [openedx/tcril-engineering#282]
The authors are aiming for inclusion in Nutmeg, so the sooner this goes through a review cycle, the better.

https://github.com/openedx/edx-platform/pull/30473

Also see [this conversation](https://openedx.slack.com/archives/C02BMP2RD5Y/p1654010834336219) on Slack.

**Comment by MaferMazu** [comment]
Thanks @arbrandes for giving visibility to this.

Maybe it's important to review these PRs too:
https://github.com/openedx/frontend-platform/pull/335
https://github.com/openedx/frontend-app-account/pull/603

Both mentioned here: [MFE runtime configuration](https://github.com/openedx/frontend-wg/issues/103)

**Comment by arbrandes** [comment]
edx-platform review pass is done.  I'll handle the others in separate tasks.
