### ISSUE TITLE
[GH Request] Relicense edx-django-utils from AGPL to Apache

### ISSUE THREAD

**Issue by timmc-edx** [openedx/tcril-engineering#289]
### Firm Name

2U

### Urgency

Would like to get this done in a few weeks

### Problem/Request

The [edx-django-utils repo](https://github.com/openedx/edx-django-utils) is currently licensed AGPL 3, but according to the [Open edX licensing guidelines](https://openedx.atlassian.net/wiki/spaces/OPEN/pages/13959332/Licensing) it would be more appropriate as Apache 2.

This comes up now because I wrote [some code](https://github.com/openedx/edx-platform/blob/master/openedx/core/djangoapps/util/ip.py) in edx-platform but I would like to make available [EDIT: to both other IDAs and] to the larger Python community, and it would make the most sense to put it in edx-django-utils. However, Apache would be a better license, and edx-django-utils probably should have been Apache-licensed from the get-go anyhow.

### Reasoning

edx-django-utils contains some generally useful code that's not particularly specific to any one IDA and is mostly just fairly generic Django- and monitoring-related things.

I could also move the new IP-determination code into its very own Apache-licensed library without coordination with tCRIL (since that code was written by 2U employees) but it's not clear that it's worth creating an entire library for it.

**Comment by sarina** [comment]
FYI to whomever picks this up - you'll probably want to discuss this a bit with Legal to figure out the right process & implications of making this change.

**Comment by arbrandes** [comment]
Waiting on legal confirmation that this can be done without repercussion.

**Comment by e0d** [comment]
@arbrandes still blocked?

**Comment by arbrandes** [comment]
@e0d, still waiting on legal, so technically still blocked.

**Comment by arbrandes** [comment]
Update: apparently, this will require some unforeseen legal leg-work.  It's happening, but we don't have a timeline yet.

**Comment by kdmccormick** [comment]
Legal just cleared this, we're all good to change the license to Apache v2. @timmc-edx could you open a PR and tag me for review?

**Comment by kdmccormick** [comment]
By the way, we'll still need to reach out to our legal counsel every time we change a repository's license, but the next time we change a repo from AGPL to Apache (if ever) should be much quicker now that we've laid the legal groundwork for that specific type of change.

**Comment by timmc-edx** [comment]
Version 5.0.1 released under Apache 2. Thank you!
