### ISSUE TITLE
[GH Request] Create repo kafka-event-bus

### ISSUE THREAD

**Issue by robrap** [openedx/tcril-engineering#291]
### Firm Name

2U

### Urgency

Medium Urgency. Hope to work on this very soon.

### Problem/Request

We would like a repo created named kafka-event-bus. Please let us know if this will be a slow process, and we will instead created it under the "edx" org and move it later.

Summary: An event bus implementation using Apache Kafka.

Description: An event bus implementation using Apache Kafka. See openedx-events for event bus related interfaces and documentation.

Note: I copied the following from our docs, in case you want to create a new Github issue template or other relevant docs for this. Clearly not all fields or details will be appropriate.

-------------------------

Name: What is your desired name for the repo?

    Visibility: Public or Private

    Summary: A short description of the repo that will show in list views, search engine results, chat link expansions, etc.

    Organization: Which org should it live under? (e.g., edx, edx-ops, edx-it)

    Permissions:

        Push: Who should be able to push?

        Pull: Who should be able to pull?

    Default branch name: Github now creates repos with a default branch called main, but for IDAs (including MFEs) the default branch should be called master for consistency.

    Protected Branch: We'll protect master/main from force pushes by default. Let us know if you want this turned off.

    License: We'll turn on the AGPL license by default, as per Open Source's policy. Please check with Open Source if you want another policy.

    Description: What is the brief description/purpose of this repo. This will be displayed at the top of the repo on [Github.com](http://github.com/)

For Python repos:

    Use the Cookiecutter repo if one exists for your purpose: https://github.com/edx/edx-cookiecutters

        Please be sure to setup the repo according the the guidelines specified in the repo.

        Please be sure to edit openedx.yaml in your new repo to be accurate!

    Enable publishing of the package in PyPI

        DEPRECATED: [Publishing a Package to PyPI using Travis] (this should be done via Github Actions)

        You may need to open a [support ticket] to get the PyPI edX credentials from SRE.

For front-end repos:

    For microfrontends, see [How to: Create and Deploy a new Microfrontend inside edX](https://2u-internal.atlassian.net/wiki/spaces/FEDX/pages/11765101).

    For libraries, use [edx/frontend-component-header](https://github.com/edx/frontend-component-header) as a template.

        Create an [SRE support ticket] for add the right Github Secrets for the semantic-release pieces.  (See for example)

### Reasoning

As part of the event bus work.

**Comment by robrap** [comment]
This seems like a long time on GitHub requests. Do you have an SLA for expected wait times at various urgency levels? Thanks.

**Comment by arbrandes** [comment]
@robrap, apologies!  This is on me: assigned myself but had a bunch of high-priority requests jump the queue, and this one fell off the table.

In any case, here it is: https://github.com/openedx/kafka-event-bus

It's blank.  You should have enough permissions to manage it.  Let me know if you need anything else.

**Comment by robrap** [comment]
Thanks @arbrandes!

**Comment by robrap** [comment]
@arbrandes: Thoughts about whether or not you want to create an improved the GitHub issue template? Maybe add that to its own separate issue (outside of this one)? Otherwise, I assume this can be closed?

**Comment by arbrandes** [comment]
@robrap, good question.  We can close this, but I'll bring up the whole new repo docs thing with the team.  (I'm of the opinion we should put up repo guidelines in a public document/wiki page, and link to it from a new issue template.)
