### ISSUE TITLE
[GH Request] Delete hubspot cookies from openedx.org

### ISSUE THREAD

**Issue by sarina** [openedx/tcril-engineering#293]
### Firm Name

tCRIL

### Urgency

Medium

### Problem/Request

Remove these cookies from all *.openedx.org sites: "hubspotutk" and "__hs_opt_out"

See [cookie inventory](https://docs.google.com/spreadsheets/d/1XTZEhkF1qAnYyEcTVMXSqAXwp6B1fG-RdkP3oribyyU/edit#gid=949426959) (private) - the Cookie Jar tab lists which cookies are present on which properties.

### Reasoning

We have HubSpot cookies on our properties but do not use hubspot anywhere. To clean up our cookie disclosure, let's remove them.

@nedbat - would love a final check that HubSpot cookies are not needed, but don't believe they are.

**Comment by sarina** [comment]
@nedbat for your reference, hubspot cookies are used on most properties:

openedx.org
con.openedx.org
logos.openedx.org
marketing.openedx.org
metrics.openedx.org
staging3.openedx.org
www.staging3.openedx.org
www.openedx.org

**Comment by arbrandes** [comment]
Confirmed that the cookies are now gone.
