### ISSUE TITLE
Include 3 new contractors under Arbisoft CLA

### ISSUE THREAD

**Issue by jmbowman** [openedx/tcril-engineering#295]
3 new Arbisoft contractors started working for me on May 23rd, but their PRs are still being flagged as `open-source-contribution` (for example, https://github.com/openedx/edx-proctoring/pull/1055 ).  My understanding is that the organization membership lists get pulled from Salesforce, and updates there may be triggered by onboarding emails sent by Wes.  But for some reason those onboarding emails weren't sent for these three contractors, and we're still trying to figure out why (Wes is on an extended vacation until tomorrow, which may be part of it).  They're already in the openedx org with push-pull-all team membership thanks to https://github.com/openedx/tcril-engineering/issues/273 and https://github.com/openedx/tcril-engineering/issues/274 ; could you also update the list in Salesforce appropriately, or do I need to continue debugging where the process broke down within 2U to get this fixed?

The contractors in question:
* Muhammad Abdullah Waheed Khan, @abdullahwaheed
* Bilal Qamar, @BilalQamar95
* Maman Khan, @mamankhan99

**Comment by e0d** [comment]
In order to get new folks added in Salesforce, IT sends us an email.  I don't see any emails about these folks.  We would also need their email addresses to add them.

**Comment by jmbowman** [comment]
We think we figured out where the process broke down to send those emails, and manually triggered them about 40 minutes ago.  Please let me know if they still haven't arrived.

**Comment by e0d** [comment]
I received them and have added them to Salesforce.  I really think we need to advance the automation of on-boarding/off-boarding from the 2U side.  Some improvements I can see:

- Getting the data in a structured format so it can be automatically added to Salesforce
- Not getting data about people that aren't actually covered by the CLA.

Perhaps the easiest path there is:   
- 2U manage a repo that is share with tCRIL with a CSV of covered committers.  
- A GitHub action on merging of pull requests hands additions and deletes from the authoritative file.  
- Only 2U staff who have the rights to specify whom is and is not covered under your CLA have access to merge pull requests.

**Comment by jmbowman** [comment]
Thanks for the suggestions; the current process isn't great on our end either, especially after some of the post-acquisition IT migrations.  I'm in the middle of working with a few people to document what we're doing right now and make a few improvements.

**Comment by feanil** [comment]
Looks like this has been resolved, closing.
