### ISSUE TITLE
[GH Request] Onboard <ADD USERNAMES HERE>

### ISSUE THREAD

**Issue by tnamgyal** [openedx/tcril-engineering#296]
### Firm Name

edX/2U

### User List

Muhammad Abdullah Waheed Khan	@abdullahwaheed
Bilal	Qamar	@BilalQamar95
Maman	Khan	@mamankhan99
Tomas	Leonavicius	@toxicom
Sophia	Inman	@sophiainman
Arturas	Zanemuncekovas	@art8888
Andrew	Wardwell	@andrewgwardwell
Muhammad	Zubair	@zubair-ce07

### Start Date

6/8/22

### Urgency

High Urgency - New contractors that IT just got alerted to today. They start on 6/8

**Comment by feanil** [comment]
Invited to push-pull-all
