### ISSUE TITLE
[GH Request] Create frontend-triage team

### ISSUE THREAD

**Issue by jmbowman** [openedx/tcril-engineering#298]
### Firm Name

2U

### Urgency

High urgency - blocking review of 7+ PRs from contractor team

### Requested Change

Please create a `frontend-triage` team in the openedx GitHub org, with the following initial members:

* Adam Stankiewicz - adamstankiewicz
* Adolfo R. Brandes - arbrandes 
* Ben Warzeski - muselesscreator
* David Joy - davidjoy

### Reasoning

In discussion with the Frontend Working Group, we decided to create a team to triage incoming PRs for assorted front end maintenance tasks (especially for PRs from developers new to the code base who are still ramping up to become the owners of repos that currently lack owners).  The discussion can be found at https://openedx.slack.com/archives/C02BMP2RD5Y/p1654261364118039 .  The goal is for the more senior Open edX frontend developers to be able to take a quick look at these and decide whether to review themselves or delegate to someone else appropriate. If even this initial triage ends up being too large of a time burden for the team members, we'll adjust the process accordingly.

The FED-BOM squad at Arbisoft/2U already has 7 such PRs awaiting review and has several more in progress: https://github.com/orgs/edx/projects/10 .

**Comment by feanil** [comment]
Done: https://github.com/orgs/openedx/teams/frontend-triage/members
