### ISSUE TITLE
[GH Request] Asking edx-community-bot to merge pull requests does not work anymore (for me)

### ISSUE THREAD

**Issue by regisb** [openedx/tcril-engineering#299]
### Firm Name

Overhang.IO

### Urgency

Medium: it would be great if we had a way to easily backport fixes to nutmeg in the coming weeks

### Requested Change

In the past, I could merge pull requests made on the "open-release/xxx.master" release branches by adding a comment: `@edx-community-bot merge`. This no longer seems to be the case, as indicated in the following PRs:

https://github.com/openedx/edx-platform/pull/30232#issuecomment-1096833549
https://github.com/openedx/edx-platform/pull/30518#issuecomment-1150309508

The @edx-community-bot seems to have been renamed first to @openedx-community-bot, then (maybe?) to @openedx/edx-community-bot.

### Reasoning

As a core contributor, I would like to be able to merge/backport changes quickly to the release branches.

**Comment by arbrandes** [comment]
@Carlos-Muniz, this is one that will take some digging.  Do you think you have time to take it on?

**Comment by Carlos-Muniz** [comment]
@arbrandes I don't mind taking this on!

**Comment by arbrandes** [comment]
Thanks!

**Comment by Carlos-Muniz** [comment]
@regisb Thank you for your GH Request. 

As I understand it, [the command](https://github.com/openedx/edx-platform/pull/30232#pullrequestreview-939435487) you should be using is actually `@openedx-community-bot merge`.

Though this does not tag @openedx/edx-community-bot nor @edx-community-bot, it should still work as intended. Please re-open this issue and tag me here to let me know in the case that it does not.

**Comment by Carlos-Muniz** [comment]
@jmakowski1123 
We should make a follow up task for evaluating and possibly rearchitecting this GH Workflow/Bot, possibly for later August.

**Comment by regisb** [comment]
I can confirm that it is working, as evidenced by: https://github.com/openedx/edx-platform/pull/30570#issuecomment-1168406245
It's strange that the "@openedx-community-bot" does not link to an actual user, though.

Thanks!
