### ISSUE TITLE
Update react-intl in frontend-platform

### ISSUE THREAD

**Issue by Carlos-Muniz** [openedx/tcril-engineering#3]
We want the ability to inject html into a translated string as shown [here](https://formatjs.io/docs/react-intl/components/#formattedmessage)

**Comment by feanil** [comment]
Should this ticket move to the Frontend Working Group backlog instead?

**Comment by arbrandes** [comment]
> Should this ticket move to the Frontend Working Group backlog instead?

Good idea.  Done.
