### ISSUE TITLE
[GH Request] Enable Issues on Credentials

### ISSUE THREAD

**Issue by hurtstotouchfire** [openedx/tcril-engineering#300]
### Firm Name

2U

### Urgency

moderate -- I'm blocked.

### Requested Change

For some reason I was able to just enable Issues on credentials-themes myself, but I can't do it on https://github.com/openedx/credentials, which is more what I was expecting.

### Reasoning

I'm using github issues to log known bugs for repos my team maintains.

**Comment by arbrandes** [comment]
Issues enabled!
