### ISSUE TITLE
Create a backlog of "good introductory tasks" to onboard a new MFE contractor

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/tcril-engineering#305]
This backlog will include #https://github.com/openedx/frontend-app-library-authoring/issues/71 and others

Noting that there are complexities in this issue as it requires feedback loops and communication with Jeremy/2U engineers to discover points of alignment in similar backlog they may be building.

**Comment by arbrandes** [comment]
This is the Issue Backlog view on the Frontend Dev board:

https://github.com/orgs/openedx/projects/29/views/8
