### ISSUE TITLE
[GH Request] Onboard whuang1202

### ISSUE THREAD

**Issue by jmbowman** [openedx/tcril-engineering#314]
### Firm Name

2U

### User List

* William Huang, @whuang1202

### Start Date

13 June 2022

### Urgency

Medium Urgency - will be needed shortly

### Special Requests

Will is an intern on the Arch-BOM squad, so it probably makes sense to also add him to the arch-bom GitHub team.

**Comment by Carlos-Muniz** [comment]
@whuang1202 has been invited to the openedx org, to the push-pull-all team, and to the arch-bom team.
