### ISSUE TITLE
[GH Request] Fix frontend-triage team permissions

### ISSUE THREAD

**Issue by jmbowman** [openedx/tcril-engineering#316]
### Firm Name

2U

### Urgency

High urgency - interfering with review of multiple PRs

### Requested Change

Grant the `frontend-triage` team explicit read or write access to at least the following repositories:

* edx-platform
* edx-proctoring
* frontend-* (any public repository starting with "frontend-")
* studio-frontend

### Reasoning

https://github.com/openedx/tcril-engineering/issues/303 created the frontend-triage team, but it can't yet be assigned as the reviewer for any PRs because it lacks explicit read permission for any repositories.

According to https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review explicit read access should be sufficient to assign the team as a reviewer, but write access would be needed for a team member to reassign an issue to someone else after triage.  I think all the team members already have write access to these repos via either push-pull-all membership or admin rights, but it might avoid trouble down the road to make it an explicit feature of the team's repository access.

**Comment by Carlos-Muniz** [comment]
The frontend-triage team has been granted explicit read access to 29 repos:
1. edx-platform
2. edx-proctoring
3. frontend-app-account
4. frontend-app-admin-portal
5. frontend-app-authn
6. frontend-app-course-authoring
7. frontend-app-discussions
8. frontend-app-ecommerce
9. frontend-app-enterprise-public-catalog
10. frontend-app-gradebook
11. frontend-app-learner-portal-enterprise
12. frontend-app-learner-portal-programs
13. frontend-app-learning
14. frontend-app-library-authoring
15. frontend-app-payment
16. frontend-app-profile
17. frontend-app-program-console
18. frontend-app-programs-dashboard
19. frontend-app-publisher
20. frontend-app-support-tools
21. frontend-build
22. frontend-component-cookie-policy-banner
23. frontend-component-footer
24. frontend-component-header
25. frontend-enterprise
26. frontend-platform
27. frontend-template-application
28. frontend-wg
29. studio-frontend
