### ISSUE TITLE
[GH Request] Onboard Marcin Pitera (m-pitera)

### ISSUE THREAD

**Issue by schenedx** [openedx/tcril-engineering#318]
### Firm Name

2U

### User List

Marcin Pitera: [m-pitera](https://github.com/m-pitera)

### Start Date

June 13, 2022

### Urgency

Medium - At the end of the week because he is a software development intern

**Comment by Carlos-Muniz** [comment]
Marcin Pitera (m-pitera) has been invited to the openedx org and added to the push-pull-all team.
