### ISSUE TITLE
[GH Request] Access to push changes to `https://github.com/openedx/course-discovery` repository

### ISSUE THREAD

**Issue by zzzarius** [openedx/tcril-engineering#319]
### Firm Name

2U Contractor - Adapt

### Urgency

Medium

### Requested Change

Ability to push changes to https://github.com/openedx/course-discovery repository for the users:
- Darius Zivertas (github id: [zzzarius](https://github.com/zzzarius),)
- Jesse Day (github id: [jesseday](https://github.com/jesseday))
- Nick Pizzo (github id: [nickpizzo](https://github.com/nickpizzo))

### Reasoning

We are working within [Prospectus](https://github.com/edx/prospectus) codebase from day to day basis and sometimes we need to do some changes in [course-discovery](https://github.com/openedx/course-discovery) repository to shape the data we receive.

**Comment by mulby** [comment]
Not sure if my approval is needed here -- but I approve!

**Comment by Carlos-Muniz** [comment]
A new team named `course-discovery-write-2u-adapt` has been created and given write-level access to `openedx/course-discovery`. The 3 users @zzzarius, @jesseday, and @nickpizzo have been invited to the openedx org and to the `course-discovery-write-2u-adapt` team.

**Comment by zzzarius** [comment]
@Carlos-Muniz Thanks!
