### ISSUE TITLE
[GH Request] Rename kafka-event-bus repo to event-bus-kafka

### ISSUE THREAD

**Issue by timmc-edx** [openedx/tcril-engineering#321]
### Firm Name

2U

### Urgency

Within 1-2 weeks would be great so that we can start publishing this package.

### Problem/Request

We originally requested this repo with a "kafka" prefix, but would like that to be the suffix instead.

### Reasoning

There will probably be multiple `openedx-event-bus-XXX` packages (kafka, redis, maybe something else?) and this will make them easier to find.

**Comment by timmc-edx** [comment]
Oh... while you're in there, could you rename the `master` branch to `main`? Our cookiecutter assumes all new repos will be created with default branch `main`, but my lcoal dev environment created the first branch as `master`...

**Comment by Carlos-Muniz** [comment]
Thank you for your request. 
The repo `openedx/kafka-event-bus` has been renamed to `openedx/event-bus-kafka`.
In addition, the default branch's name has been changed from `master` to `main`.

**Comment by timmc-edx** [comment]
Thank you!
