### ISSUE TITLE
[GH Request] Onboard TheEarlyNerd, aheykamp2u, Yar0myr

### ISSUE THREAD

**Issue by mulby** [openedx/tcril-engineering#323]
### Firm Name

2U

### User List

* Kaleb Davenport [TheEarlyNerd]
* Andrew Heykamp [aheykamp2u]
* Yaromyr Plashenko [Yar0myr]

### Start Date

16 June 2022

### Urgency

Medium - done in the next week or so would be great

### Special Requests

push-pull-all would be great if possible -- these folks are all 2U engineering full-time new hires

**Comment by Carlos-Muniz** [comment]
Thank you for your request. @TheEarlyNerd, @aheykamp2u, and @Yar0myr have been invited to the `openedx` org and have been added to the `push-pull-all` team.
