### ISSUE TITLE
[GH Request] Onboard whuang1202 (to former eduNEXT repos)

### ISSUE THREAD

**Issue by rgraber** [openedx/tcril-engineering#324]
### Firm Name

2U

### User List

William Huang
whuang1202

### Start Date

17 June 2022

### Urgency

High urgency (new intern is basically blocked without it)

### Special Requests

It seems that adding Will to openedx did not give him permission to write to openedx/openedx-events, which is the specific permission we need added

**Comment by sarina** [comment]
openedx/openedx-events is actually maintained by eduNEXT, a community member, and is thus not a default for 2U employees. Moving forward this will become more frequent as we adopt community repos and move towards maintainership.

Either you or Will will need to reach out to @mariajgrimaldi or @felipemontoya if Will wants to get write access to the repo. In the meantime, Will could work off a fork and get his PRs reviewed/merged my the maintainers/committers of the repo. Thanks!

I am closing this ticket. I believe both Felipe and Maria can directly add new committers to their repo.

**Comment by felipemontoya** [comment]
Thanks @sarina.

@rgraber please let me know if Will working with a fork is an acceptable solution. I was under the impression that this access granting would follow the core contributors procedures. So 3Cs and nomination and that. However I don't know if the case of 2U has a different flow. I hope that the urgency while this is cleared can be solved with the fork solution.

**Comment by rgraber** [comment]
We can almost certainly deal with a fork solution for now. I'll take it back to the team about the specifics of access granting.
