### ISSUE TITLE
[GH Request] Grant paragon read access to frontend-triage team

### ISSUE THREAD

**Issue by jmbowman** [openedx/tcril-engineering#325]
### Firm Name

2U

### Urgency

Medium Urgency - obstructing review workflow for some PRs

### Requested Change

Please grant the frontend-triage team explicit read access to the paragon repository.

### Reasoning

In https://github.com/openedx/tcril-engineering/issues/316, I missed the paragon repository in the list of repos in which the frontend-triage team is likely to be assigned PRs for review.  There's already one PR pending such review assignment, and there are likely to be more in the near future.

**Comment by Carlos-Muniz** [comment]
Thank you for your request.
The `frontend-triage` team has been granted read access to the `openedx/paragon` repo.
