### ISSUE TITLE
Convert our Jira instance to a readonly archive

### ISSUE THREAD

**Issue by kdmccormick** [openedx/tcril-engineering#329]
## Context

The Jira projects at https://openedx.atlassian.net/projects were once used by edX for general issue tracking. They have since moved to https://2u-internal.atlassian.net and/or GitHub project boards.

For historical reference, we want to keep the Jira issues around as a public, readonly archive. To reduce confusion and spam, we want to shut down write access to these projects.

(This doesn't all apply to the wiki at https://openedx.atlassian.net/wiki. We haven't quite decided the wiki's fate yet.)

## Acceptance Criteria

* Double check with @sarina to make sure that the plan described above is still what we want.
* Ensure 2U isn't actively using any of these projects.
* Ensure the `📣 2U / OCM Atlassian Migration 📣 Internal edX / OCM / 2U content has moved to a new Atlassian instance. If you're here for Open edX information then you're in the right place!` banner is removed.
* Revoke every non-tCRIL person's write access to each Jira project.
  * ("write access" may be the wrong term here, but you probably know what I mean)

**Comment by kdmccormick** [comment]
Update from standup:
* we are ready to do this
* one active problem with it being non-readonly is spam: https://discuss.openedx.org/t/jira-is-full-of-spam-now/7739

**Comment by sarina** [comment]
@feanil didn't you do this already?

**Comment by sarina** [comment]
<img width="449" alt="image" src="https://user-images.githubusercontent.com/1985317/184128092-5ea50144-a5ca-4011-82aa-c4bf48867e72.png">
