### ISSUE TITLE
[GH Request] Add permissions: pomegranited

### ISSUE THREAD

**Issue by sarina** [openedx/tcril-engineering#330]
### Firm Name

OpenCraft

### Urgency

medium

### Requested Change

@pomegranited writes:

We've got consensus to extend my CC merge rights to include the edx-analytics-* repos:

https://discuss.openedx.org/t/coding-cc-rights-expansion-jillian-vogel/7339

As part of this, OpenCraft is willing to take ownership of these repos, as per Andy Schulze's request. That "ownership" is likely to just be maintenance for named releases and ultimately deprecation. Could you please grant sufficient privileges for me to perform these steps?

I'm also happy to manage a Slack room for these repos, if one could be created.

### Reasoning

https://discuss.openedx.org/t/coding-cc-rights-expansion-jillian-vogel/7339

**Comment by sarina** [comment]
@pomegranited whan would you like the slack room to be called?

**Comment by pomegranited** [comment]
@sarina 

> what would you like the slack room to be called?

How about `cc-analytics` ?

I considered `cc-data` to match the `wg-data`, but "data" is a much bigger topic than "analytics", so I think "analytics" is best.

**Comment by Carlos-Muniz** [comment]
Congratulations @pomegranited, your merge rights have been extended via the process described [here](https://openedx.atlassian.net/wiki/spaces/COMM/pages/2810249408/Administering+a+CC+Committer+Onboarding+Runbook). Your one-person team `CCP Commiter: pomegranited` now has write access to the [edx-analytics-pipeline](https://github.com/openedx/edx-analytics-pipeline), [edx-analytics-data-api](https://github.com/openedx/edx-analytics-data-api/), [edx-analytics-configuration](https://github.com/edx/edx-analytics-configuration/) and [edx-analytics-dashboard](https://github.com/openedx/edx-analytics-dashboard) repositories. 

I also confirmed that @sarina created the slack room `cc-analytics` as you requested.

**Comment by pomegranited** [comment]
Awesome, thank you @Carlos-Muniz and @sarina !
