### ISSUE TITLE
[GH Request] whuang1202 labels access

### ISSUE THREAD

**Issue by whuang1202** [openedx/tcril-engineering#337]
### Firm Name

edx

### Urgency

Medium/high urgency - sometime within the next week

### Requested Change

Add permissions for whuang1202 (William Huang) to be able to add labels to the event-bus project board, alternatively give triage access. 

https://github.com/openedx/tcril-engineering/issues/324

### Reasoning

Allows for clearer labeling of tasks in the project board

**Comment by Carlos-Muniz** [comment]
Hello @whuang1202, thank you for your request. Please ask your manager to remake this request on your behalf.
