### ISSUE TITLE
[GH Request] Change Repo Access: course-discovery & publisher

### ISSUE THREAD

**Issue by sarina** [openedx/tcril-engineering#338]
### Firm Name

tCRIL & 2U

### Urgency

high

### Requested Change

Please:

* Remove course-discovery & frontend-app-publisher from `push-pull-all`
* Make two new GitHub teams:
  * course-discovery-maintainers, with write access to one repo: course-discovery
  * frontend-app-publisher-maintainers, with write access to one repo: frontend-app-publisher
* To these groups add the following people:
  * TBD: @nedbat to provide GitHub usernames of the people who have access to this repo (Phoenix team)
* Go to the repos themselves and make sure the only users with write access are the groups that have been defined.

### Reasoning

These two repos are joining the Maintainers program.

**Comment by nedbat** [comment]
Thanks.  The Phoenix team is @DawoudSheraz, @azanbinzahid, @uzairr, @Ali-D-Akbar, @AliAdnanSohail, @ansabgillani.

**Comment by sarina** [comment]
Partially completed. Teams are here:

https://github.com/orgs/openedx/teams/course-discovery-maintainers/members

https://github.com/orgs/openedx/teams/frontend-app-publisher-maintainers/members

For frontend-app-publisher, here are the teams that have access. I think the ones with "read" access can stay as-is. Could you please advise what to do with the teams that have "write" and "admin" access?

<img width="674" alt="image" src="https://user-images.githubusercontent.com/1985317/175699008-26343b2c-24ba-4972-9500-199351fd87db.png">

The same request too for course-discovery:

<img width="700" alt="image" src="https://user-images.githubusercontent.com/1985317/175699064-bc73e292-54ca-457b-b342-58c37fba2e80.png">

**Comment by sarina** [comment]
@e0d I don't think this will be finished tonight, so will need to be picked up for on-call on Monday

**Comment by e0d** [comment]
@nedbat need some additional input on this one as well.

**Comment by e0d** [comment]
@nedbat is this still a priority?

**Comment by nedbat** [comment]
I checked all the teams. I had to remove two ex-edX people who were still members of the frontend-app-publisher-admin team (Dillon Dumensil and Mike Terry).  Once I made that change, all the people with write or admin access are maintainers, bots, managers, or org-level admins, so the teams are fine as they are.  

Thanks, and sorry for the delay.

**Comment by sarina** [comment]
Thanks Ned!
