### ISSUE TITLE
[GH Request] Change repo access

### ISSUE THREAD

**Issue by sarina** [openedx/tcril-engineering#339]
### Firm Name

tCRIL & 2U

### Urgency

high

### Requested Change

Please:

* Remove ecommerce, ecommerce-worker, frontend-app-payment, & frontend-app-ecommerce from `push-pull-all`
* Make four new GitHub teams:
  * ecommerce-maintainers, with write access to one repo: ecommerce
  * ecommerce-worker-maintainers, with write access to one repo: ecommerce-worker
  * frontend-app-payment-maintainers, with write access to one repo: frontend-app-payment
  * frontend-appecommerce-maintainers, with write access to one repo: frontend-app-ecommerce
* To these groups add the following people:
  * TBD: @nedbat to provide GitHub usernames of the people who have access to this repo (purchase team)
* Ensure list of teams/people who can write to repo is correct (on settings > collaborators & teams page)

### Reasoning

these four repos are joining the Maintainers program

**Comment by nedbat** [comment]
Thanks.  These repos should be owned by the Purchase team (not Phoenix), which is: @inventhouse, @dianekaplan, @julianajlk, @pshiu.

**Comment by sarina** [comment]
Please advise how to handle the groups with write or admin access to the repos

FEA-ecommerce
<img width="896" alt="image" src="https://user-images.githubusercontent.com/1985317/175700271-c8f20c9b-5a15-42f6-be0a-96abb12a7666.png">

FEA-payment
<img width="955" alt="image" src="https://user-images.githubusercontent.com/1985317/175700293-d1df4757-555d-4909-ad59-96fd703fbf08.png">

ecomm-worker
<img width="870" alt="image" src="https://user-images.githubusercontent.com/1985317/175700397-4031cdd1-4a99-400a-8876-039b84161a46.png">

ecommerce
<img width="802" alt="image" src="https://user-images.githubusercontent.com/1985317/175700599-2b4ffef6-b9f0-438b-a213-00bec446db97.png">

**Comment by sarina** [comment]
@e0d tagging you because this on-call work will need to fall through to next week.

**Comment by e0d** [comment]
@nedbat is this still a priorty?

**Comment by nedbat** [comment]
I made one adjustment to the teams: for the frontend-app-payment and frontend-app-ecommerce repos, the "ecommerce" team had write access. I've removed that team from those repos.

Now the remaining teams write or admin access to maintainers, managers, bots, or org-level admins.  The teams are good as they are.

**Comment by sarina** [comment]
Great, thanks for doing that checking Ned.
