### ISSUE TITLE
Design to provide the ability to inject page and routes into the platform

### ISSUE THREAD

**Issue by sarina** [openedx/tcril-engineering#34]

**Comment by kdmccormick** [comment]
@e0d Is this a decoupling issue?

**Comment by ormsbee** [comment]
Yeah, I'm also fuzzy on what this is, and what gaps specifically we want to address with this ticket. We have some ability to do this on the Django side already, but I don't know what the MFE story around this is at the moment.

**Comment by e0d** [comment]
Let's close for now as we're not sure sure the intention of this item was.
