### ISSUE TITLE
[GH Request] Onboard zubair-ce07

### ISSUE THREAD

**Issue by colinbrash** [openedx/tcril-engineering#340]
### Firm Name

2U

### User List

Muhammad Zubair, @zubair-ce07

### Start Date

27 June 2022

### Urgency

mid/high urgency - Zubair's work is currently blocked

### Special Requests

Zubair also needs to be added to:
* `ecommerce-maintainers`
* `ecommerce-worker-maintainers`
* `frontend-app-payment-maintainers`
* `frontend-appecommerce-maintainers`

Thank you!

**Comment by e0d** [comment]
@colinbrash this change has been made, please let me know if there are any further issues.

**Comment by dianekaplan** [comment]
Hello, TCRIL!

Thanks for your help getting Zubair set up. We're seeing an issue with his first PR in frontend-app-ecommerce; the 'signed contributor agreement' check fails: 
https://github.com/openedx/frontend-app-ecommerce/pull/193

At first I tried adding him into the people.yaml file in repo-tools-data, but I'm not sure that's used anymore. Could you update Zubair to be internal/approved as far as github is concerned for that signed contributor agreement check?

Let us know if you need any more detail, but you can see the failure in the PR linked above. 

Thanks!
Diane

**Comment by e0d** [comment]
@dianekaplan I can confirm that we have not received a request to add zubair-ce07 to the CLA file.  

Please note that updating `people.yaml` will not help with this issue.
