### ISSUE TITLE
[GH Request] ecommerce access teams changes

### ISSUE THREAD

**Issue by colinbrash** [openedx/tcril-engineering#341]
### Firm Name

2U

### Urgency

High urgency - ASAP

### Requested Change

Please add the following users to the following teams:

Users:

- Long Lin - @long74100
- Alex Dusenbury - @iloveagent57
- Chris Pappas - @christopappas
- Adam Stankiewicz - @adamstankiewicz
- Brian Beggs - @macdiesel
- John Nagro - @johnnagro

Teams:
- ecommerce-maintainers
- ecommerce-worker-maintainers

### Reasoning

These users are all working heavily in these ecommerce repos and need direct write access (which has recently been restricted).

**Comment by e0d** [comment]
@colinbrash this has been done, please let me know if there are any further issues.
