### ISSUE TITLE
Tutor: Ensure settings for core & official plugins are documented

### ISSUE THREAD

**Issue by Carlos-Muniz** [openedx/tcril-engineering#347]
https://github.com/overhangio/2u-tutor-adoption/issues/6

**Comment by kdmccormick** [comment]
Closed as a duplicate of https://github.com/overhangio/2u-tutor-adoption/issues/6

**Comment by kdmccormick** [comment]
@Carlos-Muniz You can add Tutor issues directly to the tCRIL board by pasting just their URL into "Add item" :) 
![image](https://user-images.githubusercontent.com/3628148/180503930-b4014c22-ebc6-47c4-9808-37427eaf6b46.png)
