### ISSUE TITLE
[GH Request] Onboard asifbilal786, moeez96

### ISSUE THREAD

**Issue by colinbrash** [openedx/tcril-engineering#350]
### Firm Name

2U

### User List

* Asif Bilal, @asifbilal786
* Abdul Moeez Zahid, moeez96

### Start Date

07/04/2022

### Urgency

mid/high urgency - both have already started work

**Comment by ormsbee** [comment]
@colinbrash: I've added them to the openedx org and to push-pull-all. If there are other groups they should be added to, please list them here and re-open the ticket. Thank you.
