### ISSUE TITLE
Determine whether we need Atlassian paid plugins

### ISSUE THREAD

**Issue by e0d** [openedx/tcril-engineering#353]
We currently have two paid plugins in our instance that were in use by edX prior to the transfer of the Atlassian domains to us.  We should determine whether we still need them and, if not, remove them.

![Image](https://user-images.githubusercontent.com/1270274/177862122-84d29eeb-48dc-4664-afa2-463e4b48f81b.png)

**Comment by sarina** [comment]
This is done.

<img width="545" alt="image" src="https://user-images.githubusercontent.com/1985317/184128248-2de35fce-f1a1-4a82-95a6-05241682b0e5.png">
