### ISSUE TITLE
[GH Request] Move edx/django-require into the openedx organization

### ISSUE THREAD

**Issue by kdmccormick** [openedx/tcril-engineering#360]
### Firm Name

tCRIL

### Urgency

Low

### Requested Change

* **First,** run this transfer by legal.
* Then, after he's back from PTO on Mon 7/18, ask Ned from 2U to transfer https://github.com/edx/django-require into the openedx org.
* Then add `push-pull-all` write access to the repo, and add @jmbowman as a repo admin.
* (This unblocks https://github.com/openedx/edx-platform/pull/30719)

### Reasoning

https://github.com/edx/django-require was forked into the Open edX organization because the upstream maintainers have been slow with upkeep. Our fork is currently the most active fork of the library on GitHub.

Since the repo is a [hard dependency](https://github.com/openedx/edx-platform/blob/9e08c5e3d2d80d2da34240862aaa7193ea9fcbe4/requirements/edx/github.in#L62) of edx-platform, it should be moved to the openedx organization. We should give @jmbowman admin access to the repo since he and his team have been de facto maintaining it.

Discussed in #ask-tcril: https://openedx.slack.com/archives/C039VR9PDQ8/p1657566331940499

**Comment by kdmccormick** [comment]
(@e0d you can ignore this one, I'm on it)

**Comment by kdmccormick** [comment]
> First, run this transfer by legal.

This issue is blocked on this step until 7/25

**Comment by feanil** [comment]
@kdmccormick what's the status of this move, has it been un-blocked now?

**Comment by kdmccormick** [comment]
@feanil Yep, it's unblocked, I just haven't found time to make progress on it.

**Comment by feanil** [comment]
I've sent an e-mail to legal and am waiting to hear back.  I CC'ed you @kdmccormick.

**Comment by feanil** [comment]
From legal:

> We can fork the repo, keep the BSD notice for the original code plus whatever was added under the BSD, but also add the Apache 2.0 license for whatever code we layer on.
> 
> ... what we're doing is ending up with a multi-license. The stuff that started under BSD will stay under BSD, but the stuff that's added by or on behalf of tCRIL will be licensed under Apache.

@kdmccormick I think this is unblocked now if you want to take it over, or I can get to it later this week.

**Comment by kdmccormick** [comment]
I got it, thanks @feanil !

**Comment by kdmccormick** [comment]
PR: https://github.com/openedx/django-require/pull/1

**Comment by kdmccormick** [comment]
Added github.com/openedx/django-require to push-pull-all and added @jmbowman as a repo admin.
