### ISSUE TITLE
[GH Request] Delete Confluence page

### ISSUE THREAD

**Issue by robrap** [openedx/tcril-engineering#361]
### Firm Name

2U

### Urgency

Medium

### Problem/Request

Please delete https://openedx.atlassian.net/wiki/spaces/AC/pages/3225288755/Confluent.io+Kafka+Hosting+Notes.

### Reasoning

This page was meant for the 2U internal wiki.

**Comment by sarina** [comment]
Done!

**Comment by robrap** [comment]
Thanks @sarina.
