### ISSUE TITLE
[GH Request] Onboard <zubair-ce07>

### ISSUE THREAD

**Issue by mbeljoi** [openedx/tcril-engineering#362]
### Firm Name

2U

### User List

Muhammad Zubair,@zubair-ce07

### Start Date

12 July 2022

### Urgency

medium

### Special Requests

When making a change to one of our team repos (frontend-app-ecommerce), our
new Arbisoft teammate Zubair is failing the CLA check (PR here
<https://github.com/openedx/frontend-app-ecommerce/pull/193> for
reference).

**Comment by mbeljoi** [comment]
Hi, any news on this request?

**Comment by sarina** [comment]
Hi @mbeljoi - there's some technical stuff @caplan188 (I think) is working out between 2U and tCRIL. When that's figured out we will be able to proceed.

**Comment by sarina** [comment]
cc @e0d - we're trying to work through process here and right now are blocked.

**Comment by e0d** [comment]
This was resolved some weeks back, can be closed.
