### ISSUE TITLE
Frontend Working Group Highlights

### ISSUE THREAD

**Issue by mphilbrick211** [openedx/tcril-engineering#368]
Per email on 6/28, please add content [here](https://docs.google.com/document/d/1u_uuPgMmF_M6J0LPE2LvuRdGCFSD4lsztVgb0eRwgQI/edit).

---------------

tCRIL is working on an impact report for Open edX (for the last fiscal year). One of the sections will be focusing on our Community, and as such we want to highlight the great things the Working Groups are up to.

We're hoping that you and your group can help flesh out some of the suggested content listed [in this document](https://docs.google.com/document/d/1u_uuPgMmF_M6J0LPE2LvuRdGCFSD4lsztVgb0eRwgQI/edit). Please use this document to compile your information, and include anything additional you'd want to highlight (e.g. links to things you want to share, etc.).

**Comment by arbrandes** [comment]
@mphilbrick211, had this as #357, but better to rally under yours. :)  Closing that one.
