### ISSUE TITLE
[GH Request] Onboard TheEarlyNerd

### ISSUE THREAD

**Issue by Yar0myr** [openedx/tcril-engineering#383]
### Firm Name

edX(2U)

### User List (case sensitive!)

Kaleb Davenport, TheEarlyNerd

### Start Date

July 26 2022

### Urgency

High, needed for d2d work

**Comment by sarina** [comment]
Blocked on https://github.com/openedx/tcril-engineering/issues/384 (want to understand process there)

**Comment by nedbat** [comment]
#384 is about a gap in the CLA database particularly.  Kaleb is already there, so no CLA changes are needed.

**Comment by e0d** [comment]
This was resolved some time back and can be close.
