### ISSUE TITLE
[GH Request] Onboard <danielkalen>

### ISSUE THREAD

**Issue by Yar0myr** [openedx/tcril-engineering#384]
### Firm Name

edX(2U)

### User List (case sensitive!)

Daniel Kalen, danielkalen

### Start Date

July 26 2022

### Urgency

High, needed for d2d work

**Comment by nedbat** [comment]
Please note, this includes adding Daniel to the CLA database.  He is covered by the 2U entity agreement.

**Comment by e0d** [comment]
@nedbat is this a one off or the start of a new process for CLA updates?  

Also can you provide an email for Daniel?

**Comment by nedbat** [comment]
This is not a new process, we are just trying to backfill some gaps while Matt Caplan tries to straighten out the real pipeline.  Daniel's email is dkalen@2u.com.

**Comment by nedbat** [comment]
This has now been completed.

**Comment by nedbat** [comment]
These people have now been added to the CLA database.
