### ISSUE TITLE
[GH Request] Offboard oliviaruizknott

### ISSUE THREAD

**Issue by hurtstotouchfire** [openedx/tcril-engineering#385]
### Firm Name

2U

### User List

* [oliviaruizknott](https://github.com/oliviaruizknott)

### End Date

15 July 2022

### Urgency

moderate

**Comment by sarina** [comment]
@hurtstotouchfire this is blocked on some process stuff. Also when filing tickets please replace the `ADD USERNAMES HERE` part of the title with the actual username(s)

**Comment by sarina** [comment]
Olivia has been removed from push-pull-all.

@e0d - if Olivia's CLA needs to be adjusted, please do so. Otherwise this ticket can be closed.

**Comment by nedbat** [comment]
Olivia has been removed from the CLA database.
