### ISSUE TITLE
[GH Request] Onboard KristinAoki

### ISSUE THREAD

**Issue by jristau1984** [openedx/tcril-engineering#388]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

Kristin Aoki, GH Username: KristinAoki

### Start Date

25 July 2022

### Urgency

Medium Urgency (resolve in <one week)

**Comment by sarina** [comment]
Added Kristin to GitHub group. 

@e0d if Kristin needs to be added to the CLA database, please do so.

**Comment by nedbat** [comment]
Kristin has now been added to the CLA database.
