### ISSUE TITLE
[GH Request] Onboard zubair-ce07 asifbilal786 MaxFrank13 danielkalen varshamenon4 m-pitera

### ISSUE THREAD

**Issue by jsoto2u** [openedx/tcril-engineering#389]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

danielkalen
zubair-ce07 
asifbilal786
MaxFrank13
varshamenon4
m-pitera

### Start Date

07/21/2022

### Urgency

High Urgency as these users were not onboarded properly before, and are actively submitting PRs into this org

### Special Requests

This request is being submitted due to them being marked as external collaborators in the org currently.  When being onboarded want to make sure they don't get marked as an external contributor despite being a member of the org(this option is present in the edx and edx-ops org that I have access to).

I don't know if this was addressed for any of these users before getting to me at Help Desk so if they have just let me know and I can relay that on our end

**Comment by jsoto2u** [comment]
Want to clarify that when I say "not onboarded properly before", that is from the 2U side since it doesn't seem like a request ever came in from our end.

**Comment by nedbat** [comment]
This has now been completed.

**Comment by nedbat** [comment]
(Sorry about the close)... 

These people have been added to the CLA database.
