### ISSUE TITLE
[GH Request] CLA list verification for whuang1202 bilaltahir21 TheEarlyNerd

### ISSUE THREAD

**Issue by jsoto2u** [openedx/tcril-engineering#390]
### Firm Name

2U

### Urgency

High Urgency

### Requested Change

These 3 users are in the org but from the Help Desk ticket received at 2U are still having issues being marked as external contributors.  Speaking with Natalia Berdnikov who submitted the ticket to us for example, Kaleb Davenport (TheEarlyNerd) apparently shows up as theearlynerd in the CLA list.

I don't know if this was addressed for any of these users before getting to me at Help Desk so if they have just let me know and I can relay that on our end

### Reasoning

So these members PR don't get flagged as External Contributors and have the openedx-webhook inform them their PR won't get reviewed.

**Comment by e0d** [comment]
Kaleb has two records, one with an individual CLA, one with the 2U CLA.  The individual CLA record had the wrong casing, I've disabled that temporarily.  This will be fixed in the next feed later today.

@Carlos-Muniz do you know whether having two entries with different cases would cause the CLA check to behave improperly?

**Comment by feanil** [comment]
I looked at this with @Carlos-Muniz and having two entries should not cause any improper behavior.  The bot will pick up the version that matches the casing the username has on github so the other entry will be ignored.  It looks like everything is working as expected on our side, the PR from [before the proper casing](https://github.com/openedx/configuration/pull/6780) entry was added failed the CLA but [the one after the correct entry was added](https://github.com/openedx/paragon/pull/1479), passed.

**Comment by feanil** [comment]
@jsoto2u looks like all the people are in the list correctly now so it may just be a timing issue.  The CLA list is updated only once every 24hrs so it may just not have been filed on the 2U side early enough to be ready to go by the time the user is ready to submit contributions.
