### ISSUE TITLE
[GH Request] Confluence FEDX space write access for Jeremy Bowman

### ISSUE THREAD

**Issue by jmbowman** [openedx/tcril-engineering#391]
### Firm Name

2U

### Urgency

Medium Urgency - needed to properly locate new doc

### Problem/Request

Please grant me write permission to the Frontend Development (FEDX) space in Confluence.

### Reasoning

I'm starting a doc on proposed usage of GitHub labels to streamline frontend PR reviews.  I can probably work around this specific case by writing the doc elsewhere and asking someone else to move it once it's reviewed, but as manager of the FED-BOM squad I anticipate needing to work on more docs in this space in the near future.

**Comment by sarina** [comment]
@jmbowman - it's helpful if you can link to the space you're talking about - do you mean this space? https://openedx.atlassian.net/wiki/spaces/FEDX/overview

**Comment by sarina** [comment]
oh n/m I see you did provide the shorthand. I got that for you.

**Comment by sarina** [comment]
ugh, so I'd like to invoke @feanil here who's on vacation. We did a bunch of messing with space permissions and I think right now from what I can see the only people who have permissions to edit in this space is the tCRIL engineering team. Confluence permissions are janky and nesting so I don't want to mess this up - I'm not sure if we're intending this to be an archived space or one we want to open up for a bunch of people to edit.

Feanil is back from vacation later this week so once he's back we'll figure out how to straighten this out.

**Comment by feanil** [comment]
@jmbowman since that space was already public, rather than giving you write permissions, I've matched the permissions to the COMM space.  This should give you the access you need but hopefully solving for the general case.  Please confirm that you have what you need or if the level of access you have is not sufficient.

**Comment by feanil** [comment]
Closing this for now, reach out if this didn't resolve the issue.
