### ISSUE TITLE
[GH Request] Branch auto-delete on event-bus-kafka

### ISSUE THREAD

**Issue by timmc-edx** [openedx/tcril-engineering#392]
### Firm Name

2U

### Urgency

low -- indefinite timeline ("nice to have")

### Problem/Request

https://github.com/openedx/event-bus-kafka doesn't have the "delete branch automatically after PR is merged" option enabled, unlike most of the openedx repos. Could this be enabled?

(Ideally it would also be added to a checklist for repo creation, or one day we could have a bot enforce this...)

### Reasoning

Without this option, old branches stick around; if someone really wants their branch, the UI even offers to recreate it.

**Comment by ormsbee** [comment]
Done
