### ISSUE TITLE
[GH Request] Create shared #event-bus Slack channel

### ISSUE THREAD

**Issue by robrap** [openedx/tcril-engineering#394]
### Firm Name

2U

### Urgency

Medium

### Problem/Request

Please create an #event-bus channel in the Open edX Slack and send an invite to rraposa@edx.org to share the channel with the 2U Slack instance.

Thank you.

### Reasoning

@e0d noted that the community wants a way to be able to communicate with the 2U team working on the Event Bus, and we will be experimenting with Slack as a solution.

**Comment by robrap** [comment]
@ormsbee: Reminder ping. Thanks.

**Comment by ormsbee** [comment]
@robrap: Thank you for the reminder. Created it and added you.
