### ISSUE TITLE
OEP-54 details

### ISSUE THREAD

**Issue by mphilbrick211** [openedx/tcril-engineering#396]
Details/highlights from [OEP-54](https://open-edx-proposals.readthedocs.io/en/latest/processes/oep-0054-core-contributors.html) for impact report.

Please put [content here](https://docs.google.com/document/d/1cwP7uKI8wCqQSLiFDcRz4_yiwZ_RbhGwS0Rh4YSl5RU/edit).

**Comment by sarina** [comment]
Hey @mphilbrick211 - I put this out to the team for review. I know Adolfo looked at it, and I asked Nell to take a pass. I'm not sure if you or Ed have taken a look. But as far as I'm concerned, this is done! I'll let you close the ticket when you agree.
