### ISSUE TITLE
Confluence spam clean-up

### ISSUE THREAD

**Issue by robrap** [openedx/tcril-engineering#399]
<img width="380" alt="Screen Shot 2022-08-02 at 9 52 51 AM" src="https://user-images.githubusercontent.com/14576445/182391885-71855b83-1654-4449-b134-8c44d277670e.png">

You'll find the above three pages of spam, from multiple users, in the left-hand nav when viewing https://openedx.atlassian.net/wiki/spaces/AC/overview?homepageId=7766132.  Please block these users and remove all their edits.

**Comment by feanil** [comment]
@robrap on-call is not picking it up these tickets properlyproperly.  Are you making system requests or something else?
![image](https://user-images.githubusercontent.com/781561/182636508-fe217c32-d19d-40f6-8931-a9e7f62970fa.png)

**Comment by feanil** [comment]
This should be all set. I've cleaned the pages this and other spam users created and revoked their access.

**Comment by robrap** [comment]
@feanil: I even know what to do, but since I don't see "[GH Request]" in the title, I presume I clicked on the wrong one by mistake. I wonder if you should rename "tCRIL Engineering Task (tCRIL Internal - not for requests)" to "Internal-only tCRIL Engineering Task" or "Internal-only tCRIL Engineering Task (not for external requests)". Just a thought. Sorry about the confusion. Thanks.
