### ISSUE TITLE
Sessionize ownership

### ISSUE THREAD

**Issue by sarina** [openedx/tcril-engineering#40]
Transfer ownership of Sessionize to tCRIL - figure out how to do this and what person(s) to transfer it to.

**Comment by ormsbee** [comment]
How far in advance of the conference do we usually start accepting talk proposals? Is this something we'll want to control before that happens this year?

**Comment by sarina** [comment]
Eden posted today in the Transifex group that we are now accepting talk proposals as of today; this is live: https://sessionize.com/2022-open-edx-conference

So maybe this is done already? I'm not sure how Sessionize works. @e0d or @nedbat is this transfer work still something that needs to be on our radar?

**Comment by e0d** [comment]
We have own this, marking done.
