### ISSUE TITLE
Enforce CLA Check Everywhere

### ISSUE THREAD

**Issue by feanil** [openedx/tcril-engineering#407]
The CLA checks gets run by the webhooks bot on any repo it has write access to, however, the check is not always required.  This means that it can be ignored even if it is failing.  People can bypass the CLA check and still merge.

* Do we want that or should we update our repos to better enforce the CLA check?

Example PR Where the CLA failed but the change was merged anyway: https://github.com/openedx/configuration/pull/6780

**Comment by feanil** [comment]
@e0d, @Carlos-Muniz and I noticed this while we were investigating other CLA stuff.  This seems wrong but wanted to check in before we prioritized fixing it.

**Comment by nedbat** [comment]
If we do enforce the check, it will do two things which are probably good: 
- Tool us up to make repo settings uniform across an org (or some other grouping of repos)
- Fix onboarding problems that keep entity-covered people out of the CLA database.

**Comment by feanil** [comment]
I created https://github.com/openedx/terraform-github/pull/39 as a first stab at this.

**Comment by feanil** [comment]
We ran the script that was merged in with this PR: https://github.com/openedx/terraform-github/pull/39  We have a ticket for automating it to run regularly in the future.  https://github.com/openedx/terraform-github/issues/40

Closing this ticket as I think we've got leftover work tracked and the main concern here should not happen again for all the existing repos.
