### ISSUE TITLE
[GH Request] Add members to ecommerce-maintainers team

### ISSUE THREAD

**Issue by colinbrash** [openedx/tcril-engineering#409]
### Firm Name

2U

### Urgency

mid/high urgency

### Requested Change

Please add the following members to the ecommerce-maintainers team (https://github.com/orgs/openedx/teams/ecommerce-maintainers):

Moeez Zahid, @moeez96
Jawad Khan, @jawad-khan

Thanks,
Colin

### Reasoning

These team members are regularly working directly in the ecommerce repo and need write access.

**Comment by feanil** [comment]
This should be all set.
