### ISSUE TITLE
[GH Request] Need review and merge on the PR

### ISSUE THREAD

**Issue by Jawayria** [openedx/tcril-engineering#410]
### Firm Name

2U

### Urgency

Medium

### Problem/Request

I need someone from tcril team to review and merge this PR.
https://github.com/openedx/tcril-onboarding/pull/29

### Reasoning

My team doesn't have permissions to approve or merge PRs on tcril-onboarding repository.

**Comment by feanil** [comment]
Left an initial review, waiting for your response and then I can do another round.

**Comment by feanil** [comment]
PR has been reviewed, approved and merged.
