### ISSUE TITLE
[GH Request] Onboard Hamzah Ullah

### ISSUE THREAD

**Issue by brobro10000** [openedx/tcril-engineering#412]
### Firm Name

tCRIL

### User List (case sensitive!) - Please also include in ticket title

Full Name: Hamzah Ullah
Github Username: brobro10000

Manager: Brian Beggs   

### Start Date

Thursday August 11

### Urgency

Medium urgency - nonblocking but essential

### Special Requests

Since Brian is OOO till Friday, sending request myself as a new hire. Please reach out for any questions. Thanks.

**Comment by macdiesel** [comment]
I approve of this addition.

**Comment by natabene** [comment]
@feanil His PRs are still flagged as OSPRs, and I don't see him in the list.

**Comment by feanil** [comment]
@natabene this is only for handling the github access, CLA requests have a different process that the 2U IT team is meant to take care of.  If the user is not in the CLA list, it's usually beacuse 2U IT has not filed the relevant requests to add them to the salesforce.

**Comment by jsoto2u** [comment]
@georgebabey Per what was discussed in the Slack thread for the CLA process going forward, Hamzah Ullah's email is hullah@2u.com to upload it into Salesforce.

**Comment by natabene** [comment]
@brobro10000 Please reopen.

**Comment by brobro10000** [comment]
@natabene It will not allow me to reopen the ticket. I believe only @feanil  can reopen it at the moment

**Comment by arbrandes** [comment]
@e0d, can you add them to the CLA database, please?
