### ISSUE TITLE
[GH Request] Kristin Aoki needs access to OPEN space of Openedx confluence

### ISSUE THREAD

**Issue by jristau1984** [openedx/tcril-engineering#414]
### Firm Name

2U

### Urgency

Medium Urgency (resolve in <one week)

### Requested Change

Kristin Aoki needs access to OPEN space of Openedx confluence

### Reasoning

She is trying to access the OSPR review guidelines page, linked form our engineering pathways sheet.  She is getting a permissions error.

**Comment by feanil** [comment]
I'll take a look at this, I would expect that space to be open to anyone in the community, if there are specific pages that she can't edit, links to them would be appreciated since Confluence permissions can vary down to the page.

**Comment by jristau1984** [comment]
She is trying to access the OSPR review guidelines page, linked form our engineering pathways sheet.
https://openedx.atlassian.net/wiki/spaces/OPEN/pages/1916338440/OSPR+Review+Guidelines

**Comment by feanil** [comment]
Making this page more publicly visible was more complicated than expected(tm) so I don't think there is much I can do on that front but any user who has an account should still be able to see it.

**Comment by jristau1984** [comment]
Thanks for looking into it, @feanil !
