### ISSUE TITLE
[GH Request] Onboard cablaa77 (Brad Brown) to openedx org

### ISSUE THREAD

**Issue by jristau1984** [openedx/tcril-engineering#416]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

* cablaa77

### Start Date

1 August 2022

### Urgency

Medium Urgency (resolve in <one week)

**Comment by feanil** [comment]
Invitation sent.

**Comment by arbrandes** [comment]
Reopening.  @e0d, another one for the CLA.
