### ISSUE TITLE
Update all old edx.org GitHub links to Open edX GitHub links in our codebase

### ISSUE THREAD

**Issue by sarina** [openedx/tcril-engineering#42]
- Once all the repos are moved, we need to update the old GH links to the new ones
- We need to make sure none of this breaks edx.org

@feanil @nedbat is there a timeline for this?

**Comment by jmakowski1123** [comment]
Target Q2

**Comment by sarina** [comment]
This seems pretty straightforward with the right script. want to confirm that no one's done this yet.

**Comment by sarina** [comment]
I wrote a script to do this and will be running it as it seems to be working. Everyone will get tagged. Sorry not sorry

<img src="https://media4.giphy.com/media/rd4PovI7PgYw0/giphy.gif"/>

**Comment by sarina** [comment]
note: messed a thing up, once all these are merged will need do one final pass for the `uses: edx/.github` string but on a new branch name.

**Comment by sarina** [comment]
87% of PRs are merged. Remaining 26 will be dealt with as part of the follow-up task #386
