### ISSUE TITLE
Create CloudFlare account for tCRIL

### ISSUE THREAD

**Issue by ormsbee** [openedx/tcril-engineering#431]
In order to meet OFAC requirements, we want to use CloudFlare's WAF rules and block by `ip.geoip.country` and `ip.geoip.subdivision_1_iso_code` (for regions of Ukraine). Doing this would require having the "Business" plan for CloudFlare ($200/month).

The relevant excerpt from the [fields reference](https://developers.cloudflare.com/ruleset-engine/rules-language/fields/):

> Access to `ip.geoip.is_in_european_union`, `ip.geoip.subdivision_1_iso_code`, and `ip.geoip.subdivision_2_iso_code` fields requires a Cloudflare Business or Enterprise plan.

**Comment by feanil** [comment]
@e0d I think you've done this at this point right?

**Comment by e0d** [comment]
Yes, that's correct.  @ormsbee can you confirm:

- You have a required access to Cloudflare
- That the domains are correctly resolving, they seem right or thereabouts to me
  - https://training.openedx.org/
  - https://sandbox.openedx.org/

If all looks good, we can close.

**Comment by e0d** [comment]
@ormsbee is this good to close?

**Comment by ormsbee** [comment]
Yup, thank you!
