### ISSUE TITLE
Upgrade react-intl in frontend-platform

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/tcril-engineering#433]
### Problem

The fact a very outdated version of react-intl is being used across the board makes it hard to implement i18n practically for consumers of frontend-platform and Paragon components.

### Product/Platform Value

This makes internationalization easier for both devleopers and translators, ultimately favoring adoption.

### Related or in-progress work

This has already been solved by Adam Stankiewicz at 2U as tracked via [frontend-wg#38](https://github.com/openedx/frontend-wg/issues/38).

### Contingencies

**Comment by sarina** [comment]
@jmakowski1123 @arbrandes I assme this can be closed if Adam has already solved it
