### ISSUE TITLE
Update Openedx Stats Site to Pull from Openedx Bucket

### ISSUE THREAD

**Issue by sarina** [openedx/tcril-engineering#44]
Context:
https://openedxstats.herokuapp.com/ is a site that shows us what Open edX sites might exist out in the world.  It does this by looking at the logs for a specific image(Powered by Open edX) that should be on most deployments.  This image used to be served out of a bucket/cloudfront distribution in the edx-prod aws account.  The logs from that coludfront distribution would be processed by the openedxstats app to be able to show us a list of potential openedx sites.

As a part of https://github.com/openedx/decoupling/issues/3 we updated the link so that it pulls the image out of a bucket in the aws-opensource account that TCRIL manages. But there are a few more changes we need to make to fully finish this work.

The current state is as follows:
* In edx-platform the link is for https://files.edx.org/openedx-logos/...
* That is managed by edx@2U via Cloudflare.
  * Anything under that particular path is redirected to a cloudfront distribution.
* The cloudfront distro lives in the aws-opensource AWS acccount that TCRIL manages.
* The cloudfront distro logs all requests including the referer for the request in an S3 Bucket(s3://openedx-logs)

Things Left to Do:
* Update the heroku app to pull the s3 data from the new log bucket.
  * Probably a new user will need to be created with the relevant s3 permissions and keys will need to be generated for that user.
* Update edx-platform to not point to files.edx.org for the image in future versions.
  * Consider making a CNAME for the cloudfront distro so that we can hide the implementation detail of cloudfront.

AC:
* The openedx-stats app can pull data from the new bucket and shows useful information
* edx-platform is not pointing to a files.edx.org URL for these logos.

Note: We'll want to leave the files.edx.org redirect working as is to not break older versions of the Open edX platform.

**Comment by feanil** [comment]
Created https://github.com/openedx/terraform-internal/pull/7 to get a distro with correct DNS and TLS without breaking the current distro.  Once that's up and we've verified that it works, we'll want to update [cloudflare rule at edx](https://github.com/edx/terraform/compare/feanil/update_logos_backend?expand=1)  and [update the edx-platform codebase](https://github.com/openedx/edx-platform/search?q=files.edx.org)

**Comment by feanil** [comment]
New distro created, [cloudflare update](https://github.com/edx/terraform/pull/4281) completed and [edx-platform updated](https://github.com/openedx/edx-platform/pull/29826).

Now just waiting on traffic to the old distro to die down before cleaning it up.

**Comment by feanil** [comment]
Old distro has been cleaned.   All the work for this is done.
