### ISSUE TITLE
[GH Request] Onboard mzakaria1

### ISSUE THREAD

**Issue by jsoto2u** [openedx/tcril-engineering#440]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

Full Name: M. Zakaria Nazir
Github Username: [mzakaria1](https://github.com/mzakaria1)

### Start Date

8/17/2022

### Urgency

Medium urgency - non blocking but essential due to 2U not properly onboarding on hire

**Comment by feanil** [comment]
@jsoto2u you are not currently in the Open edX organization and I'm not sure what team you're representing. Can you please identify yourself and provide more context on this request?

**Comment by jsoto2u** [comment]
I work at the 2U Help Desk, for Onboarding users to this org we were given the link below for this process since it's not one we directly manage.

https://github.com/openedx/tcril-engineering/issues/new/choose

M. Zakaria Nazir is a contractor who started with us on 7/13/2022.  As part of his new hire onboarding a request should have came in around that time to onboard him to this Github organization from our provisioning team but browsing at other tickets I did not see a request came in for them.  Someone else on the edX side reached out to me over Slack today since apparently Zakaria has been submitting PRs here already but due to this has had difficulties in it getting them merged.

Let me know if you need me to provide more information/context.

**Comment by arbrandes** [comment]
Awaiting confirmation from George Babey [on Slack](https://openedx.slack.com/archives/C039VR9PDQ8/p1661265954575469).

**Comment by arbrandes** [comment]
Confirmed with George.  Invitation sent!

**Comment by arbrandes** [comment]
@e0d, can you please include this user in the CLA?
