### ISSUE TITLE
[GH Request] Add to maintainers teams

### ISSUE THREAD

**Issue by colinbrash** [openedx/tcril-engineering#442]
### Firm Name

2U

### Urgency

Mid/high urgency

### Requested Change

Please add

* Westley Russell, @wdrussell2015

to the following openedx teams:

* @openedx/ecommerce-maintainers 
* @openedx/frontend-app-ecommerce-maintainers 
* @openedx/frontend-app-payment-maintainers 
* @openedx/ecommerce-worker-maintainers 

### Reasoning

Westley is a new hire on the 2U Purchase Squad

**Comment by arbrandes** [comment]
@colinbrash, this is done!

**Comment by arbrandes** [comment]
@e0d, can you please include this user in the CLA?
