### ISSUE TITLE
Change Authn Admin to Zainab on Github

### ISSUE THREAD

**Issue by waheedahmed** [openedx/tcril-engineering#444]
### Firm Name

2U

### Urgency

Deadline September 9th

### Requested Change

Add [Zainab](https://github.com/zainab-amir) into [frontend-app-authn-admin](https://github.com/orgs/openedx/teams/frontend-app-authn-admin) as admin and on all other places and invites.

### Reasoning

September 9th is my last day with 2U/edX, she will be replacing me for the lead position for the Vanguards.

**Comment by arbrandes** [comment]
Added to frontend-app-authn-admin team.  Is there anything else I should add them to?

**Comment by waheedahmed** [comment]
Thank you @arbrandes! No, I guess we are good to close.
