### ISSUE TITLE
[GH Request] Onboard zxcs001 

### ISSUE THREAD

**Issue by maliyath** [openedx/tcril-engineering#445]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

Yuchen Tu, @zxcs001 

### Start Date

8/25/2022

### Urgency

Medium urgency - user needs Github access 

### Special Requests

User is Yuchen Tu, github username is zxcs001

**Comment by arbrandes** [comment]
User invited.

**Comment by arbrandes** [comment]
@e0d, please include in the CLA.
