### ISSUE TITLE
[GH Request] Onboard ashley3

### ISSUE THREAD

**Issue by maliyath** [openedx/tcril-engineering#446]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

Ashley Smith, @ashley3

### Start Date

8/22/2022

### Urgency

High urgency

### Special Requests

Users name is Ashley Smith, email is asmith6@2u.com, github username is ashley3

**Comment by arbrandes** [comment]
User invited.

**Comment by arbrandes** [comment]
@e0d, please include in the CLA.
