### ISSUE TITLE
[GH Request] Offboard Jack Popiel

### ISSUE THREAD

**Issue by maliyath** [openedx/tcril-engineering#447]
### Firm Name

2U

### User List  (case sensitive!) - Please also include in ticket title

Jack Popiel

### End Date

8/27/2022

### Urgency

Low urgency

### Retained Permissions & Special Requests

Please remove termed user Jack Popiel from the Github openedx org

**Comment by maliyath** [comment]
Users github username is The-Pope-2U

**Comment by arbrandes** [comment]
I can't find the user in the openedx org.  Either somebody already removed them, or they were never in the organization.  In any case, I'm closing the issue.
