### ISSUE TITLE
[GH Request] Offboard noisecapella

### ISSUE THREAD

**Issue by ashley3** [openedx/tcril-engineering#448]
### Firm Name

2U

### User List  (case sensitive!) - Please also include in ticket title

noisecapella

### End Date

8/5/2022

### Urgency

Low urgency

### Retained Permissions & Special Requests

Please remove noisecapella from the Github openedx org

**Comment by arbrandes** [comment]
They've been removed from the openedx org.  I'll close the issue once I know what the Salesforce offboarding process entails.

**Comment by e0d** [comment]
@arbrandes they've been removed from SF.
