### ISSUE TITLE
[GH Request] Remove access to "maintainers" teams

### ISSUE THREAD

**Issue by colinbrash** [openedx/tcril-engineering#449]
### Firm Name

2U

### Urgency

High urgency - users should no longer have access

### Requested Change

Please remove the following users:
* [Diane Kaplan](https://github.com/dianekaplan) @dianekaplan
* [Ben Holt](https://github.com/inventhouse) @inventhouse
* [Chris Pappas](https://github.com/christopappas) @christopappas

from the following teams:
* [ecommerce-maintainers](https://github.com/orgs/openedx/teams/ecommerce-maintainers)
* [ecommerce-worker-maintainers](https://github.com/orgs/openedx/teams/ecommerce-worker-maintainers)
* [frontend-app-ecommerce-maintainers](https://github.com/orgs/openedx/teams/frontend-app-ecommerce-maintainers)
* [frontend-app-payment-maintainers](https://github.com/orgs/openedx/teams/frontend-app-payment-maintainers)

Thank you!

### Reasoning

* Ben Holt and Diane Kaplan no longer work at 2U.
* Chris Pappas has moved to another team and no longer requires direct access to the associated repos.

**Comment by arbrandes** [comment]
They've all been from the openedx org.

@e0d, what's the offboarding process for the Salesforce database?
