### ISSUE TITLE
Migrate PR checks that are active on edX to the Open edX Org

### ISSUE THREAD

**Issue by sarina** [openedx/tcril-engineering#45]
- [ ] OSPR bot checks for the CLA, we don't think the bot requires code changes. https://github.com/openedx/decoupling/issues/84
  - Need to updated to use a CSV that's downloaded from salesforce.
 
- What about the other jobs of the OSPR bot
  - Will we create tickets in Jira via the bot?
  - Will 2U maintainers follow the same process as community members or do something different.
  - [Dec 10, 2021] Leave it alone for now, this will probably be re-visited later and doesn't need to be solved as a part of the repo migration.

- [x] ADR bot https://github.com/openedx/decoupling/issues/99
  - We run on Heroku, but was written by OpenCraft

- Remaining things that Jenkins does
  - [x] e2e -- Awais Khan and Awais Queresi will create a plan for how we can these out of Jenkins.
  - [ ] https://github.com/openedx/codejail/issues/121
    - Code Jail PR tests haven't been move to Github actions -- intention was to exercise AppArmour, but we're not sure that's happening
  - [x] Python on edX platform tests is very close switching over to edx-platform.

@feanil adds:
> Marking the e2e test issue as closed not because it's done but because it's not a blocker for decoupling. Those testes are run by edX and edX will retain the build jenkins server so they there is no rush in getting those tests moved off of jenkins from a decoupling perspective.

cc @Carlos-Muniz @nedbat as you're working on the first bullet point.

**Comment by kdmccormick** [comment]
Closed in favor of open child tickets:
* https://github.com/openedx/decoupling/issues/84
* https://github.com/openedx/codejail/issues/121
