### ISSUE TITLE
Update our Heroku apps to ensure they continue to work

### ISSUE THREAD

**Issue by e0d** [openedx/tcril-engineering#450]
Heroku is change their terms of service and this will affect applications that w run.

https://blog.heroku.com/next-chapter

I have requested that we are included in their open-source program, but it will be some time before we hear back.

From the support ticket:

> Thank you for your response and your feedback. We have confirmed the email ospo-heroku-credits@salesforce.com appears to be functioning as expected but let me know if you receive another bounce back. We are currently working on fixing the redirect link in the article.
> 
> Regarding the two month credit, I reviewed your current resources and you have one free heroku-postgresql:dev on your app openedx-webhooks and one free heroku-postgresql:dev on your app openedx-webhooks-staging.
> 
> An upgrade will need to be made on those free tier resource to avoid being deleted starting November 28, 2022. However, since you are a non-profit company, we will be crediting that upgrade beginning November 28, 2022 for 2 months.
> 
> After those two months of credits, the price increase with be $9/month for postgres for each app.
> 
> I hope this helps and please let me know if you have any other questions.

**Comment by e0d** [comment]
Latest correspondance.

> Dear Customer,
> 
> We are grateful for your partnership with Salesforce to date. Given the upcoming changes to Heroku free tier Dynos, Postgres, and Redis, we realize this will impact you as a non-profit customer. In this case, we will apply a credit for the next two months to your account as you are a non-profit customer. The credits are only applied for free tier resources (Dynos, Postgres, and Redis) at the tier above free. One example of this would be if you only had a single free dyno, in which case a credit of $7 would be applied to upgrade to a hobby dyno.
> 
> The changes and credits will take effect on November 28th, 2022. If you have any questions, please reach out to us at https://help.heroku.com/ and our billing team will be able to assist.

**Comment by e0d** [comment]
Here are our current apps:

[openedx-backstage](https://dashboard.heroku.com/apps/openedx-backstage)
[openedx-pr-watcher-notifier](https://dashboard.heroku.com/apps/openedx-pr-watcher-notifier)
[openedx-slack-invite](https://dashboard.heroku.com/apps/openedx-slack-invite)
 [ openedx-webhooks 2 apps](https://dashboard.heroku.com/pipelines/aa81fee7-dfdc-4ad2-ad8e-ef8ee0e389a0)
[openedxstats](https://dashboard.heroku.com/apps/openedxstats)
[tcril-engineering-api](https://dashboard.heroku.com/apps/tcril-engineering-api)
[tcril-interview-react-api](https://dashboard.heroku.com/apps/tcril-interview-react-api)

Most seem to be already updated to 7/month dynos.  The webhooks projects is a special case.

https://help.heroku.com/RHLWN53U/why-am-i-being-asked-to-authorize-additional-charges

**Comment by feanil** [comment]
Looks like the additional services were upgrade so this should be all set for the changes coming at the end of the month.
