### ISSUE TITLE
[GH Request] Onboard bmtcril & brian-smith-tcril

### ISSUE THREAD

**Issue by sarina** [openedx/tcril-engineering#452]
### Firm Name

tCRIL

### User List (case sensitive!) - Please also include in ticket title

* Brian Smith, @brian-smith-tcril
* Brian Mesick, @bmtcril

### Start Date

6 Sep 2022

### Urgency

Medium

### Special Requests

Brian & Brian should be added to a default tcril team that has base repos that we manage/maintain. That should be created if not already. The ones I can think of are

* tcril-engineering
* tcril-onboarding
* tcril-interview
* tcril-interview-react-api
* tcril-engineering-api
* public-engineering

**Comment by kdmccormick** [comment]
* I invited both of them to the org and added them to https://github.com/orgs/openedx/teams/tcril-engineering
* Some of the mentioned repos were missing from the team so I added them in.
* I gave everyone on the team Admin permission on the `tcril-*` repos. For the rest of the repos, the team grants Write permission.
