### ISSUE TITLE
[GH Request] Notify slack channel for OEPs

### ISSUE THREAD

**Issue by hurtstotouchfire** [openedx/tcril-engineering#453]
### Firm Name

2u

### Urgency

low

### Problem/Request

Can some automation be added to the #open_edx_proposals slack channel to post when a new OEP goes live?

### Reasoning

We've just created a 2U internal process for ensuring that all OEPs get socialized, and it would be helpful to have a touchpoint in that channel as a reminder and conversation focus. We debated what would be the best trigger for an automated post. It could be PRs being opened but they often are very rough at first and it's possible that a Discourse post would be the better signal. I think whichever is possible to automate is fine and would be helpful.

**Comment by sarina** [comment]
I think this might be a no-op? @feanil wrote in chat that the `#adr-notifications` channel (and the corresponding 2U channel that I can't see but mentioned in https://openedx.slack.com/archives/C1L370YTZ/p1662561365972059?thread_ts=1662492203.990519&cid=C1L370YTZ) is a stream of ADR and OEP notifications, which is probably pretty noisy.

Based on that discussion, @hurtstotouchfire do you still have this request? If so, has it changed shape at all?

(The request to notify in Slack when someone makes a forums post announcing an OEP seems... pretty challenging, and not something I could tackle right now.)

**Comment by sarina** [comment]
Hi,

Based on no response I'm going to close this issue. Please reopen if there's any new info.
