### ISSUE TITLE
[GH Request] Onboard <bobthebeef> Bob LeBoeuf - bleboeuf@2u.com

### ISSUE THREAD

**Issue by iobrien2u** [openedx/tcril-engineering#455]
### Firm Name

2U Helpdesk

### User List (case sensitive!) - Please also include in ticket title

Bob LeBoeuf, bleboeuf@2u.com, is requesting Github edX-ops access so that
his team can continue provsioning him in that space. Username: @bobthebeef

### Start Date

07 September 2022

### Urgency

Urgent - Provisioning request from 8/22 New Hire. Bob's team needs him to have access so they can finalize his provisioning.

**Comment by kdmccormick** [comment]
The edx-ops organization is managed by 2U.
