### ISSUE TITLE
[GH Request] Onboard ayeshoali

### ISSUE THREAD

**Issue by maliyath** [openedx/tcril-engineering#456]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

Ayesha Waris, @ayeshoali

### Start Date

9/14/2022

### Urgency

Medium urgency

**Comment by e0d** [comment]
@maliyath can you please provide their work email.

**Comment by kdmccormick** [comment]
@georgebabey can you confirm that @maliyath is a 2U IT employee?

**Comment by maliyath** [comment]
Hi,

Sure, their work email is ***@***.***

Best,

Maliyat

*Maliyat* *Hashin* | She/Her
IT Help Desk Associate
FL
Office: (301) 892-4350
***@***.*** <https://bit.ly/31YJPg1> | @edxonline
<https://bit.ly/3cnlmDa> | @Lifeat2U <https://bit.ly/3cda0BJ> | #NoBackRow
<https://bit.ly/3iBmIO3>*
Unlock your potential at edX.org <https://edx.org/> and 2u.com/careers/.
This message contains confidential information and is intended only for the
individual named. If you are not the named addressee you should not
disseminate, distribute or copy this e-mail. Please notify the sender
immediately by e-mail if you have received this e-mail by mistake and
delete this e-mail from your system.

**Comment by e0d** [comment]
@maliyath It looks like the email response to this ticket won't come through properly, can you add the email address to the ticket directly in GitHub?

**Comment by maliyath** [comment]
@e0d Of course! Their work email is awaris@2u.com

**Comment by georgebabey** [comment]
@kdmccormick Confirmed - thank you!

**Comment by kdmccormick** [comment]
Welcome @ayeshoali! You should see an email that invites you to the openedx org and adds you to the push-pull-all team.

**Comment by ayeshoali** [comment]
@kdmccormick Thank you, I have joined push-pull-all team.

**Comment by ayeshoali** [comment]
@maliyath Hi, I have not received my credentials for work email.
