### ISSUE TITLE
Archive RateXBlock and move it to openedx-unsupported

### ISSUE THREAD

**Issue by e0d** [openedx/tcril-engineering#458]
[This repository ](https://github.com/openedx/RateXBlock) has been deprecated and is ready for removal to openedx-unsupported.

**Comment by e0d** [comment]
@feanil any reason to wait to do this?  I believe references will be maintained as redirects.

**Comment by feanil** [comment]
No, I think this is safe to do.  I took a look and it's never been published to PyPI so we don't need to do a final release or anything before we move this to unsupported.

**Comment by e0d** [comment]
There's a [PR](https://github.com/openedx/edx-platform/pull/31158) to remove from edx-platform, but it's blocked as there are courses with this XBlock in them.
