### ISSUE TITLE
[GH Request] Offboard Jawayria

### ISSUE THREAD

**Issue by jmbowman** [openedx/tcril-engineering#459]
### Firm Name

2U

### User List  (case sensitive!) - Please also include in ticket title

* Jawayria Hashmi, @Jawayria

### End Date

19 August, 2022

### Urgency

Medium urgency - response in the next week would be ideal

**Comment by e0d** [comment]
I have remove them from the CLA file.

**Comment by kdmccormick** [comment]
I removed them from the org. Wishing you all the best in your future work @jawayria.
