### ISSUE TITLE
[GH Request] Onboard ishahroz & Mashal-m

### ISSUE THREAD

**Issue by jmbowman** [openedx/tcril-engineering#462]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

* Shahroz Amad, @ishahroz
* Mashal Malik, @Mashal-m

### Start Date

14 September 2022

### Urgency

Medium urgency - response in the next week would be ideal

### Special Requests

They should also be added to the @openedx/fed-bom team.  These are new Arbisoft contractors on that team.

**Comment by kdmccormick** [comment]
Welcome @ishahroz and @mashal-m! You should each see an email that invites you to the openedx org and adds you your teams.

**Comment by e0d** [comment]
Per the email confirmation I have added them and they should be included in the next batch.
