### ISSUE TITLE
[GH Request] Move frontend-lib-special-exams into openedx org

### ISSUE THREAD

**Issue by kdmccormick** [openedx/tcril-engineering#463]
### Firm Name

2U & tCRIL

### Urgency

No urgency

### Problem/Request

Move frontend-lib-special-exams from the edx org into the openedx org

### Reasoning

https://github.com/edx/frontend-lib-special-exams is in the edx org.

https://github.com/openedx/frontend-app-learning, in the openedx org, has a non-optional dependency on it.

So, frontend-lib-special-exams should move into the openedx org.

This seems to have been an oversight from the repository move (was created in April 2021).

**Comment by kdmccormick** [comment]
was flagged by @jmbowman in Slack: https://openedx.slack.com/archives/C039VR9PDQ8/p1663271357689889

**Comment by kdmccormick** [comment]
No objections to this from the team. We will need to ask Nell to amend the deal documents in order to allow for this transfer.

**Comment by e0d** [comment]
@kdmccormick I'm going to assign this to you.

**Comment by kdmccormick** [comment]
Update: I just reached out to our legal counsel about this.
