### ISSUE TITLE
[GH Request] Onboard zubairshakoorarbisoft

### ISSUE THREAD

**Issue by jmbowman** [openedx/tcril-engineering#465]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

* Zubair Shkoor, zubairshakoorarbisoft

### Start Date

10 September 2022

### Urgency

Medium urgency - response in the next week would be ideal

### Special Requests

Zubair should also be added to the @openedx/arbi-bom team.

**Comment by Carlos-Muniz** [comment]
Welcome @zubairshakoorarbisoft! You should see an email that invites you to the `openedx` org and adds you to the `openedx/push-pull-all` and `openedx/arbi-bom` teams.

**Comment by Carlos-Muniz** [comment]
@e0d Can you add zubairshakoorarbisoft to the CLA?

**Comment by e0d** [comment]
I've updated their record, will be in the batch this afternoon.
