### ISSUE TITLE
[GH Request] Implement DEPR template change

### ISSUE THREAD

**Issue by robrap** [openedx/tcril-engineering#466]
### Firm Name

2U

### Urgency

Low

### Problem/Request

We'd like to make improvements to the DEPR Github issue template based on the following comment from "Update OEP-21: Deprecation and Removal with more date guidance". See comment: https://github.com/openedx/open-edx-proposals/issues/333#issuecomment-1202979006

### Reasoning

Make it simpler to create DEPR issues.

**Comment by sarina** [comment]
Unfortunately, these templates cannot be created in `.github` repo - they are on individual repos.

Would you like me to make PRs across all repos and then you can handle getting them merged?

**Comment by sarina** [comment]
Ignore my previous comment, I think I'm wrong! Is there a reason you need us to do this? Could you make a PR to https://github.com/openedx/.github/blob/master/.github/ISSUE_TEMPLATE/depr-ticket.yml ?

**Comment by robrap** [comment]
I learned about this after I created the ticket, and you supplied the link. For now we can close this ticket and start with a PR. Thanks.
