### ISSUE TITLE
[GH Request] Move Learner Records MFE to openedx github org

### ISSUE THREAD

**Issue by hurtstotouchfire** [openedx/tcril-engineering#467]
### Firm Name

2U

### Urgency

medium, would like to have for Olive

### Requested Change

Move https://github.com/edx/frontend-app-learner-record/ to the openedx org in preparation for including it in the next Open edX release.

### Reasoning

It will be disabled by default but I'd like to get it out there for people to try and to streamline contributions in case it's involved in the verified credentials FC work. I'm looking at https://github.com/openedx/build-test-release-wg/issues/131 for guidance on what the other next steps are but any further guidance would be great.

**Comment by Carlos-Muniz** [comment]
@hurtstotouchfire Thank you for the request. Due to the nature of this request, we are currently working with tCRIL legal counsel to make sure we go through the appropriate steps to transition the frontend-app-learner-record repository from the edx organization to the openedx organization.

**Comment by hurtstotouchfire** [comment]
@Carlos-Muniz How long do you expect this to take?

**Comment by nedbat** [comment]
There are still edx-org repos in the Open edX releases. This repo doesn't have to move before Olive to be seen by the community.

**Comment by hurtstotouchfire** [comment]
Ok, thanks @nedbat. FYI @Carlos-Muniz I do still want to move it sooner than later because right now it's not possible to include issues from this repo in our [workstream tracking board](https://github.com/orgs/openedx/projects/23) for Credentials.

**Comment by Carlos-Muniz** [comment]
@hurtstotouchfire 

Noted. Our legal counsel has compiled the required steps:

Can you confirm that 2U is intentionally submitting the [edx/frontend-app-learner-record](https://github.com/edx/frontend-app-learner-record/) repo code as a contribution to the Open edX public platform codebase under the existing 2U-tCRIL license and contribution agreements?

**Comment by Carlos-Muniz** [comment]
@hurtstotouchfire Thanks, your confirmation here is sufficient.
Following [GitHub's guide to Transferring a repository owned by your organization](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-organization), could you please initiate the transfer from the edx org to the openedx org?

**Comment by nedbat** [comment]
I can do it.  GitHub will ask me what teams should have access to the repo.

**Comment by Carlos-Muniz** [comment]
@nedbat If you initiate the transfer, I can add this repo to the openedx/push-pull-all team

**Comment by nedbat** [comment]
@hurtstotouchfire also asks, "can you post in [#aperture-eng](https://edx-internal.slack.com/archives/CFRBDDGMN) (private link) when you’re going to transfer the mfe repo?"

**Comment by nedbat** [comment]
@hurtstotouchfire @Carlos-Muniz I can add that team also, i just wasn't sure if there were other teams that needs particular access.  When we document how to move repos, we should note this step of figuring out the team access, which is a question GitHub asks the person doing the transfer, and they might not have that info at their fingertips.

**Comment by feanil** [comment]
@nedbat I think we just need you to initiate the transfer and then we have documentation for the tCRIL person to do a bunch of things to accept the transfer.  I think we want to get away from having someone who is an admin in both orgs.

**Comment by nedbat** [comment]
OK, so just for clarity, I should assign no teams to the new repo, and then tCRIL will fix it up, is that right?

**Comment by Carlos-Muniz** [comment]
@nedbat That's right. The process from your side should be:
1) Request the transfer and confirm it
2) Initiate the transfer
3) Let us know which teams need access to this repo

tcril-oncall takes care of the rest :+1:

**Comment by nedbat** [comment]
The repo is transfered.

**Comment by Carlos-Muniz** [comment]
@hurtstotouchfire @nedbat 
[frontend-app-learner-record](https://github.com/openedx/frontend-app-learner-record) is now part of openedx, and the push-pull-all team has been given write access to it.
You can let me know here, or in a new ticket if any other teams also need access to it.
