### ISSUE TITLE
[GH Request] Brian Mesick org admin / Core Contributor access

### ISSUE THREAD

**Issue by bmtcril** [openedx/tcril-engineering#468]
### Firm Name

tCRIL

### Urgency

Low urgency - next week or so

### Requested Change

I'd like the following Github permissions added to my bmtcril Github account:

- Org admin for openedx

- Coding cc rights on these individual repos
    code-annotations
    course-discovery
    data-wg
    edx-enterprise-data
    edx-platform
    event-bus-kafka
    tubular

- Coding cc rights on these repos, via a newly created permissions group (name is up for debate... `contrib_analytics`?)
    edx-analytics-configuration
    edx-analytics-dashboard
    edx-analytics-data-api
    edx-analytics-data-api-client
    edx-analytics-exporter
    edx-analytics-pipeline

- Coding cc rights on these repos, via a newly created permissions group (name is up for debate... `contrib_events`?)
    event-routing-backends
    event-tracking
    openedx-events

### Reasoning

Per Sarina Canelake (@sarina) and the [discuss thread](https://discuss.openedx.org/t/coding-cc-rights-brian-mesick/8237/9 ) I've been accepted as a Core Committer and need the access granted to do my job and tCRIL on-call work.

**Comment by feanil** [comment]
Super Nit(feel free to ignore if you disagree) but we've managed to generally use spaces or dashes for team names and I think we've used the shorthand of `cc` for contributor related team names so my suggestions would be `cc-analytics` and `cc-events` for the group names.

**Comment by feanil** [comment]
Naming Feelings(feel free to ignore if you disagree): I think we've been prefixing things related to core contributors with `cc` and somehow have managed to name teams with either dashes or spaces instead of underscores so my suggestion for names would be `cc-analytics` and `cc-events` instead of the ones suggested in the ticket.

**Comment by bmtcril** [comment]
@feanil Makes sense to me

**Comment by Carlos-Muniz** [comment]
Working on this now!

**Comment by Carlos-Muniz** [comment]
Thanks for the request @bmtcril 
You have been added to the newly created @openedx/ccp-committer-bmtcril. In addition, two new teams @openedx/cc-analytics and @openedx/cc-events have been created, and you have been added to them. Lastly, you have been upgraded to "Owner" of the openedx org, which grants you Admin rights.

With great power comes great responsibility. Congratulations and best of luck!

**Comment by sarina** [comment]
@Carlos-Muniz were all steps of https://openedx.atlassian.net/wiki/spaces/COMM/pages/2810249408/Administering+a+CC+Committer+Onboarding+Runbook followed? just checking in because Brian didn't get an invite to Listaflow and I want to make sure the runbook steps are clear.

**Comment by Carlos-Muniz** [comment]
@sarina No, the original request only asks for GH permissions. I was not made aware through this ticket that I needed to run through the entire onboarding procedure.

**Comment by sarina** [comment]
Ah. I had mentioned this in this comment: https://github.com/openedx/tcril-engineering/issues/468#issuecomment-1256315738 and it's in the on-call playbook. I think @bmtcril has done some of these things, could you two coordinate to get the rest done?

**Comment by sarina** [comment]
Also let me know what we can do to make it clearer that a ticket asking for "Core Contributor access" needs to follow the CC onboarding playbook - I'd like to make this seamless for all.
