### ISSUE TITLE
[GH Request] Please add @christopappas to maintainers teams

### ISSUE THREAD

**Issue by colinbrash** [openedx/tcril-engineering#471]
### Firm Name

2U

### Urgency

mid/high urgency

### Requested Change

Please add Chris Pappas - @christopappas to the following teams:

* [ecommerce-maintainers](https://github.com/orgs/openedx/teams/ecommerce-maintainers)
* [ecommerce-worker-maintainers](https://github.com/orgs/openedx/teams/ecommerce-worker-maintainers)
* [frontend-app-ecommerce-maintainers](https://github.com/orgs/openedx/teams/frontend-app-ecommerce-maintainers)
* [frontend-app-payment-maintainers](https://github.com/orgs/openedx/teams/frontend-app-payment-maintainers)

### Reasoning

Chris has joined the Purchase Squad in their current work.

**Comment by Carlos-Muniz** [comment]
Thanks for your request.

@christopappas you have been added to the teams mentioned above.
