### ISSUE TITLE
[GH Request] Onboard shahbaz-arbisoft

### ISSUE THREAD

**Issue by zainab-amir** [openedx/tcril-engineering#473]
### Firm Name

2U edX

### User List (case sensitive!) - Please also include in ticket title

* Shahbaz Shabbir, @shahbaz-arbisoft

### Start Date

28 September 2022

### Urgency

Medium

### Special Requests

Please add Shahbaz to the vanguards team in openedX as well.

**Comment by georgebabey** [comment]
Approved!

**Comment by Carlos-Muniz** [comment]
Thank you for the confirmation.
@shahbaz-arbisoft you have been added to the openedx github organization as well as the push-pull-all and vanguards teams.

**Comment by Carlos-Muniz** [comment]
@e0d Can you add shahbaz-arbisoft to the CLA?

**Comment by e0d** [comment]
I've updated their record, will be in the batch this afternoon.
