### ISSUE TITLE
Kick off meeting with UX stakeholders

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/tcril-engineering#477]
Organize a meeting with stakeholders to discuss how to make UX decisions.  In particular, how it relates to https://github.com/openedx/tcril-engineering/issues/418 and Kshitij's ADRs (https://github.com/openedx/paragon/pull/1388 and https://github.com/openedx/frontend-platform/pull/351), as it has come to light that 2U is working on a potentially colliding solution.

Goals:

* To gather consensus on what the general next steps are.  For example:
  * A regular meeting?
  * A specific place to document UX decisions? (Related to this request: https://github.com/openedx/tcril-engineering/issues/476)
  * Should the [Paragon Design System figma](https://www.figma.com/file/eGmDp94FlqEr4iSqy1Uc1K/Paragon-Design-System) be ported somewhere the community can look at and opine on?
* To get Kshitij and Adam talking specifically about theming solutions
* To gather ideas about how to avoid collisions in the future
* Share meeting notes

Invite the following people for the meeting:

* Mike Leary
* Gabe Weinberg
* Adam
* Kshitij
* Ben Warzeski
* Fox Piacenti
* Allie

**Comment by arbrandes** [comment]
The theming bits of this discussion happened in a specific meeting today: see https://github.com/openedx/tcril-engineering/issues/475 for details.

As for the general UX conversation, the ball is now on 2U's court to organize a place to do it.  Specifically, on Gabriel Weinberg.  See the [action items](https://openedx.atlassian.net/wiki/spaces/BPL/pages/3549954438/2022-10-05+Meeting+notes#%E2%9C%85-Action-items) on the Paragon Working Group meeting where this was discussed.

**Comment by arbrandes** [comment]
This was discussed again [today](https://openedx.atlassian.net/wiki/spaces/BPL/pages/3560472596/2022-10-26+Meeting+notes) in the PWG meeting.  Copy-pasting from the wiki page:

> At a previous meeting @Gabriel Weinberg offered to ask around about when/where we could start getting the community involved in UX discussions
> I’ve (@Adolfo Brandes) been asked the same question, so I’m checking back :slight_smile: 
> 
> Notes:
> 
> * Community also happy to just stay informed on what’s happening with design work, rather than actively contributing.
> * New FedX meeting is more technical in nature (FED), not so much design conversations.
> * [Gabe] Is this improvements to contributions to Paragon specifically? Or is it more for feature development across the platform?
> * 2U has largely driven design of Open edX, but tCRIL/community has desire to keep taps on design updates to these platforms.
> * PWG is probably not the right group for this purpose since not all feature work comes through PWG (only when a use case for new/updated component, for example).
> * FWG is also more technical in nature.
> * We’re looking for a cross-functional meeting for context/knowledge sharing around design.
> * Gabe + Adolfo to sync offline to find a better medium for these conversations.
> * Ali would also like to get involved in this :slight_smile: 
> * May also do an inform about this with Product Working Group.

**Comment by arbrandes** [comment]
See conversation [in the forum](https://discuss.openedx.org/t/core-contributor-sprint-retro-15-october-31-october/8627/8?u=arbrandes).

**Comment by arbrandes** [comment]
This will be kicked off today during the PWG meeting.

**Comment by jmakowski1123** [comment]
@arbrandes Do these resonate with you as next steps from the meeting?

Next step: Identify a bounded project to experiment with pulling UX representatives into product working group. Might start with Discussions MFE. 1) Identify who on the UX side is most connected with UX decisions for that MFE and 2) Pull UX documentation into public (full notes here: https://openedx.atlassian.net/wiki/spaces/COMM/pages/3572203578/2022-11-08+-+Product+Working+Group+Meeting+Notes+and+Agenda)

**Comment by arbrandes** [comment]
Sounds exactly right!  I figure we can close this one and track next steps separately.
