### ISSUE TITLE
Update Open edX redirect order

### ISSUE THREAD

**Issue by sarina** [openedx/tcril-engineering#48]
Currently openedx.org redirects to open.edx.org.  We should change that as we will not have control of edx.org domains and it's a better for the project branding.

AC:
- [ ] Understand what needs to happen so that GA data is preserved from the open.edx.org world of today.
- [ ] Understand what Wordpress changes need to be made to support hosting the website at openedx.org
- [ ] Work with edX to configure redirects from open.edx.org to openedx.org

**Comment by sarina** [comment]
@feanil left this comment on the original issue:

Took a look at this today, it looks like all the permanent redirects(301s) are from the `http` version of a site to the `https` version of the same site.  All the redirects to https://open.edx.org are made as 302s so it should be pretty safe to turn these around.

```
    | Url                      | Response Code | New location if relevant  | Potential Change                                        |
    |--------------------------+---------------+---------------------------+---------------------------------------------------------|
    | http://openedx.org       |           301 | https://openedx.org/      |                                                         |
    | https://openedx.org      |           302 | http://open.edx.org/      | Update this to directly serve the website               |
    |                          |               |                           |                                                         |
    | http://open.edx.org      |           301 | https://open.edx.org/     |                                                         |
    | https://open.edx.org     |           200 | <Actual Site Content>     | Update this to redirect to https://openedx.org at least |
    |                          |               |                           | 24 hrs after that url has been serving actual content   |
    |                          |               |                           |                                                         |
    | http://www.openedx.org   |           301 | https://www.openedx.org/  |                                                         |
    | https://www.openedx.org  |           302 | http://open.edx.org       |                                                         |
    |                          |               |                           |                                                         |
    | http://www.open.edx.org  |           301 | https://www.open.edx.org/ |                                                         |
    | https://www.open.edx.org |           302 | http://open.edx.org/      | Update to redirect to https://openedx.org               |
```

There is going to be a period of time where we'll need to serve the same content from both `https://open.edx.org` and from `https://openedx.org` to not get people caught in redirect loops.  This phase should need to last only a few hours but to be safe I suggest we leave it that way for 24hrs.

For the Cutover, we can make a new site on Sitegrounds that's a copy of the original site and not modify it for the 24hrs after we've made it.

We'll need SSL certs for the new site setup, so we'll probably want to solve that in the same way we did at edX(using ACM and a cloudfront distro).

Next Steps:
* Figure out who needs to make what changes
  * Most of the redirects are done using cloudfront distros owned and managed by edx@2U so need to figure out what they'll need to change on their end and when.
* Figure out when we need to make all these changes.

**Comment by e0d** [comment]
@feanil checking the status of this, @ehuthmacher has a blog post scheduled to go live today.

**Comment by feanil** [comment]
@e0d this is done as of this morning, there's some cleanup left to do before I close the PR but `http(s)?://*open.edx.org` is now redirecting to `https://openedx.org`

**Comment by feanil** [comment]
Note to self:  These are the last two things that need to happen before we can close this ticket.
* Waiting for https://github.com/edx/terraform/pull/4240 to land.
  * Needs a new review from edX SRE
* Waiting for the old open.edx.org site grounds site to be deleted.
  * The team will disable the open.edx.org site tomorrow to verify that it's safe to delete.

**Comment by feanil** [comment]
From Eden H:
> The open.edx.org siteground site is scheduled to be deleted on 1/19/22

This ticket can be closed once we've confirmed that that operation has completed.

**Comment by feanil** [comment]
The open.edx.org site has been removed so this work is complete.
