### ISSUE TITLE
[GH Request] Onboard jfinkiels

### ISSUE THREAD

**Issue by maliyath** [openedx/tcril-engineering#481]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

Jacqueline Finkielsztein @jfinkiels

### Start Date

10/3/2022

### Urgency

High urgency

**Comment by e0d** [comment]
@georgebabey can you confirm this is right?  I was not sure if this was meant to be an off-boarding ticket.

**Comment by maliyath** [comment]
Hi, this was meant to be an onboarding ticket

**Comment by e0d** [comment]
Group has been updated, CLA check will be updated this afternoon.

**Comment by maliyath** [comment]
Hi team -- following up here! User Jacqueline Finkielsztein no longer has access to this old account @jfinkiels, would you be able to remove her access and offboard her? She would like to be re-added using her new account @jackfinkiel

**Comment by e0d** [comment]
@maliyath I can do that.  I knew that Jacqueline has been focused on a small set of repositories focused on data and analytics in the past, do you have a a list of teams and or repos she needs access to?

**Comment by e0d** [comment]
@maliyath bumping this.
