### ISSUE TITLE
[GH Request] Please give me admin access to openedx/nedbat-test-trigger

### ISSUE THREAD

**Issue by nedbat** [openedx/tcril-engineering#484]
### Firm Name

2U

### Urgency

Today please

### Requested Change

Please add me as an admin of https://github.com/openedx/nedbat-test-trigger

### Reasoning

I created this repo to test some repo topologies: https://github.com/openedx/nedbat-test-trigger

I was an owner of the openedx org when I made it, but I am not anymore.  I need to be added as an admin to the repo so I can continue the experiments.

Thanks.

**Comment by e0d** [comment]
Done.
