### ISSUE TITLE
[GH Request] Offboard multiple users who have been terminated from 2U

### ISSUE THREAD

**Issue by maliyath** [openedx/tcril-engineering#488]
### Firm Name

2U

### User List  (case sensitive!) - Please also include in ticket title

Users Name | github username

Abdurrahman Asad | A-ASAD
Alex Ye | alexander-ye
Brian Wilson | brianhw
Brian Mesick | bmtcril
Carlos Muniz | Carlos-Muniz
Dave Ormsbee | ormsbee
Debbie Jacob | debbiejacob
Dillon Dumesnil | Dillon-Dumesnil
Eden Huthmacher | ehuthmacher
Edward Zarecor | e0d
Feanil Patel | feanil
Jazib Humayun | jazibhumayun
Julia Eskew | doctoryes
Kyle McCormick | kdmccormick
Long Lin | long74100
Manny Moquete | manny-m
Matt Caplan | caplan188
Matthew Piatetsky | MatthewPiatetsky
Michael Terry | mikix
Michelle Philbrick | mphilbrick211
Sarina Canelake | sarina
Stuart Young | estute
Waheed Ahmed | waheedahmed
William Huang | whuang1202
Yaromyr Plashenko | Yar0myr
Zia Fazal | ziafazal

### End Date

10/6/2022

### Urgency

High urgency - terminated users

**Comment by e0d** [comment]
Several of the folks on your list have access via other affiliations with the project.  I've removed:

| Name | GitHub Username |
| ---------- | ---------------------- |
| Abdurrahman Asad | A-ASAD | 
| Alex Ye | alexander-ye | 
| Brian Wilson | brianhw | 
| Debbie Jacob | debbiejacob |
| Dillon Dumesnil | Dillon-Dumesnil |
| Jazib Humayun | jazibhumayun |
| Julia Eskew | doctoryes |
| Long Lin | long74100 |
| Manny Moquete | manny-m |
| Matt Caplan | caplan188 |
| Matthew Piatetsky | MatthewPiatetsky |
| Michael Terry | mikix |
| Stuart Young | estute |
| Waheed Ahmed | waheedahmed |
| William Huang | whuang1202 |
| Yaromyr Plashenko | Yar0myr |

**Comment by maliyath** [comment]
Hi, @e0d thank you for working on this. Does this mean the remaining users are unable to be offboarded from this instance of github?

**Comment by e0d** [comment]
That's correct.  In case it's not clear, this instance of GitHub is not for 2U's exclusive use.  In some cases, folks who work here, say for tCRIL, formerly worked for edX/2U.  However, our entire community might access this instance if their work requires it.

**Comment by maliyath** [comment]
@e0d Thank you for the clarification!
