### ISSUE TITLE
[GH Request] Onboard <Mashal-m>

### ISSUE THREAD

**Issue by maliyath** [openedx/tcril-engineering#491]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

Mashal Malik, @Mashal-m

### Start Date

9/20/2022

### Urgency

High urgency

### Special Requests

Please add them to the Arbisoft CLA

**Comment by e0d** [comment]
This person has access.

@georgebabey we typically add Aribsoft folks working for you under the 2U CLA as their contributions are on your behalf.  If that should change, see the "Special Instructions," let's discuss.
