### ISSUE TITLE
[GH Request] Onboard Glenn Martin

### ISSUE THREAD

**Issue by colinbrash** [openedx/tcril-engineering#492]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

Glenn Martin, @grmartin

### Start Date

10/3/2022

### Urgency

mid/high urgency

### Special Requests

Please add to:

* [frontend-app-ecommerce-maintainers](https://github.com/orgs/openedx/teams/frontend-app-ecommerce-maintainers)
* [frontend-app-payment-maintainers](https://github.com/orgs/openedx/teams/frontend-app-payment-maintainers)
* [ecommerce-worker-maintainers](https://github.com/orgs/openedx/teams/ecommerce-worker-maintainers)
* [ecommerce-maintainers](https://github.com/orgs/openedx/teams/ecommerce-maintainers)
* [revenue-squad](https://github.com/orgs/openedx/teams/revenue-squad)
* [push-pull-all](https://github.com/orgs/openedx/teams/push-pull-all)

**Comment by e0d** [comment]
He'll be added in the next CLA update batch.

**Comment by e0d** [comment]
I've confirmed he's been successfully added to the CLA file.

**Comment by colinbrash** [comment]
@e0d thanks!  Would you please also add him to the teams listed?

**Comment by e0d** [comment]
He has been @colinbrash , though it doesn't look as though he's accepted his invitation to the org.

**Comment by colinbrash** [comment]
Ok, thank you!  I'll ping him to do that.
