### ISSUE TITLE
[GH Request] Onboard marlonkeating

### ISSUE THREAD

**Issue by bcitro** [openedx/tcril-engineering#493]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

Marlon Keating, @marlonkeating

### Start Date

11 October 2022

### Urgency

High urgency, ASAP

### Special Requests

Please add Marlon to the following teams:

- https://github.com/orgs/openedx/teams/enterprise-quokkas
- https://github.com/orgs/openedx/teams/push-pull-all

**Comment by georgebabey** [comment]
Confirmed..

Will follow up internally to determine why this came from the manager and not helpdesk

**Comment by e0d** [comment]
They've:

- been invited to the org
- added to the requested teams
- added to the CRM

They'll be in the next batch from the CRM to GitHub for the CLA check.

**Comment by e0d** [comment]
I've confirmed he's been added to the CLA file.
