### ISSUE TITLE
Create the roadmap issue(s) that will track the new MFEs in Olive

### ISSUE THREAD

**Issue by arbrandes** [openedx/tcril-engineering#495]
The AC is to have product-oriented Roadmap tickets for each new MFE that include robust information about:

- Product scope and features included
- What features are deprecated
- Community release information

Tasks:

- [x] Create ticket shells
- [x] Coordinate with Ryan, Aamir, Spencer, Brad to get as much product documentation as possible

**Comment by jmakowski1123** [comment]
Roadmap tickets here:

Discussions MFE: https://github.com/openedx/platform-roadmap/issues/106
Course Authoring MFE: https://github.com/openedx/platform-roadmap/issues/213
Authentication MFE: https://github.com/openedx/platform-roadmap/issues/214
Learner Record MFE: https://github.com/openedx/platform-roadmap/issues/215
ORA Grading MFE: https://github.com/openedx/platform-roadmap/issues/216

**Comment by arbrandes** [comment]
@jmakowski1123, are we done with this one?
