### ISSUE TITLE
Unarchive solutions related xBlocks

### ISSUE THREAD

**Issue by feanil** [openedx/tcril-engineering#50]
The repos below were archived temporarily because they still require some legal sign-off before the licensing and ownership rights are fully set.  Once that's done, they should be un-archived and we can continue to accept new contributions.

- xblock-image-explorer
- xblock-adventure
- xblock-drag-and-drop-v2
- xblock-google-drive

**Comment by ormsbee** [comment]
Note: Of these, I think xblock-drag-and-drop-v2 is the most important one, since it's a commonly used problem type. The others are much more obscure.

**Comment by sarina** [comment]
I forgot about this one... I'm sending an email to legal about this and get the ball rolling on what we are allowed to do.

**Comment by e0d** [comment]
We are actively have conversations with McKA about this.  I am hopeful that we'll have a resolution this week and will be in a position to unarchive :crossed_fingers:

**Comment by sarina** [comment]
Thanks @e0d - assigning you for now so we can track who's on this ticket.

**Comment by feanil** [comment]
@e0d reviewed the logs and did not find any issues.  We should be all set to un-archive these.
![image](https://user-images.githubusercontent.com/781561/153051036-5c908eb6-4239-40d1-a610-5498b73f92dc.png)

**Comment by feanil** [comment]
All 4 archives have been un-archived.
