### ISSUE TITLE
Create rough draft tool that will download the necessary translation files from openedx-translations into a locally cloned repo for a simulation deployment

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/tcril-engineering#500]

**Comment by Carlos-Muniz** [comment]
[openedx/code-annotations](https://github.com/openedx/code-annotations) is a CLI tool example.
[openedx/edx-cookiecutters python-template](https://github.com/openedx/edx-cookiecutters/tree/master/python-template) is a good place to get started for building a python package.
