### ISSUE TITLE
[GH Request] Need review on the reusable requirements upgrade workflow fix

### ISSUE THREAD

**Issue by UsamaSadiq** [openedx/tcril-engineering#507]
### Firm Name

2U

### Urgency

High Urgency - Its a blocker on all the requirements upgrade workflows across 2U/OpenEdx repos.

### Problem
- After the new release of `checkout@v2.5.0` the requirements upgrade PRs started failing in all repos.
- The error was able to be reproduced with replicating the if condition in a test [PR](https://github.com/openedx/edx-rest-api-client/pull/237).

### Request
- The [fix PR](https://github.com/openedx/.github/pull/28) needs to be reviewed and merged as `arbi-bom` doesn't have access to merge.

### Testing
- After fixing and testing the fix on local, now creating the PR to test this change in the upgrade requirements workflows by triggering a custom workflow build against the updated workflow.
- Since the PR has been created against a fork so this commit hash or branch name can't be used in any workflow that's why we need to merge the change to test it properly in other requirements upgrade actions.

**Comment by feanil** [comment]
Reviewed and merged.
