### ISSUE TITLE
Transfer ownership of tcril.org and other tcril domains from edx/2U

### ISSUE THREAD

**Issue by sarina** [openedx/tcril-engineering#51]
https://openedx.atlassian.net/browse/PSRE-1159 has the details but some of the domains couldn't be transferred because they were bought recently.  We'll have to do this transfer after Dec 7th so making this separate ticket for that work.  It's related to https://github.com/openedx/decoupling/issues/3 (set up tCRIL AWS accounts appropriately)

**Comment by feanil** [comment]
The last of the domains have been transferred and are now fully under tCRIL control.
