### ISSUE TITLE
[GH Request] Move https://github.com/edx/frontend-lib-special-exams/ from edx org to openedx org

### ISSUE THREAD

**Issue by schenedx** [openedx/tcril-engineering#511]
### Firm Name

2U

### Urgency

Medium - At the end of the week because she is a software developer

### Requested Change

The repository https://github.com/edx/frontend-lib-special-exams/ is currently belonging to the edx org on github. After a conversation with Kyle, we believe this repository should be part of the openedx github org.
This ticket is to actually implement the move.

### Reasoning

The repository is a required library with https://github.com/openedx/frontend-app-learning. Since the Learning MFE is in Openedx and used by the community, it is necessary for the library it requires to also be in the openedx github org.

**Comment by kdmccormick** [comment]
Alright, tCRIL is OK to accept this repo as a contribution from 2U and move forward with the transfer 👍🏻 

@jmbowman could you initiate the transfer from your side? I will make sure it the `push-pull-all` is given write access to it, and `masters-devs-cosmonauts` is given admin access to it.

**Comment by kdmccormick** [comment]
@schenedx and I will be doing a video call soon to execute the transfer.

**Comment by kdmccormick** [comment]
Done: https://github.com/edx/frontend-lib-special-exams/

We gave write access to `push-pull-all` and admin acces to `masters-devs-cosmonauts`.
