### ISSUE TITLE
[GH Request] Move `browserslist-config` from edx GH org to openedx GH org

### ISSUE THREAD

**Issue by adamstankiewicz** [openedx/tcril-engineering#515]
### Firm Name

2U

### Urgency

Low urgency

### Problem/Request

The `browserslist-config` repository largely intends to define which browsers are officially supported across the Open edX  platform in a shared configuration that can be extended by any other repo (single source of truth): https://github.com/edx/browserslist-config

It currently lives in the `edx` Github organization.

### Reasoning

The browserslist config is applicable to all frontend facing repos in the `openedx` Github org, so it should really belong in the `openedx` org instead.

Heads up, the repo releases to NPM via semantic-release.

Thanks!

**Comment by sarina** [comment]
@adamstankiewicz just ack'ing this - sorry I missed it Friday. I'll try to take a look today.

**Comment by sarina** [comment]
Request is legit from my perspective. Next steps:

1. I need to consult with my legal team - I may need someone else at 2U verify this request is OK.
2. Once everything is in order, I will need to work with someone on your side who is a GitHub administrator to perform the transfer.

**Comment by adamstankiewicz** [comment]
> Request is legit from my perspective. Next steps:
> 
> 1. I need to consult with my legal team - I may need someone else at 2U verify this request is OK.
> 2. Once everything is in order, I will need to work with someone on your side who is a GitHub administrator to perform the transfer.

@sarina

1. Is there someone from 2U in particular you're looking to verify this request (e.g., manager approval)?
2. I have administrator rights to the repo so I believe I should be able to kick off the transfer once ready.

<img width="796" alt="image" src="https://user-images.githubusercontent.com/2828721/197610119-aa817bfa-fa2a-4f55-a382-e81e4330bc8a.png">

**Comment by sarina** [comment]
re: 1 - I don't know, I'm checking now.
re: 2 - great! I'll coordinate with you!

**Comment by sarina** [comment]
@adamstankiewicz we are good to go! I'm looking at https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-organization and you should be able to click that transfer button to `openedx` and I'll approve it on my side.

**Comment by sarina** [comment]
Also @adamstankiewicz could you specify which user group(s) should have write access to this repository? Generally 2U repos get put into `push-pull-all`, but you may have different requirements.

**Comment by adamstankiewicz** [comment]
@sarina The `push-pull-all` user group makes sense for this repo.

Regarding the transfer:

<img width="1510" alt="image" src="https://user-images.githubusercontent.com/2828721/197613646-3a798d7c-8d6b-470f-92b9-3a93de292048.png">

Interesting. Apparently in order to transfer to another organization, you need permissions to create repos in that other organization?

> Transfer this repository to another user or to an organization where you have the ability to create repositories.

**Comment by sarina** [comment]
yeah, that's what I was super afraid of. it's a dumb restriction. let me consult legal again 😮‍💨

**Comment by sarina** [comment]
Hey @adamstankiewicz - we need to follow this procedure: https://openedx.atlassian.net/wiki/spaces/COMM/pages/3438903337/On-call+Playbooks#%F0%9F%8F%97-Transferring-repositories-in-or-out-of-the-openedx-GitHub-organization

Since we'll need to do this synchronously, let's find a few minutes to do it together. Add 15m to my calendar here: https://calendly.com/sarina-tcril/15min?back=1&month=2022-10

**Comment by adamstankiewicz** [comment]
@sarina Scheduled some time with you on your calendar for tomorrow afternoon; thanks!

**Comment by sarina** [comment]
Transfer complete!

**Comment by adamstankiewicz** [comment]
thanks again @sarina
