### ISSUE TITLE
[GH Request] mphilbrick211, new OSPR PM CC, needs triage access

### ISSUE THREAD

**Issue by sarina** [openedx/tcril-engineering#516]
### Firm Name

tCRIL

### Urgency

Medium

### Requested Change

The Project Manager will need [Triage Permissions](https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-roles-for-an-organization) on all repositories that are a part of the Open edX Platform, as the position requires the following abilities:

- Assign and remove labels

- Assign and remove people from PRs

- Close and re-open PRs (this is an easy way to trigger tests, and stale PRs need to be closed from time to time)

- Request PR reviews.

Please grant these to @mphilbrick211

### Reasoning

Nomination thread: https://discuss.openedx.org/t/core-contributor-nomination-michelle-philbrick/8408

Role access rights: https://openedx.atlassian.net/wiki/spaces/COMM/pages/3548807177/Community+Contributions+Project+Manager#OSPR-Project-Manager-Access-Rights

**Comment by sarina** [comment]
@mphilbrick211 could you provide me a list of the repos you're currently looking at? I have to add the repos one-by-one and would rather start off giving you permissions to the ones that are going to be used the most.

**Comment by mphilbrick211** [comment]
> @mphilbrick211 could you provide me a list of the repos you're currently looking at? I have to add the repos one-by-one and would rather start off giving you permissions to the ones that are going to be used the most.
> 
> For internal reference: group made: https://github.com/orgs/openedx/teams/community-pr-triage-managers

blockstore
course-discovery
credentials
ecommerce
ecommerce-worker
frontend-app-ecommerce
frontend-app-payment
frontend-app-publisher
openedx-events
xblock-lti-consumer

**Comment by sarina** [comment]
Thanks @mphilbrick211 !

I've granted you triage access on all those repos and edx-platform.

@feanil is working on automation to make sure you have triage access on _all_ repos, which should be ready next week. I'm going to hand this ticket to him. In the meantime if you need triage access to any other repo just ping on this ticket.

**Comment by feanil** [comment]
Once https://github.com/openedx/terraform-github/pull/41 lands I should be able to give you triage access to all the public repos pretty quickly.

**Comment by sarina** [comment]
@feanil for posterity's sake can you share the solution used to solve this, for people looking at prior art for new incoming Community Managers?

**Comment by feanil** [comment]
Yea, it's the change linked in https://github.com/openedx/terraform-github/pull/41,  more specifically,  https://github.com/openedx/terraform-github/blob/main/migrate/repo_checks.py#L152  which ensures that the `community-pr-triage-managers` github team has triage access on all public github repos in the openedx org.  As long as new community managers are added to that team, nothing else should need to be done.
