### ISSUE TITLE
[GH Request] Delete wiki spam

### ISSUE THREAD

**Issue by nedbat** [openedx/tcril-engineering#522]
### Firm Name

2U

### Urgency

No rush

### Problem/Request

This wiki page and its child should be deleted: https://openedx.atlassian.net/wiki/spaces/OEPM/pages/3564470399/Topics+for+Expository+Essay+for+High+School+and+College+Students

I'd do it, but I don't have delete permissions.

### Reasoning

It's spam.

**Comment by bmtcril** [comment]
Hey Ned! Sorry for the delay, it took me a bit to get permissions. By the time I got there it was 3 users and 11 pages, so I'll keep monitoring.

**Comment by nedbat** [comment]
There's more: https://openedx.atlassian.net/wiki/spaces/OEPM/pages/3567485417/Tips+for+Using+Adjectives+in+a+Narrative+Essay+Guide+2022

If someone wants, we can talk about how to monitor for spam like this.

**Comment by bmtcril** [comment]
I think I got all of those before I saw this one, but am monitoring the open spaces for anything new. If you want to grab me on slack about how to monitor more effectively I'd be happy to have that conversation.
