### ISSUE TITLE
[GH Request] Am I still an admin on the openedx.org Wordpress instance?

### ISSUE THREAD

**Issue by nedbat** [openedx/tcril-engineering#524]
### Firm Name

2U

### Urgency

Low urgency

### Problem/Request

I have a login for openedx.org, username "ned".  It doesn't have rights to view https://openedx.org/wp-admin/ .  I don't know if it should.

I used to be able to see wp-admin, but that might have been under a different login (ned@edx.org?), I'm a bit confused about how many I had.

This is a two-fold request:
1. Should I still have access to wp-admin?
2. If so, I don't, can it be fixed?

### Reasoning

I used to help manage this site, and might still be helpful in the future.  I was trying to double-check that the CLA link was to the latest uploaded document, and could not get to wp-admin.

**Comment by e0d** [comment]
You are not currently an admin on the site.  I don't think you should still have admin access, but if you have a reason for needing it, let's discuss.  I believe this change was made during the decoupling work.

You may also recall that you changed the URL for the admin application to defeat script kiddie attacks :)

**Comment by nedbat** [comment]
OK, it's not a problem to not have admin, i just wasn't sure if it was my fumbling preventing me from checking.

I changed the login URL, but I think /wp-admin is still the dashboard URL? Doesn't matter, I can't get to it :)
