### ISSUE TITLE
[GH Request] Onboard farhanumar

### ISSUE THREAD

**Issue by adzuci** [openedx/tcril-engineering#527]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

farhanumar

### Start Date

01 July 2022

### Urgency

Pretty high urgency, sorry we missed this months ago

### Special Requests

Please also add Farhan to https://github.com/orgs/openedx/teams/devops/members

**Comment by bmtcril** [comment]
Hi @adzuci and @farhanumar! The invite has been sent out to the Github associated email address. It should include group permissions for:

- openedx/push-pull-all
- openedx/devops

@e0d Farhan should be ready to be added to the CLA database.

**Comment by e0d** [comment]
@adzuci can you please provide Farhan's full name?

**Comment by adzuci** [comment]
His full name is Farhan Umer
