### ISSUE TITLE
Talk to Legal about what to do with CLA checks in the edX Org

### ISSUE THREAD

**Issue by feanil** [openedx/tcril-engineering#533]
Right now the Open edX CLA gets checked on the edX org repos.  Does this makes sense? Do we need to do things?

**Comment by nedbat** [comment]
This might touch on the question of how to move repos from edx to openedx in GitHub.

**Comment by feanil** [comment]
There were a lot of complicated outcomes of this conversation but the key piece of information that's relevant moving forward is that from a legal perspective, checking whether the Open edX CLA has been signed before accepting changes into the `edx` org does not actually mean anything and is not a useful requirement in that github org.

Moving forward edX/2U should not run the CLA checker in the `edx` org since it might confuse people into thinking that it's safe to take 3rd party contributions when in fact that is not the case.
