### ISSUE TITLE
[GH Request] Move frontend-app-course-authoring to openedx org

### ISSUE THREAD

**Issue by jristau1984** [openedx/tcril-engineering#534]
### Firm Name

2U

### Urgency

Medium Urgency (resolve in <one week)

### Requested Change

Move frontend-app-course-authoring to the openedx org.

### Reasoning

This MFE is needed by the new Discussions MFE and the new Text Editor in Studio.  Both are trying to get into the Olive release.

**Comment by bmtcril** [comment]
Hi Jeremy, I'm on call this week so will likely be running this. Couple of things while I'm running this by internally to make sure we want to accept the request:

1. Can you explicitly confirm that 2U is intentionally submitting frontend-app-course-authoring's code as a contribution to the Open edX public platform codebase under the existing 2U-tCRIL license and contribution agreements?
2. Have you done one of these transfers before? If not I can share the process with you so you know what to expect before we try to set up a time to do the transfer.
