### ISSUE TITLE
[GH Request] Onboard <fumer>

### ISSUE THREAD

**Issue by alexrswan01** [openedx/tcril-engineering#535]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

*Farhan Umer, @farhanumar

### Start Date

11/9/2022

### Urgency

Urgent

### Special Requests

push or pull requests to the configuration repo

**Comment by bmtcril** [comment]
Hi @georgebabey can you verify that this request is legitimate for us?

**Comment by ormsbee** [comment]
I'm closing this, as it looks like it should be covered by https://github.com/openedx/tcril-engineering/issues/540

Please re-open if that is incorrect.
