### ISSUE TITLE
[GH Request] add Arbisoft SRE folks to openedx admin team

### ISSUE THREAD

**Issue by matthugs** [openedx/tcril-engineering#540]
### Firm Name

2U/edX

### Urgency

medium urgency, blocking sprint progress

### Requested Change

Please add [Farhan Umar](https://github.com/farhanumar) and [Nicholas Moy](https://github.com/ohnickmoy) to https://github.com/orgs/openedx/teams/edx-admin/members.

### Reasoning

Both of these users are members of the PSRE team inside of OCM/edX/2U, and should have administrative access to all push-pull-all repos.

**Comment by ormsbee** [comment]
@adzuci: Done.
