### ISSUE TITLE
[GH Request] Onboard chennighan2u

### ISSUE THREAD

**Issue by schenedx** [openedx/tcril-engineering#541]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

chennighan2u

### Start Date

Nov 14, 2022

### Urgency

Medium - At the end of the week because he is a software development intern

**Comment by ormsbee** [comment]
@chennighan2u has been invited to the openedx org and added as a member of push-pull-all.

Tagging @e0d for the CLA check database.

**Comment by e0d** [comment]
@schenedx Can you please provide their first and last name?

**Comment by chennighan2u** [comment]
Chris Hennighan

**Comment by e0d** [comment]
Added, will be in this afternoon's batch.
