### ISSUE TITLE
[GH Request] Offboard Tj-Tracy

### ISSUE THREAD

**Issue by hurtstotouchfire** [openedx/tcril-engineering#543]
### Firm Name

2U

### User List  (case sensitive!) - Please also include in ticket title

* Thomas Tracy, @Tj-Tracy 

### End Date

11 November 2022

### Urgency

High

### Retained Permissions & Special Requests

I've already removed TJ from https://github.com/orgs/openedx/teams/2u-aperture/members

**Comment by ormsbee** [comment]
He's also been removed from the openedx org.
