### ISSUE TITLE
[GH Request] Offboard <Carlos-Muniz> < kdmccormick > <m-pitera> < azanbinzahid>

### ISSUE THREAD

**Issue by stooks61** [openedx/tcril-engineering#548]
### Firm Name

2U

### User List  (case sensitive!) - Please also include in ticket title

Carlos Muniz, @Carlos-Muniz
Kyle McCormick, @kdmccormick
Marcin Pitera, @m-pitera
Azan Bin Zahid, @azanbinzahid 

### End Date

21 November 2022

### Urgency

Medium - users are no longer with the company

**Comment by ormsbee** [comment]
@georgebabey confirmed in chat that @stooks61 is with 2U IT.

@stooks61: @Carlos-Muniz and @kdmccormick now work at tCRIL, so I will not be revoking their access. I will remove @m-pitera and @azanbinzahid from the openedx GitHub org.

**Comment by georgebabey** [comment]
Thanks @ormsbee! This was based off a list of people with access that @sarina provided, hence the tCRIL people appearing

**Comment by ormsbee** [comment]
@azanbinzahid: If you believe this was an error, please let me know. We clearly still have a few issues to iron out with this entire process.

**Comment by stooks61** [comment]
@ormsbee Thanks for your help with this.
