### ISSUE TITLE
[GH Request] <Confirm Untracked Users>

### ISSUE THREAD

**Issue by stooks61** [openedx/tcril-engineering#549]
### Firm Name

2U

### Urgency

Medium - Completing Audit 

### Problem/Request

Hi Team, 

I'm working on tracking access for GitHub (github.com/openedx) and noticed a few users with access but no profile in HUB. Please confirm the following users require access to github.com/openedx:

- Piotr Surowiec, @Agrendalath
- Sofiane Bébert, @BbrSofiane
- Felipe Montoya, @felipemontoya
- Naeem Ilyas, @naeem91
- Omar Al-Ithawi, @OmarIthawi
- Shadi Naif, @shadinaif

Best,

Santana 

### Reasoning

Received a request to track existing access in Salesforce HUB - I'd like to ensure tracking is accurate.

**Comment by OmarIthawi** [comment]
Currently I don't _require_ access to any repo at @openedx. 

The only repo on which that I have access to is openedx/edx-ace but it's been a long time since I contributed to it and I think it's fairly stable so I'm fine with removing my access to all repos in Open edX.

Same goes for my teammate @shadinaif at Appsembler.

**Comment by ormsbee** [comment]
@e0d, @stooks61: Is this tCRIL's Salesforce instance or something 2U is tracking separately...?

**Comment by e0d** [comment]
@stooks61 tCRIL manages access to the openedx GitHub repository.  There will always be community members with access to it that do not work for 2U.  I would not expect them to have a profile in Hub, which I believe is an internal 2U system.  I actually surprised that the list above isn't much longer.

Can I ask what you were trying to determine with this audit?  It will help me understand where the disconnect is.

FYI: @georgebabey

**Comment by georgebabey** [comment]
These were from the original list given to us from tCRIL which was not filtered to just edx/2U employees. 

I believe we can confirm that these individuals are community members/do not have a contributor agreement based on 2U and close this out.

**Comment by stooks61** [comment]
Hey! I was just making sure access was properly tracked in 2U system for former/current employees. Thanks for the information. I'll close out the request now.
