### ISSUE TITLE
[GH Request] Need review on upgrade requirements workflow PR

### ISSUE THREAD

**Issue by aht007** [openedx/tcril-engineering#550]
### Firm Name

2U

### Urgency

High Urgency - Upgrade Jobs failing daily across 2U/OpenedX repos

### Problem/Request

**Problem**
There is a bug in upgrade requirements workflow which is causing the upgrade jobs to fail daily. It was uncovered just recently because previously all the repos were using workflow from edX's github org. After the jobs were updated to use openedX's workflow the builds started to fail.

**Request**
I have fixed the bug in this PR: https://github.com/openedx/.github/pull/33 but I don't have access to merge this.I need someone from your team to review and merge this.

### Reasoning

N/A

**Comment by arbrandes** [comment]
Reviewed it, but I suspect the problem should be fixed in the calling workflow, not in the shared one.

**Comment by arbrandes** [comment]
This is my recommended fix: https://github.com/openedx/.github/pull/35

**Comment by arbrandes** [comment]
Fix merged.  @aht007, feel free to reopen this issue if your problem persists!
