### ISSUE TITLE
[GH Request] Delete Confluence spam page

### ISSUE THREAD

**Issue by robrap** [openedx/tcril-engineering#557]
### Firm Name

2U

### Urgency

Low? - but very quick

### Problem/Request

Please delete the following page:
https://openedx.atlassian.net/wiki/spaces/AC/pages/3593994241/Notice+Free+Live+Cricket+Spilling+on+Crichd

You may also want to disable the author's account.

### Reasoning

Speaks for itself.

**Comment by Carlos-Muniz** [comment]
Thank you for the request! I have deleted the spam post and suspended the user's access. Thank you for alerting us about this spam. If you find more, please let us know. We are currently working on a method to reduce the spam posts and spammers.
