### ISSUE TITLE
[GH Request] Remove access for Usman (symbolist)

### ISSUE THREAD

**Issue by sarina** [openedx/tcril-engineering#559]
### Firm Name

tCRIL

### Urgency

Medium

### Requested Change

Usman (symbolist) has left the Core Contributor program. Please remove the team he belongs to, as well as remove all access to openedx repos.

### Reasoning

Usman has left the cc program

**Comment by Carlos-Muniz** [comment]
* `symbolist` has been removed from the `Core Contributor Program Committers` team. 
* The `CCP Committer: symbolist` team has been deleted. 
* `symbolist` has been removed from the `openedx` org.
