### ISSUE TITLE
[GH Request] Add write access to frontend-app-learner-record to edx-transifex-translations team

### ISSUE THREAD

**Issue by Carlos-Muniz** [openedx/tcril-engineering#567]
### Firm Name

tCRIL

### Urgency

Medium

### Requested Change

Add frontend-app-learner-record with write access to the edx-transifex-translations team so the edx-transifex-bot can work correctly.

https://github.com/openedx/frontend-app-learner-record/issues/113

### Reasoning

This step was a necessary part of the transfer of this repo from the edx org to the openedx org. It has been causing failures, but this fix should be sufficient.

**Comment by Carlos-Muniz** [comment]
Write access to frontend-app-learner-record has been granted to the edx-transifex-translations team. This gives edx-transifex-bot the necessary permissions.

**Comment by Carlos-Muniz** [comment]
Adding Write access solved the problem, but now there is a new error.

```
16:22:42 Traceback (most recent call last):
16:22:42   File "transifex/pull.py", line 120, in <module>
16:22:42     pull(
16:22:42   File "transifex/pull.py", line 86, in pull
16:22:42     repo.merge_pr()
16:22:42   File "/edx/var/jenkins/jobs/translations/jobs/frontend-app-learner-record-pull_translations/workspace/ecommerce-scripts/transifex/utils.py", line 373, in merge_pr
16:22:42     raise RuntimeError('Pending status checks or other failure prevented this PR from being automatically merged')
16:22:42 RuntimeError: Pending status checks or other failure prevented this PR from being automatically merged
16:22:42 Build step 'Execute shell' marked build as failure
16:22:42 Archiving artifacts
16:22:42 Sending e-mails to: aperture@2u-internal.opsgenie.net
16:22:43 Finished: FAILURE
```
@hurtstotouchfire believes this setting may be the problem:
![image](https://user-images.githubusercontent.com/32077020/205127847-2c72cb88-223c-4e39-982e-2fe68fe88747.png)

**Comment by hurtstotouchfire** [comment]
We can follow up next week with full logs, thanks for looking into this.

**Comment by Carlos-Muniz** [comment]
Closing this ticket since this repo has the correct access. Debugging the reason why edx-transifex-bot/jenkins is unable to merge the pull request cannot be done by tcril.
