### ISSUE TITLE
[GH Request] Onboard jsnwesson

### ISSUE THREAD

**Issue by hurtstotouchfire** [openedx/tcril-engineering#568]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

* Jason Wesson, @jsnwesson

### Start Date

28 Nov 23

### Urgency

Medium

### Special Requests

Jason should also be added to @openedx/2u-aperture.

Sorry for the lack of notice, we're having some trouble determining which onboarding tasks IT will do and which the HM needs to do. Jason is not currently blocked though (he can always fork and PR), so access sometime next week would be great.

**Comment by Carlos-Muniz** [comment]
@jsnwesson has been added to the `openedx` organization, `openedx/push-pull-all` team, and the `openedx/2u-aperture` team. The invitations have been sent to their GitHub email.

@e0d will handle adding Jason to the CLA check database.

**Comment by e0d** [comment]
They will be in the batch this afternoon.
