### ISSUE TITLE
[GH Request] Onboard <a-asad>

### ISSUE THREAD

**Issue by kuche2U** [openedx/tcril-engineering#569]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

Ali Nawaz,, a-asad

### Start Date

02 December 2022

### Urgency

High Urgency

### Special Requests

ali.nawaz@arbisoft.com, anawaz@2u.com

**Comment by sarina** [comment]
@openedx/tcril-oncall automation's been broken, so manually pinging

**Comment by Carlos-Muniz** [comment]
@georgebabey can you verify that this request is legitimate?

**Comment by georgebabey** [comment]
@Carlos-Muniz approved.

**Comment by Carlos-Muniz** [comment]
@kuche2U Can you send the user profile for Ali Nawaz?

**Comment by kuche2U** [comment]
@Carlos-Muniz zawan-ila is the user profile

**Comment by Carlos-Muniz** [comment]
@zawan-ila has been added to the openedx GitHub organization. The invitation has been sent to their GitHub email. As part of the invitation, the user has been added to the push-pull-all team. The user has also been added to the CLA check database.
