### ISSUE TITLE
[GH Request] Onboard <@gregpeinke>

### ISSUE THREAD

**Issue by hmccauley** [openedx/tcril-engineering#570]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

user is Greg Peinke, username is @gregpeinke, 2U email is gpeinke@2u.com

### Start Date

2 December 2022

### Urgency

Medium Urgency - end of next calendar week would be fine

**Comment by Carlos-Muniz** [comment]
@georgebabey can you verify that this request is legitimate?

**Comment by georgebabey** [comment]
Approved

**Comment by Carlos-Muniz** [comment]
@Gregpeinke has been added to the openedx GitHub organization. The invitation has been sent to their GitHub email. As part of the invitation, the user has been added to the `push-pull-all` team.

**Comment by Carlos-Muniz** [comment]
@e0d This user needs to be added to the CLA check database.

**Comment by Carlos-Muniz** [comment]
Greg has been added to the CLA Check Database
