### ISSUE TITLE
[GH Request] Onboard jesperhodge

### ISSUE THREAD

**Issue by jristau1984** [openedx/tcril-engineering#573]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

Name: Jesper Hodge
Github id: jesperhodge

### Start Date

December 12, 2022

### Urgency

Medium Urgency (resolve in <two weeks)

**Comment by Carlos-Muniz** [comment]
@jesperhodge has been added to the openedx GitHub organization. The invitation has been sent to their GitHub email. As part of the invitation, the user has been added to the push-pull-all team.

**Comment by Carlos-Muniz** [comment]
@e0d This user needs to be added to the CLA check database.

**Comment by e0d** [comment]
They will be in the batch this afternoon.

**Comment by jristau1984** [comment]
Thanks so much!
