### ISSUE TITLE
[GH Request] <GitHub EdX & GitHub Getsmarter>

### ISSUE THREAD

**Issue by mmnxumalo** [openedx/tcril-engineering#575]
### Firm Name

EdX & Getsmarter

### Urgency

High

### Requested Change

Not sure what the process looks like, but can we get the members of the
following github teams on the 2U Inc. org added to edX and GetSmarter
Github Organizations please?

* https://github.com/orgs/2uinc/teams/admissions-systems/members
* https://github.com/orgs/2uinc/teams/platform-systems/members

We don't need write access to anything at this time, read only access to
the organization is fine too.

Users: 
- Praveen Balachandar
- drowe@2u.com (nigelfloe)
- jkaye@2u.com (jkaye31)
- akang@2u.com (akang2u)
- cjunker@2u.com (cjunks94)
-  dlang@2u.com (DonLang)

### Reasoning

We're starting to work on projects that span across multiple LOBs and
having access to the private repositories of edX and GetSmarter would be
great for us.

**Comment by Carlos-Muniz** [comment]
@mmnxumalo Hello! I think you may have made requests here in error. This GitHub Request system is for the openedx GitHub organization. I cannot add those github teams on the 2U Inc. org (I can't see them as they are private) to the edX and GetSmarter Github Organizations.
