### ISSUE TITLE
[GH Request] Moving the repository containing the Kubernetes/Helm deployment support

### ISSUE THREAD

**Issue by antoviaque** [openedx/tcril-engineering#577]
### Firm Name

OpenCraft

### Urgency

Within a week if possible? It would help to clarify that this isn't an OpenCraft project, but a collaborative community-based one

### Problem/Request

To help making it clear that we intend to do the project described by https://github.com/openedx/open-edx-proposals/pull/372 as a shared collaborative effort within the framework of the Open edX project, it would be useful to move the [repository containing the code & tasks list](https://github.com/open-craft/tutor-contrib-multi) to the github openedx organization - would it be possible to do this now?

See:
* https://github.com/openedx/open-edx-proposals/pull/372#issuecomment-1341552893 
* https://discuss.openedx.org/t/deploying-open-edx-on-kubernetes-using-helm/8771
* https://discuss.openedx.org/t/tech-talk-demo-deploying-multiple-open-edx-instances-onto-a-kubernetes-cluster-with-tutor/4641

### Reasoning

I've mentioned the reasoning in the previous field, but let me know if you need any additional detail about it, or the initiative in general.

**Comment by Carlos-Muniz** [comment]
Thank you for the request @antoviaque. We are currently reviewing the request with our legal team and will get back with the next steps.

**Comment by Carlos-Muniz** [comment]
Hello @antoviaque! Thank you for your patience. We have reviewed [open-craft/tutor-contrib-multi](https://github.com/open-craft/tutor-contrib-multi), and under the Entity CLA with OpenCraft and your clear expression of intent to contribute the repository in this ticket, that is all we need to accept this contribution. I will send you a private message with the next steps we will take to bring this repository into the openedx GitHub organization.

**Comment by antoviaque** [comment]
@Carlos-Muniz Thank you @Carlos-Muniz ! I've followed the steps from your message, hopefully you should now be able to move the repo. :) Don't hesitate if you need anything else in the process.

**Comment by Carlos-Muniz** [comment]
tutor-contrib-multi is now part of the openedx GitHub organization. To ease the transition, @antoviaque, @regisb, @felipemontoya, and @jfavellar have been added to a new openedx team called tutor-contrib-multi and have maintained their write access. All other outside collaborators in that repository no longer have write access to the repo. 

@antoviaque Please let me know if anyone else should also have write access, and if there is anything else needed.

**Comment by antoviaque** [comment]
@Carlos-Muniz Thank you! :+1: 

For the write access, the aim was to have all outside collaborators originally listed on the OpenCraft repo having access to it like @lpm0073 @MoisesGSalas , plus the OpenCraft folks who had access to it via our org (in particular, @bradenmacdonald @keithgg @mtyaka & the OpenCraft core contributors in general). 

I'm guessing that you didn't keep the access for the people who weren't already core contributors? If you want I can create a dedicated ticket for discussing this.

**Comment by Carlos-Muniz** [comment]
@antoviaque 
After discussing with the tCRIL team we've come to the conclusion that contributors (OpenCraft + outside collaborators) to openedx/tutor-contrib-multi should [follow the OEP-54 instructions](https://open-edx-proposals.readthedocs.io/en/latest/processes/oep-0054-core-contributors.html#adding-new-core-contributors) for adding new CCs or expanding the rights of existing CCs. [Here](https://discuss.openedx.org/t/core-contributor-nomination-maria-grimaldi/6548) is an example  for nominating a new CC and [here](https://discuss.openedx.org/t/coding-cc-rights-expansion-piotr-surowiec/6958) is an example for expanding rights of an existing one. 
In addition, the openedx team tutor-contrib-multi with write access to the tutor-contrib-multi repository has been deleted in favor of the Core Contributor program.

**Comment by antoviaque** [comment]
@Carlos-Muniz That makes sense - thank you for looking into it. We'll follow-up on this point in https://github.com/openedx/tutor-contrib-multi/issues/9
