### ISSUE TITLE
[GH Request] New enterprise-related repos

### ISSUE THREAD

**Issue by iloveagent57** [openedx/tcril-engineering#585]
### Firm Name

2U

### Urgency

Medium, a few business days or so?

### Problem/Request

Please create 3 new repos related to the edX Enterprise ecosystem.

Name: edx-ledger
Visibility: Public
Summary: A library that records transactions against a ledger, denominated in units of value.
Organization: openedx
Permissions:
Push: https://github.com/orgs/openedx/teams/business-enterprise-team
Pull: Anyone in the openedx org (push-pull-all, I guess?)
Default branch name: main 
Protected Branch: yes
License: We'll turn on the AGPL license by default, as per Open Source's policy. Please check with Open Source if you want another policy.
Description: This library provides a transaction-based system of record, capturing and balancing the usage of value denominated in some unit.

Name: edx-enterprise-subsidy
Visibility: Public
Summary: Captures and balances enterprise-subsidized transactions.
Organization: openedx
Permissions:
Push: https://github.com/orgs/openedx/teams/business-enterprise-team
Pull: Anyone in the openedx org (push-pull-all, I guess?)
Default branch name: main 
Protected Branch: yes
License: We'll turn on the AGPL license by default, as per Open Source's policy. Please check with Open Source if you want another policy.
Description: This service provides a transaction-based system of record, capturing and balancing the usage of value toward learning content for enterprise learners.

Name: edx-enterprise-subsidy-client
Visibility: Public
Summary: Client for making requests to edx-enterprise-subsidy.
Organization: openedx
Permissions:
Push: https://github.com/orgs/openedx/teams/business-enterprise-team
Pull: Anyone in the openedx org (push-pull-all, I guess?)
Default branch name: main 
Protected Branch: yes
License: We'll turn on the AGPL license by default, as per Open Source's policy. Please check with Open Source if you want another policy.
Description: A REST client for consistent API-based communication with the edx-enterprise-subsidy service.

### Reasoning

* ecommerce Enterprise Offers are deprecated, and this is the replacement for them.
* so that we can accurately account for usage across the enterprise system.

**Comment by arbrandes** [comment]
@iloveagent57, ACKing the request.  We're looking into it!

**Comment by arbrandes** [comment]
@iloveagent57, I believe Ed got in touch with regarding the possibility of renaming `edx-ledger` to `openedx-ledger`?

Ideally, the enterprise repos would be similarly renamed, but that doesn't make much sense unless `edx-enterprise` itself is renamed, and I'm not sure we want to embark on that mission just yet.

**Comment by iloveagent57** [comment]
Hey @arbrandes yup, `openedx-ledger` works great for the repo name.  
Renaming `edx-enterprise-subsidy` to `openedx-enterprise-subsidy` would also be fine, although I agree it's inconsistent with some other existing enterprise repos.

The 2u Enterprise team talked a little bit about this - naming the subsidy repos something like `openedx-subsidy` (without the word "enterprise" in it) could also work.  We could design our models within that repo so that there's some base Subsidy and related models, and then perhaps a Django app that defines an enterprise-specific implemenation.  So something like:
```python
# file openedx_subsidy.apps.base

class Subsidy(models.Model):
    pass  # fields and such...
```

```python
# file openedx_subsidy.apps.enterprise

class EnterpriseSubsidy(Subsidy):
   pass # enterprise-specific fields and methods here...
```
Let me know if you think there's any utility in that, happy to discuss further.

**Comment by arbrandes** [comment]
I don't think it's necessary to go through the model contortions just for this.  :)  At least not yet.

Anyway, here they are:

* https://github.com/openedx/openedx-ledger
* https://github.com/openedx/edx-enterprise-subsidy
* https://github.com/openedx/edx-enterprise-subsidy-client

AGPLed but otherwise empty, and added to `@openedx/push-pull-all`.

**Comment by kdmccormick** [comment]
FYI @arbrandes `push-pull-all` had been given only Read access to those three repos. I just upped it to Write access.
