### ISSUE TITLE
[GH Request] Spam to be deleted from Confluence

### ISSUE THREAD

**Issue by robrap** [openedx/tcril-engineering#587]
### Firm Name

2U

### Urgency

Medium

### Problem/Request

Please delete https://openedx.atlassian.net/wiki/spaces/AC/pages/3608969217/How+to+Save+Money+on+Eyelash+Boxes+Cardboard and block user.

### Reasoning

Self-evident.

**Comment by arbrandes** [comment]
Thanks @robrap!  Deleted.

We're investigating ways to minimize spam, and will let the community know once there's a reasonable plan (read: a decent trade-off between filtering power and convenience).
