### ISSUE TITLE
[GH Request] Onboard @jesperhodge

### ISSUE THREAD

**Issue by connorhaugh** [openedx/tcril-engineering#588]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

@jesperhodge

### Start Date

12/14/2022

### Urgency

Medium urgency -- done before the new year would be ideal.

**Comment by arbrandes** [comment]
Hi @connorhaugh!  I'll take care of this early tomorrow.

**Comment by arbrandes** [comment]
Looks like they're already in!  Added 10 days ago, it seems.  @connorhaugh, feel free to reopen if there's something missing.
