### ISSUE TITLE
[GH Request] Move Repos from 2U to Openedx

### ISSUE THREAD

**Issue by feanil** [openedx/tcril-engineering#591]
### Firm Name

tCRIL

### Urgency

Medium

### Requested Change

The following repos are in the `edx` Org but also part of the Open edX Releases.  They should be transferred to the Open edX org.

@nedbat can you confirm as the representative from 2U?

#### Repos in Question

- edx/enterprise-access
- edx/frontend-app-communications
- edx/frontend-app-learner-dashboard
- edx/frontend-app-ora-grading
- edx/testeng-ci

### Reasoning

Since these repos are tagged in the Open edX release and in most cases these are installed as a part of the default build of the Open edX Platform.

testeng-ci is not needed for running the platform but contains the code we use to make PRs and do routine maintenance tasks no the platform and is heavily used by github actions across the openedx codebase.

**Comment by nedbat** [comment]
I agree that these five repos should move to the openedx GitHub organization.

**Comment by georgebabey** [comment]
Also agreeing here - lets get these moved over.

**Comment by feanil** [comment]
Great, I'll work with Ned to move this over under the 2U-tCRIL license and contributions agreements.

**Comment by feanil** [comment]
All the above named  repositories have been transferred.
