### ISSUE TITLE
[GH Request] Expand Carlos-Muniz CC Rights 

### ISSUE THREAD

**Issue by Carlos-Muniz** [openedx/tcril-engineering#592]
### Firm Name

tCRIL

### User List (case sensitive!) - Please also include in ticket title

Carlos Muniz, @Carlos-Muniz 

### Start Date

N/A

### Urgency

Low

### Special Requests

Please expand my CC Rights to include:
[openedx-atlas](https://github.com/openedx/openedx-atlas), [openedx-translations](https://github.com/openedx/openedx-translations), [docs.openedx.org](https://github.com/openedx/docs.openedx.org), and [openedx-webhooks](https://github.com/openedx/openedx-webhooks).

See [this forum post](https://discuss.openedx.org/t/coding-cc-rights-expansion-carlos-muniz/8862) for more details.

**Comment by arbrandes** [comment]
Added repos [to the list](https://openedx.atlassian.net/wiki/pages/diffpagesbyversion.action?pageId=3156344833&selectedPageVersions=61&selectedPageVersions=60).  Since Carlos is already org admin, no actual permissions changes were necessary.

**Comment by Carlos-Muniz** [comment]
My repos in the openedx team [CCP Committer: Carlos-Muniz](https://github.com/orgs/openedx/teams/ccp-committer-carlos-muniz) were not updated.

**Comment by feanil** [comment]
This should be all set, I've updated Carlos' CCP Team.
