### ISSUE TITLE
[GH Request] - Add new members to discovery and publisher maintainers group

### ISSUE THREAD

**Issue by kashifch** [openedx/tcril-engineering#598]
### Firm Name

2U

### Urgency

urgent - we are blocked on some tickets due to access issues

### Requested Change

We need Ali Nawaz(zawan-ila) and Afaq(AfaqShuaib09)  to be members of @openedx/course-discovery-maintainer and @openedx/frontend-app-publisher-maintainers.

### Reasoning

Ali Nawaz(zawan-ila) and Afaq(AfaqShuaib09) have recently joined the Phoenix squad as engineers. As our squad owns the Discovery and Publisher we need them to be able to make changes

**Comment by arbrandes** [comment]
Done!  Both were invited to both teams.
