### ISSUE TITLE
[GH Request] Leaving CC program on December 27

### ISSUE THREAD

**Issue by giovannicimolin** [openedx/tcril-engineering#600]
### Firm Name

OpenCraft

### Urgency

December 28th

### Requested Change

Remove write permission for user `giovannicimolin` (me) from Open edX/2U repos.

### Reasoning

I'm leaving the CC program on December 27, and from that date onwards I'll just be a regular community member.

Open edX slack announcement: https://openedx.slack.com/archives/C015KC8CN76/p1671733565280989

**Comment by giovannicimolin** [comment]
@sarina As per offboarding procedures on https://openedx.atlassian.net/wiki/spaces/COMM/pages/3358261582/Core+Contributor+Offboarding+Runbook

**Comment by sarina** [comment]
Done! Thanks again for everything, @giovannicimolin !
