### ISSUE TITLE
[GH Request] Archive private channel

### ISSUE THREAD

**Issue by atrepca** [openedx/tcril-engineering#603]
### Firm Name

2U

### Urgency

Med urgency - by end of next week is fine

### Problem/Request

Hi,

Please archive the private channel `aws-and-edx` in the `openedx` Slack workspace.

Thanks,
Alex Trepca

### Reasoning

It was moved to a different Slack workspace and is not needed anymore.

**Comment by feanil** [comment]
@atrepca please invite me to the channel so that I can archive it.

**Comment by atrepca** [comment]
Done, thanks. Can you also please remove access from the `openedx` Slack workspace for the AWS people we invited: Andrew Chen, Fernando Ibanez, Leonora Steger and Wes Carver?

**Comment by feanil** [comment]
Channel archived.  For the users, they're just standard openedx slack workspace members so they can leave that workspace themselves.

**Comment by atrepca** [comment]
Great, thanks @feanil!
