### ISSUE TITLE
[GH Request] Onboard <dnuzz, purna2U>

### ISSUE THREAD

**Issue by kmedina2u** [openedx/tcril-engineering#604]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

* Daniel Nuzzo-Mueller, @dnuzz
* Purna Shah, @purna2U

### Start Date

9 January 2023

### Urgency

Somewhat Urgent - done within the next week

### Special Requests

Daniel:
Personal email: dnuzzomueller@gmail.com
2U email: dnuzzo-mueller@2u.com

Purna:
Personal email: pvs25@cornell.edu
2U email: pshah@2u.com

**Comment by feanil** [comment]
@kmedina2u I'll take a look at this. @georgebabey can you confirm the request?

**Comment by georgebabey** [comment]
@feanil Confirmed both Purna and Daniel. Thank you.

**Comment by feanil** [comment]
They should have github invites.

@e0d can you please add these users to the CLA database.

**Comment by feanil** [comment]
The users have been added to the CLA database.  The change will take about a business day to sync to the CLA checker but this should otherwise be all set.
