### ISSUE TITLE
[GH Request] Onboard purna2U 

### ISSUE THREAD

**Issue by kuche2U** [openedx/tcril-engineering#607]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

<html>
<body>

Purna Shah
--

</body>
</html>[Purna Shah](https://2u-corp-hub.my.salesforce.com/0036f00003okygm)

### Start Date

09 January 2023

### Urgency

High Urgency

### Special Requests

Email: pshah@2u.com

**Comment by feanil** [comment]
@georgebabey can you confirm?

**Comment by georgebabey** [comment]
@feanil Approved. Thank you

**Comment by feanil** [comment]
oh wait, @kuche2U this is just a second request for the same person as in https://github.com/openedx/tcril-engineering/issues/604

Closing this request, I'll take care of both of those together and update https://github.com/openedx/tcril-engineering/issues/604 when I'm done.
