### ISSUE TITLE
Determine list of repositories that require python translations and repositories that require javascript translations

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/tcril-engineering#608]
- [x] Look through all repos

- [x] Characterize by python or javascript

- [x] Effort to integrate into new translations management system (easy, medium, hard)

- [x] Identify subset of repos that need further work

**Comment by Carlos-Muniz** [comment]
[List of Repos with categorization](https://docs.google.com/spreadsheets/d/1PmevMGcYKfDb0h78aaoqVPjETg-rvwfrs24nr9lDxJg/edit?usp=sharing)
