### ISSUE TITLE
Create contributor onboarding and training course(s)

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/tcril-engineering#61]
Goal: Improve the developer/contributor onboarding process with one or multiple courses that orient new contributors to the platform and provide basic how-to/tutorial guidance on getting started.

**Comment by jmakowski1123** [comment]
Sub-task under epic https://github.com/openedx/tcril-engineering/issues/41

**Comment by sarina** [comment]
Courses are being tracked here: https://github.com/orgs/openedx/projects/15
