### ISSUE TITLE
[GH Request] Adding the Kubernetes / large instances working group meeting to the community calendar

### ISSUE THREAD

**Issue by antoviaque** [openedx/tcril-engineering#617]
### Firm Name

OpenCraft

### Urgency

Within 1-2 weeks? The next meeting is on Jan 24th

### Problem/Request

So far the Kubernetes / Large Instances DevOps working group has been mostly informal, but as we are beginning to produce more concrete work (like https://github.com/openedx/tutor-contrib-multi/), we are looking at formalizing the group a bit more - starting with meeting more regularly, now every two weeks. We would like to publish the meeting on the community agenda - how could I add it there? (And update it when needed later on, as it contains the agenda?)

Also, as a secondary question (let me know if you prefer a dedicated ticket for it), what would be the steps needed to further formalize the working group - maybe as a subgroup of the new devops working group?

### Reasoning

These meetings are already published in the forums (see https://discuss.openedx.org/t/deploying-open-edx-on-kubernetes-using-helm/8771), but it would be useful to get that meeting on the community working groups agenda, to allow everyone using that shared agenda to see it easily there.

**Comment by feanil** [comment]
@antoviaque I've added you to the working group calendar so you can add the meeting onto it.  For more formalizing, I'd talk to the chair of the Devops group and then follow https://openedx.atlassian.net/wiki/spaces/COMM/pages/3621519401/How+to+Make+a+New+Working+Group to start up the working group.

**Comment by antoviaque** [comment]
@feanil Thank you! I seem to have been able to add the meeting to the shared calendar perfect.

And sounds good, I'll have a look at the steps, and we have already started discussing this with @regisb - we'll follow up in https://github.com/openedx/tutor-contrib-multi/issues/12 and during the upcoming meetings.
