### ISSUE TITLE
[GH Request] Accept Maintainer request for olxcleaner package on edX PyPI account

### ISSUE THREAD

**Issue by rgraber** [openedx/tcril-engineering#618]
### Firm Name

2U

### Urgency

As soon as convenient. Blocking some work.

### Problem/Request

Accept the contributor request from the owner of olxcleaner on the edx PyPI account.

### Reasoning

olxcleaner package was forked into edX project as the upstream package is no longer maintained. The owner is ready to give edX access to the original PyPI repository so that we can maintain the original repository on PyPI and make new releases to the same package name. See https://github.com/openedx/olxcleaner/pull/16 for more context.

**Comment by feanil** [comment]
@rgraber I don't see the pending invitation on the `edx` user in PyPI, can you confirm

**Comment by feanil** [comment]
I reached back out to that user on the above PR, waiting for them to respond.  It looks like their initial invite was months ago and is no longer visible.

**Comment by rgraber** [comment]
> @rgraber I don't see the pending invitation on the `edx` user in PyPI, can you confirm

I don't think I have the permission to see the invitation to the edx user

**Comment by feanil** [comment]
I've accepted the project and it is now owned by the new `openedx` pypi user.  We should now be able to release new versions of it from our fork.
