### ISSUE TITLE
[GH Request] Onboard <zblanchet, amber-dorst>

### ISSUE THREAD

**Issue by kmedina2u** [openedx/tcril-engineering#621]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

* Zachary Blanchet, @zblanchet
* Amber Dorst, @amber-dorst

### Start Date

23 January 2023

### Urgency

Somewhat Urgent - done within the next week

### Special Requests

Zachary Blanchet - zblanchet@2u.com, zblanchet@gmail.com
Amber Dorst - adorst@2u.com, ambelisa@gmail.com

**Comment by kdmccormick** [comment]
@georgebabey Can you confirm this request?

**Comment by kdmccormick** [comment]
@kmedina2u , I won't be able to do anything on this request until I get a thumbs up from @georgebabey .

**Comment by kmedina2u** [comment]
@kdmccormick No worries, I don't believe this request is very urgent

**Comment by georgebabey** [comment]
Confirmed both Amber and Zachary

**Comment by kdmccormick** [comment]
@amber-dorst and @zblanchet are both invited to the openedx org & push-pull-all team, and have been added to to the CLA database in Salesforce. Reopen this if there are are any issues. Welcome to the project!
