### ISSUE TITLE
[GH Request] Offboard Various Users from the openedx GitHub organization

### ISSUE THREAD

**Issue by sarina** [openedx/tcril-engineering#622]
### Firm Name

tCRIL

### Urgency

High

### Requested Change

The following users have been removed from the openedx GitHub organization:

@0x29a
@Agrendalath
@ahmed-zubair12
@andrewgwardwell
@boulevardofdef
@clemente
@ehuthmacher
@lgp171188
@markH-Docemus
@naeem91
@oliviaruizknott
@qasim-arbisoft
@shadinaif
@sophiainman
@thomty
@Toxicom
@usmanmurad
@viadanna
@viktorrusakov

### Reasoning

If you think this is in error, please open up an [Access request GitHub ticket](https://github.com/openedx/tcril-engineering/issues/new/choose). Explain the reason you need access. Currently only Core Contributors, tCRIL employees, and 2U employees are given repo write access. 

Please do not leave a comment, but instead open a new ticket for your own access. thank you!

**Comment by sarina** [comment]
If you think this is in error, please open up an [Access request GitHub ticket](https://github.com/openedx/tcril-engineering/issues/new/choose). Explain the reason you need access. Currently only Core Contributors, tCRIL employees, and 2U employees are given repo write access. 

Please do not leave a comment, but instead open a new ticket for your own access. thank you!

**Comment by sarina** [comment]
@Agrendalath apologies I made a mistake. You're still in the org with your CC permissions, but have been removed from the solutions group. I meant to message that separately.

**Comment by Agrendalath** [comment]
@sarina, no worries. Thanks for clarifying.
