### ISSUE TITLE
[GH Request] Access for Xavier Antoviaque

### ISSUE THREAD

**Issue by sarina** [openedx/tcril-engineering#623]
### Firm Name

tCRIL

### Urgency

High

### Requested Change

Hi @antoviaque, I've removed your write access to all repos. Please let me know which, if any, repositories you should retain triage access to.

### Reasoning

Principle of least privilege

**Comment by antoviaque** [comment]
@sarina Sure - I didn't even realize I still had write access on all repos; I couldn't do any triage on https://github.com/openedx/tutor-contrib-multi for example?

I'll have a look, also to answer you on https://github.com/openedx/tutor-contrib-multi/issues/9#issuecomment-1387229525 and let you know

**Comment by antoviaque** [comment]
@sarina Taking a closer look today, I think the only repos on which I currently do triage are:
* https://github.com/openedx/tutor-contrib-multi (for the DevOps Helm/Kubernetes/Large instances working group)
* https://github.com/openedx/wg-community (for the contributors meetup & checkins)
* https://github.com/openedx/open-edx-proposals/issues (for core contributors program topics)

There are other groups like product/roadmap & onboarding courses where I do some contributions, but currently nothing that requires me to triage so it's probably fine to skip them.

**Comment by sarina** [comment]
@antoviaque this is all set. I've added you to three triage teams: https://github.com/orgs/openedx/teams?query=%40antoviaque

Note I put another tutor-contrib repo in the Tutor triage group. I think it may make sense to group all Tutor repos in that triage group (for now - perhaps not if Tutor stuff becomes really disparate). Grouping them makes my life more sane and also encourages you to work across tutor projects if need be.
