### ISSUE TITLE
[GH Request] Access to confluence

### ISSUE THREAD

**Issue by pedromartello** [openedx/tcril-engineering#636]
### Firm Name

HammerLabs

### Urgency

This week

### Problem/Request

I would like to request contributor access to the openedx confluence for the Google account pedro@hammerlabs.net

### Reasoning

I am collaborating with Adolfo Brandes and Michelle Philbrick on FC-0007. I specifically need access to this page and subpages: 

https://openedx.atlassian.net/wiki/spaces/COMM/pages/3614900241/FC-0007+-+Modular+MFE+Domains+Discovery

**Comment by feanil** [comment]
Hi @pedromartello you should have an invite to confluence in your inbox now.
