### ISSUE TITLE
[GH Request] AWS account access for Brian Mesick

### ISSUE THREAD

**Issue by bmtcril** [openedx/tcril-engineering#638]
### Firm Name

tCRIL

### Urgency

Low urgency - within 2 wks is fine

### Requested Change

Hello, I need an AWS account to be able to run terraform plan, my e-mail address is <bmesick@tcril.org>. 

Tagging my manager @sarina for visibility.

### Reasoning

Specifically this is for standing up an OARS environment / community playground during development. I have a fair amount of Terraform experience, though most of it is in managing Snowflake.

**Comment by sarina** [comment]
:approved:

**Comment by kdmccormick** [comment]
Currently working on getting access to both AWS and Cloudflare myself.

**Comment by kdmccormick** [comment]
Alright, I'm in AWS, but I don't seem to have access to invite users.

@e0d , can you also add Brian to AWS?

**Comment by e0d** [comment]
Please create a PR to terraform:

https://github.com/openedx/terraform-internal/blob/main/opensource/iam.tf

**Comment by kdmccormick** [comment]
https://github.com/openedx/terraform-internal/pull/31

**Comment by kdmccormick** [comment]
FYI @brian-smith-tcril --  I created a PR against terraform-internal to give Brian M access to AWS, using the previous commit (Dave's AWS access PR) as a template. While I was there, I removed Carlos's access.

As far as I can tell, we don't have automated planning  & execution set up for Terraform yet, so we'll need Ed or Feanil to run and merge that PR for us.
