### ISSUE TITLE
[GH Request] Cloudflare access for Brian Mesick

### ISSUE THREAD

**Issue by bmtcril** [openedx/tcril-engineering#639]
### Firm Name

tCRIL

### Urgency

Low urgency - within 2 wks is fine

### Requested Change

In addition to the permissions for #638 it seems like I will also need Cloudflare credentials to run Terraform. At least according to this: https://github.com/openedx/terraform-internal

Tagging my manager @sarina 

### Reasoning

I'm guessing there are some Cloudflare resources that get touched via Terraform and therefore everyone running a plan needs these perms? 🤷‍♂️

**Comment by kdmccormick** [comment]
Taking a look.

**Comment by kdmccormick** [comment]
I have an account now, but I don't think have the access rights to add Brian.

@e0d , could you either add Brian to CF, or elevate my privileges so I can do so?

**Comment by e0d** [comment]
Done.

**Comment by kdmccormick** [comment]
Thanks!
