### ISSUE TITLE
[GH Request] Onboard roybrown-trilogyed

### ISSUE THREAD

**Issue by jsoto2u** [openedx/tcril-engineering#640]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

Roy Brown(https://2u-corp-hub.my.salesforce.com/0030f000035mDRD)

### Start Date

01/19/2023

### Urgency

High Urgency

### Special Requests

Email: [rbrown1@2u.com](mailto:rbrown1@2u.com)

**Comment by kdmccormick** [comment]
@jsoto2u Can you provide their GitHub username?

@georgebabey , can you confirm that this is a new edX engineer?

**Comment by jsoto2u** [comment]
@kdmccormick Github username is roybrown-trilogyed

Put it in the title but forgot to put it in the body

**Comment by georgebabey** [comment]
Confirmed

**Comment by kdmccormick** [comment]
@roybrown-trilogyed is invited to the openedx org & push-pull-all team, and has been added to Salesforce. Reopen this if there are are any issues. Welcome to the project!
