### ISSUE TITLE
[GH Request] Offboard Carlos-Muniz

### ISSUE THREAD

**Issue by Carlos-Muniz** [openedx/tcril-engineering#641]
### Firm Name

tCRIL

### User List  (case sensitive!) - Please also include in ticket title

@Carlos-Muniz - Core Contributor

### End Date

2023-01-31

### Urgency

Medium

**Comment by kdmccormick** [comment]
@brian-smith-tcril I'll leave this to you, assuming you're still slated for on-call next week.

**Comment by kdmccormick** [comment]
@brian-smith-tcril 's on call starting next week, so I'll take this one back.

**Comment by kdmccormick** [comment]
AWS access will be revoked here: https://github.com/openedx/terraform-internal/pull/31

**Comment by Carlos-Muniz** [comment]
Removed myself from the @openedx-unsupported org

**Comment by kdmccormick** [comment]
I updated Carlos's Salesforce entry per https://openedx.atlassian.net/wiki/spaces/COMM/pages/3438903337/On-call+Playbooks#Adding%2FRemoving-A-New-Entity-Contributor. Looks like Sarina already removed him from the openedx GH org.

Closing this now, Sarina will handle anything tCRIL-specific over in https://github.com/openedx/tcril-engineering/issues/648.

cc @brian-smith-tcril
