### ISSUE TITLE
[GH Request] Cross-post DEPR announcements made in Discourse

### ISSUE THREAD

**Issue by dianakhuang** [openedx/tcril-engineering#642]
### Firm Name

2U

### Urgency

Low - whenever someone has time

### Problem/Request

We would like have the Slack integration auto-post any announcements made in the [Deprecation announcements section on Discourse](https://discuss.openedx.org/c/announcements/deprecation/20) to be also announced in the \#general and \#open-edx-proposals as recommended in the [deprecation OEP](https://open-edx-proposals.readthedocs.io/en/latest/processes/oep-0021-proc-deprecation.html).

### Reasoning

This will automate the process of announcing new deprecation proposals and reduce the amount of work for the person proposing new deprecations.

**Comment by kdmccormick** [comment]
@feanil do you mind taking this one on?

**Comment by feanil** [comment]
This should be all set.
