### ISSUE TITLE
[GH Request] Please correct purna2U

### ISSUE THREAD

**Issue by nedbat** [openedx/tcril-engineering#644]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

In #604, purna2U was mis-capitalized as purna2u, which is preventing a match.

### Start Date

9 January 2023

### Urgency

This week please

**Comment by kdmccormick** [comment]
@nedbat I corrected Purna's username capitalization in Salesforce. Let me know if it needs to be fixed anywhere else.
