### ISSUE TITLE
[GH Request] Offboard Carlos-Muniz

### ISSUE THREAD

**Issue by sarina** [openedx/tcril-engineering#648]
### Firm Name

tcril

### User List  (case sensitive!) - Please also include in ticket title

* Carlos Muniz, Carlos-Muniz

### End Date

31 Jan 2023

### Urgency

ASAP - offboarding

**Comment by sarina** [comment]
I removed Carlos from the github org, I will do the rest this week.

**Comment by kdmccormick** [comment]
Per https://github.com/openedx/tcril-engineering/issues/641 , I've updated Carlos's [Salesforce entry](https://tcril.lightning.force.com/lightning/r/Contact/0035f00000CIeXFAA1/view).
