### ISSUE TITLE
[GH Request] Onboard <ilee2u>

### ISSUE THREAD

**Issue by Vhenry7** [openedx/tcril-engineering#659]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

Isaac Lee, @ilee2u

### Start Date

06 February 2023 

### Urgency

High urgency - tomorrow

### Special Requests

ilee@2u.com

**Comment by brian-smith-tcril** [comment]
I have:
- [x] Added @ilee2u as a member of the [Open edX GH org](https://github.com/openedx)
- [x] Added @ilee2u as a member of the [push-pull-all team](https://github.com/orgs/openedx/teams/push-pull-all/)
- [x] Added Isaac Lee to the CLA database on Salesforce
