### ISSUE TITLE
[GH Request] Move OARS repos from open-craft to openedx

### ISSUE THREAD

**Issue by pomegranited** [openedx/tcril-engineering#660]
### Firm Name

OpenCraft

### Urgency

Low urgency

### Requested Change

Could you please move these repos into the openedx org?

* https://github.com/open-craft/tutor-contrib-superset
* https://github.com/open-craft/tutor-contrib-oars

### Reasoning

These repos will be part of the supported OARS suite of plugins, and so they should be part of the Open edX community repos.

CC @bmtcril

**Comment by pomegranited** [comment]
@antonviaque Could you approve this request, in case we need another voice from OpenCraft?

**Comment by pomegranited** [comment]
@antoviaque Could you approve this request, in case we need another voice from OpenCraft?

**Comment by pomegranited** [comment]
FYI @bmtcril, there should be invitations in your inbox to Admin these repos now.

**Comment by antoviaque** [comment]
@pomegranited Yup, all good on my side. :+1: Let me know if there is anything specific I need to do besides commenting here. :)

**Comment by bmtcril** [comment]
Thanks all! These have been moved over and write access granted to the CC Analytics group, so you may not have access until I update your perms after comments close on your thread tomorrow.

**Comment by pomegranited** [comment]
Hooray! Thank you @bmtcril and @antoviaque for getting this done so quickly!
