### ISSUE TITLE
[GH Request] Rename tutor-contrib-multi to openedx-k8s-harmony

### ISSUE THREAD

**Issue by bradenmacdonald** [openedx/tcril-engineering#661]
### Firm Name

OpenCraft

### Urgency

Low urgency

### Problem/Request

Per https://github.com/openedx/tutor-contrib-multi/issues/5 we have decided that the repo https://github.com/openedx/tutor-contrib-multi/ needs a new name, and we've decided on `openedx-k8s-harmony`.

Could you please rename the repo for us, as we don't seem to have permission.

### Reasoning

The repo is more specific to Open edX and to Kubernetes than it is to Tutor.

**Comment by bradenmacdonald** [comment]
I forgot to mention this but could you please also edit the "About" section on the right side of the repo's home page on GitHub to remove the part that says "Needs a new name :)"

**Comment by brian-smith-tcril** [comment]
Complete! https://github.com/openedx/openedx-k8s-harmony

**Comment by bradenmacdonald** [comment]
Awesome, thanks @brian-smith-tcril !
