### ISSUE TITLE
[GH Request] Create group to manage CC access to openedx-k8s-harmony

### ISSUE THREAD

**Issue by felipemontoya** [openedx/tcril-engineering#665]
### Firm Name

eduNEXT

### Urgency

Medium (< 2 weeks)

### Requested Change

I would like for tCRIL to create a group for the proper maintenance and stewardship of the [`openedx-k8s-harmony`](https://github.com/openedx/openedx-k8s-harmony) project.

This group should have `maintain` permission on the `openedx-k8s-harmony` repo. The group members would be @bradenmacdonald and me (@felipemontoya). Both of us are core contributors so this should not have problems from the legal standpoint. When the times comes we will use the process of oep-54 to extend permissions to other members. 

### Reasoning

This project used to be called `tutor-contrib-multi` but that was a temporal name and now the definitive one is in place.

Previously this was discussed at:
https://github.com/openedx/tcril-engineering/issues/577

And more recently:
https://github.com/openedx/openedx-k8s-harmony/issues/9

However it looks like we tried adding people that were not core commiters and this further complicated everything. It should not be the case this time around.

Thanks a bunch

**Comment by brian-smith-tcril** [comment]
@felipemontoya @bradenmacdonald I have invited you to be members of the newly created [openedx-k8s-harmony-maintainers](https://github.com/orgs/openedx/teams/openedx-k8s-harmony-maintainers) team.

I have given that team the **Maintain** role on the [openedx-k8s-harmony](https://github.com/openedx/openedx-k8s-harmony) repo.

**Comment by bradenmacdonald** [comment]
Thanks @brian-smith-tcril !
