### ISSUE TITLE
Set up mail for training.openedx.org

### ISSUE THREAD

**Issue by sarina** [openedx/tcril-engineering#666]
From eduNEXT:

Attached you will find a guide to verify the domain [mg.tcrill.org](http://mg.tcrill.org/), which is the first step to authenticating emails sent by the platform.

Once you finish the configuration, we will update our SMTP settings and verify if further changes are needed. We recommend adding the following SPF records:

 include:[mailgun.org](http://mailgun.org/) ~all

[InstructionsFromeduNEXT.pdf](https://github.com/openedx/tcril-engineering/files/10726529/Sending_.Overview.-.Mailgun.pdf)

**Comment by feanil** [comment]
https://github.com/openedx/terraform-internal/pull/33 should create the necessary records based on the instructions.

**Comment by sarina** [comment]
Created a support ticket w/ eduNEXT

**Comment by sarina** [comment]
Done - I made a new test account and can verify the activation email was delivered to my inbox and looked correct.
