### ISSUE TITLE
[GH Request] Onboard krishatcher

### ISSUE THREAD

**Issue by krishatcher** [openedx/tcril-engineering#667]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

Kris Hatcher @krishatcher

### Start Date

1 March 2023

### Urgency

Low (2 weeks)

**Comment by drogerstrilogy** [comment]
this is approved

**Comment by brian-smith-tcril** [comment]
I have:
- [x] Added @krishatcher as a member of the [Open edX GH org](https://github.com/openedx)
- [x] Added @krishatcher as a member of the [push-pull-all team](https://github.com/orgs/openedx/teams/push-pull-all/)
- [x] Added Kris Hatcher to the CLA database on Salesforce

**Comment by brian-smith-tcril** [comment]
@drogerstrilogy, it appears you are not in Salesforce as someone who can approve onboarding requests.
* @georgebabey can you confirm that it's ok for them to do this and for us to complete this request?
* If so, @drogerstrilogy can you send your own name and email address so we can add you to the list?
