### ISSUE TITLE
[GH Request] Onboard Syed-Ali-Abbas-Zaidi

### ISSUE THREAD

**Issue by jmbowman** [openedx/tcril-engineering#669]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

* Syed Ali Abbas Zaidi, @Syed-Ali-Abbas-Zaidi

### Start Date

8 February 2023

### Urgency

High (< 3 days)

### Special Requests

Please also add him to @openedx/fed-bom .

**Comment by brian-smith-tcril** [comment]
I have:
- [x] Added @Syed-Ali-Abbas-Zaidi as a member of the [Open edX GH org](https://github.com/openedx)
- [x] Added @Syed-Ali-Abbas-Zaidi as a member of the [push-pull-all team](https://github.com/orgs/openedx/teams/push-pull-all/)
- [x] Added @Syed-Ali-Abbas-Zaidi as a member of the [fed-bom team](https://github.com/orgs/openedx/teams/fed-bom)
- [x] Added Syed Ali Abbas Zaidi to the CLA database on Salesforce

**Comment by Syed-Ali-Abbas-Zaidi** [comment]
Hi @brian-smith-tcril, CLA check is still failing on my PR's.
