### ISSUE TITLE
Represent current Tutor backlog on new Tutor project board

### ISSUE THREAD

**Issue by kdmccormick** [openedx/tcril-engineering#67]
Most of the issues in this ~epic~ project will relate to the overhangio/tutor repository. We could create the issues in overhangio/tutor, and then reference them from the [new project board](https://github.com/orgs/openedx/projects/10/views/1). We could then create [milestones](https://github.com/overhangio/tutor/milestones) in the overhangio/tutor repo to group the issues into deliverable goals.

**Comment by kdmccormick** [comment]
@regisb, what do you think? Are you OK with Tutor issues being used that way?

**Comment by regisb** [comment]
What epic are you referring to? It seems to me that many of the issues relate to the CourseGraph plugin, and should thus be created in that repository.
I'm not a big fan of opening many GitHub issues in the core Tutor repo. I would prefer if we discussed eventual improvements and bugs in the forum prior to moving the conversation to GitHub -- well at least that's been my workflow so far. But I'm open to suggestions.

**Comment by kdmccormick** [comment]
@regisb Sorry, I didn't do a great job with that issue description. I am referring to [this backlog](https://docs.google.com/spreadsheets/d/12MxCu6Z3lzbF8Z6t2B39y73r65PjiwPnvwb3gHkkKD8/edit#gid=0).

The CourseGraph plugin issues will stay in the tutor-coursegraph repository. 

> I'm not a big fan of opening many GitHub issues in the core Tutor repo.

I am sensitive to that. Mostly, I want us to have a way to propose, discuss, and track project tasks without working in a restricted-visibility google sheet. The forum is a great place for discussion, but it doesn't lend itself to task tracking.

**Comment by regisb** [comment]
> Mostly, I want us to have a way to propose, discuss, and track project tasks without working in a restricted-visibility google sheet. The forum is a great place for discussion, but it doesn't lend itself to task tracking.

Right. I can certainly create a new GitHub beta project where we can discuss the roadmap: https://github.com/orgs/overhangio/projects/2/views/1
The good thing with such a project is that items do not have to be associated with actual issues.

**Comment by kdmccormick** [comment]
> The good thing with such a project is that items do not have to be associated with actual issues.

Good point.

The only problem with draft (no-issue) project cards is that are siloed to that board. They wouldn't be cross-referencable from the [platform roadmap](https://github.com/orgs/openedx/projects/4/views/1) or [tCRIL's own engineering board](https://github.com/orgs/openedx/projects/8/).

Maybe we could use draft project cards for new/ungroomed items, but them convert them to proper issues when it's clear we understand them & agree that we want to work on them.

**Comment by kdmccormick** [comment]
> I think this is the right approach, yes. We must acknowledge that by picking GitHub as our principal project management system we will necessarily be lacking some features, such as inter-issue linking, fine-grained permissions, etc. We must make do with what we got, which very much goes against our (or at least: my) instinct as software engineers. But that's ok -- I'm fine with the fact that no issue tracking system is 100% satisfying. And I wouldn't choose to go back to a more feature-packed solution like Jira.

+1

> The approach that you picked at tCRIL is sensible: issues are created in a dedicated roadmap repo and listed in a GitHub (beta) project. We could probably use that same template with Tutor. That way we would get the best of both worlds: groomed per-repo issues and full-fledged issues for backlog tracking.

Excellent. Our product manager @jmakowski1123 and I just talked; here's our plan for tracking this project's progress (which'll hopefully be a model for Open edX initiatives going forward):
* Epics within the project will be represented as issues on [the platform roadmap](https://github.com/orgs/openedx/projects/4/views/1), allowing the community to get a birds-eye-view of the work in progress.
* Each epic itself will have a task list containing groomed stories. For example, I made a [tutor-coursegraph epic](https://github.com/openedx/platform-roadmap/issues/114) for myself. 
* Each groomed story will be an issue in the most relevant repo -- for this project, that'll be mostly the Tutor repo, but it might also involve edx-platform, devstack, tcril-engineering, etc. 
* Stories (groomed & ungroomed) will be pulled together and tracked on a project board, either [the one you made](https://github.com/orgs/overhangio/projects/2/views/1) or [the one I made](https://github.com/orgs/openedx/projects/10/views/1). Either of those boards works for me; let me know if you have a preference.
* Ungroomed stories will exist as draft issues on that project board.

Does that sound good to you?

**Comment by kdmccormick** [comment]
We settled on a variation of that ^, described here: https://openedx.atlassian.net/wiki/spaces/COMM/pages/3315335223/Tutor+Adoption+Initiative#Processes

**Comment by kdmccormick** [comment]
All old backlog tasks were imported here: https://github.com/orgs/openedx/projects/10/views/10
