### ISSUE TITLE
[Onboarding] <I WANTED TO ACCESS WIKI>

### ISSUE THREAD

**Issue by parvinkumarEdx** [openedx/tcril-engineering#671]
### Firm Name

SuccessLab 

### Urgency

Low (2 weeks)

### Problem/Request

I have done all research on which video player we can use with Edx and what features we must use in our video player for web and mobile apps so i would like to request you please grant me access to wiki. I am also attaching my input thread details for your reference. https://discuss.openedx.org/t/a-new-video-player-for-all-comments-requested-on-react-player-specs/9374/2

### Reasoning

i don't know how to apply for wiki access if i done anything wrong please help me so i will make this right.

**Comment by bmtcril** [comment]
Hi @parvinkumarEdx , sorry for the delay. If you add your email address here I can send you an invite to the wiki.

**Comment by parvinkumarEdx** [comment]
parvin.kumar154@gmail.com thank alot @bmtcril

**Comment by bmtcril** [comment]
Great, thank you. I've sent an invite to Confluence, let me know if you run into any issues!
