### ISSUE TITLE
[GH Request] Remove aht007 from arbi-bom GitHub team

### ISSUE THREAD

**Issue by jmbowman** [openedx/tcril-engineering#672]
### Firm Name

2U

### Urgency

Low (2 weeks)

### Requested Change

Please remove aht007 from the arbi-bom GitHub team (but not the org or the push-pull-all team).

### Reasoning

Ahtasham has transferred to another Arbisoft team working for 2U.  So he needs to retain all appropriate org access, I just want to save his inbox from being flooded by notifications no longer relevant to what he's now working on.

**Comment by brian-smith-tcril** [comment]
I do not see @aht007 in the [arbi-bom team](https://github.com/orgs/openedx/teams/arbi-bom). Just [django-multi-email-field-admin](https://github.com/orgs/openedx/teams/django-multi-email-field-admin), [push-pull-all](https://github.com/orgs/openedx/teams/push-pull-all), and [revenue-squad](https://github.com/orgs/openedx/teams/revenue-squad).

How would you like me to proceed?

**Comment by jmbowman** [comment]
Nothing left to do, I guess; could have sworn he was still in there when I looked, but maybe I either got it confused with the edx org or someone else made the change while adding him to revenue-squad.
