### ISSUE TITLE
[GH Request] Remove ishahroz from fed-bom team

### ISSUE THREAD

**Issue by jmbowman** [openedx/tcril-engineering#673]
### Firm Name

2U

### Urgency

Low (2 weeks)

### Requested Change

Please remove ishahroz from the fed-bom GitHub team (but not the org or the push-pull-all team).

### Reasoning

Shahroz has transferred to another Arbisoft team working for 2U. So he needs to retain all appropriate org access, I just want to save his inbox from being flooded by notifications no longer relevant to what he's now working on.

**Comment by brian-smith-tcril** [comment]
I have removed @ishahroz from the [fed-bom team](https://github.com/orgs/openedx/teams/fed-bom)
