### ISSUE TITLE
[GH Request] `SEMANTIC_RELEASE_NPM_TOKEN` secret exposed in a PR

### ISSUE THREAD

**Issue by adamstankiewicz** [openedx/tcril-engineering#674]
### Firm Name

2U

### Urgency

Urgent (< 3 days)

**🔔 Security / Product Delivery Risk 🔔**:

We exposed `SEMANTIC_RELEASE_NPM_TOKEN` which is used for publishing our JS libraries across Open edX to NPM. With it exposed, we _could_ run the risk of having bad actors publish to our `@edx`-namespaced NPM packages.

We are seemingly experiencing NPM authentication issues with the same token across multiple repos.

Example repos and libraries likely impacted (most of which are used by nearly all frontend applications across Open edX):
* https://github.com/openedx/paragon
* https://github.com/openedx/frontend-platform
* https://github.com/openedx/frontend-build
* https://github.com/openedx/eslint-conflig
* https://github.com/openedx/stylelint-config
* https://github.com/openedx/browserslist-config
* https://github.com/openedx/frontend-build
* https://github.com/openedx/frontend-lib-content-components
* https://github.com/openedx/frontend-component-header
* https://github.com/openedx/frontend-component-footer
* https://github.com/openedx/frontend-lib-special-exams
* https://github.com/openedx/frontend-component-cookie-policy-banner

(There may be others).

Engineers looking to contribute to these repos in support of their work will be blocked until the NPM authentication issue is resolved.

### Problem/Request

We have inadvertently exposed the `SEMANTIC_RELEASE_NPM_TOKEN` Github organization secret for `openedx` in a PR: https://github.com/openedx/frontend-enterprise/pull/300/files

My understanding is that `SEMANTIC_RELEASE_NPM_TOKEN` is a secret used for publishing all the JS libraries to NPM within the `openedx` github org whereby exposing it may be granting access to publish to our NPM packages.

It's also worth mentioning a related NPM authentication issue was filed automatically by semantic-release in the Paragon repo: https://github.com/openedx/paragon/issues/2058

Is this NPM token something tCRIL can help us rotate to a new one?

### Reasoning

We're hypothesizing somehow a bot picked up a NPM secret was exposed and made it unusable but we're not really sure how to explain the NPM auth issue with the token now.

For example, trying to authenticate locally with the exposed NPM token results in a 401 currently.

**Comment by feanil** [comment]
The exposed credential has been revoked but we have not made a new one to replace it yet.  NPM releases from the `openedx` org will be broken until that's resolved.

**Comment by feanil** [comment]
I've let the community know here: https://discuss.openedx.org/t/package-publishing-to-npm-temporarily-disabled/9389

**Comment by feanil** [comment]
We've replaced the token in the `openedx` org, this should be all set.  I'll leave this ticket open for a while to monitor and make sure the new token is working as expected.

Test before closing: Login to NPM and make sure the new token is being used.

**Comment by feanil** [comment]
I confirmed that this was used yesterday so we should be all set with this.
