### ISSUE TITLE
[GH Request] Edit permissions for labels on openedx/openedx-k8s-harmony

### ISSUE THREAD

**Issue by antoviaque** [openedx/tcril-engineering#675]
### Firm Name

OpenCraft

### Urgency

Low (2 weeks)

### Requested Change

I need to manually add the "good first issue" label to openedx/openedx-k8s-harmony, and be able to assign to tickets on that repository afterwards, to complete this task: https://github.com/openedx/openedx-k8s-harmony/issues/12#issuecomment-1432880626

### Reasoning

See https://github.com/openedx/terraform-github/issues/51#issuecomment-1432878444

**Comment by bmtcril** [comment]
I believe you already have triage access to this repo via the `tutor-repos-triage` group, so if you can't make that change you'll need to go through the CC process to get write access to the repo. In the meantime I've added the "good first issue 🎉 " label to unblock you. Let me know if you have any questions or issues!

**Comment by antoviaque** [comment]
@bmtcril Thank you for creating the label! I can set the labels, but not create or edit them - but for now that's probably good enough, and that got me unblocked. :) :+1:
