### ISSUE TITLE
[GH Request] Access to Wiki

### ISSUE THREAD

**Issue by erikmartus** [openedx/tcril-engineering#676]
### Firm Name

Medality

### Urgency

Low (2 weeks)

### Problem/Request

I am unable to comment/contribute to the wiki on Confluence without first logging in. When attempting to login with my existing Atlassian credentials (emartus@mrionline.com) I see a message that I do not have access to Confluence on openedx.atlassian.net. Following a comment from Sarina on the [discussion board](https://discuss.openedx.org/t/a-new-video-player-for-all-comments-requested-on-react-player-specs/9374/3?u=emartus) I am opening a ticket here to request access.

### Reasoning

Having recently worked on implementing a custom video player for our MFE with videojs, I would like to contribute to the discussion of improving the edX video player.

**Comment by bmtcril** [comment]
Hi @erikmartus , I've added mrionline.com to our allowed list of domains so you and anyone from your org should be able to sign up now. Please let me know if you have any issues.

**Comment by erikmartus** [comment]
@bmtcril thank you! I was able to sign up.
