### ISSUE TITLE
[GH Request] Onboard <gabew1984>

### ISSUE THREAD

**Issue by gabew1984** [openedx/tcril-engineering#678]
### Firm Name

edX/2U

### User List (case sensitive!) - Please also include in ticket title

Gabriel Weinberg @gabew1984

### Start Date

21 February 2023

### Urgency

High (< 3 days)

### Special Requests

I am looking for the ability to create/edit issues on the Paragon project. I had this capability up until recently when my access level was changed by someone at tcril. Also I am asked to contribute UX input to tcril development projects, such as verifiable credentials, to be able to be tagged and able to comment on issues. Thanks!

**Comment by brian-smith-tcril** [comment]
I have:
- [x] Reinstated @gabew1984 as a member of the [Open edX GH org](https://github.com/openedx)
- [x] Added @gabew1984 as a member of the [push-pull-all team](https://github.com/orgs/openedx/teams/push-pull-all/)
- [x] Added Gabriel Weinberg to the CLA database on Salesforce
