### ISSUE TITLE
[GH Request] Onboard <Alexander Telischak, @aethant , Earnest Berry, @souvent22>

### ISSUE THREAD

**Issue by billyhho** [openedx/tcril-engineering#680]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

atelischak@2u.com Alexander Telischak, @aethant 
eberry@2u.com Earnest Berry, @souvent22

### Start Date

24 February 2023

### Urgency

Low (2 weeks)

**Comment by bmtcril** [comment]
Hi Billy, it looks like we don't have you in our database as a trusted approver for the 2U CLA. @georgebabey are you able to confirm that @billyhho is able to make this request and be added to the list of people who can make these CLA requests on behalf of 2U?

**Comment by georgebabey** [comment]
Approved

**Comment by bmtcril** [comment]
Thanks George, @billyhho can I get your email address so I can add you as an approver for future requests?

**Comment by billyhho** [comment]
@bmtcril it is bho@2u.com -- Thank you!

**Comment by bmtcril** [comment]
Thanks, this should be all set!

**Comment by bmtcril** [comment]
@Souvent22 as a heads up this invite will expire soon if you don't accept it.
