### ISSUE TITLE
[GH Request] Offboard javiboo

### ISSUE THREAD

**Issue by javiboo** [openedx/tcril-engineering#683]
### Firm Name

tCRIL

### User List  (case sensitive!) - Please also include in ticket title

* Javier Boó, @javiboo
* I want to leave from atlassian.net also (both JIRA and Confluence)

### End Date

24 February 2023

### Urgency

High (< 3 days)

**Comment by bmtcril** [comment]
Hi @javiboo, I can help you with that. We show you as being covered by the Game On Factory license agreement. If that's no longer the case I can remove you. I have removed your access from the Atlassian products. Do you have any other access that you're concerned about?

**Comment by bmtcril** [comment]
Hi @javiboo , should I be removing you from the Game On Factory agreement with tCRIL as part of this?

**Comment by bmtcril** [comment]
Yes there is another contact on the account, you should otherwise be offboarded from any github and atlassian permissions. Thanks!
