### ISSUE TITLE
[GH Request] Onboard <Syed-Ali-Abbas-Zaidi>

### ISSUE THREAD

**Issue by kmedina2u** [openedx/tcril-engineering#685]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

Syed Ali Abbas Zaidi, @Syed-Ali-Abbas-Zaidi

### Start Date

22 February 2023

### Urgency

High (< 3 days)

### Special Requests

Contractor's actual start date was 8 February 2023

Emails:
sabbas@2u.com
syed.ali.abbas@arbisoft.com

**Comment by bmtcril** [comment]
Hello, I've added them to our CLA database for tests (should propagate to test checks within 24 hrs), but they were already in the openedx GitHub organization. Let me know if you need anything else,

**Comment by bmtcril** [comment]
Actually @kmedina2u I do have a question. It looks like they were already added in our database under Arbisoft. Are they covered under the 2U CLA or the Arbisoft CLA?

**Comment by kmedina2u** [comment]
@bmtcril I am actually not sure, I can get in contact with them or their manager to confirm which CLA they are under

**Comment by bmtcril** [comment]
@kmedina2u If it helps, I believe the threshold is that if 2U is paying for their contributions they are under the 2U CLA

**Comment by kmedina2u** [comment]
@bmtcril The user's manager confirmed that they are covered under the Arbisoft CLA

**Comment by bmtcril** [comment]
Ok, should be all set then. Thanks!
