### ISSUE TITLE
[GH Request] Onboard <Zachary Blanchet (zblanchet@2u.com)>

### ISSUE THREAD

**Issue by billyhho** [openedx/tcril-engineering#686]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

Zachary Blanchet (zblanchet@2u.com)

### Start Date

27 February 2023

### Urgency

Low (2 weeks)

**Comment by bmtcril** [comment]
Hi @billyhho can you send over Zachary's GitHub username as well?

**Comment by billyhho** [comment]
@bmtcril it is zblanchet

**Comment by bmtcril** [comment]
This was actually previously handled in #621 , let me know if there's more that's needed here.
