### ISSUE TITLE
[GH Request] Onboard ahtesham-quraish

### ISSUE THREAD

**Issue by zainab-amir** [openedx/tcril-engineering#689]
### Firm Name

2U edX

### User List (case sensitive!) - Please also include in ticket title

* Ahtesham Quraish, @ahtesham-quraish

### Start Date

1 March, 2023

### Urgency

Medium (< 2 weeks)

### Special Requests

Please add Ahtesham to the vanguards team in openedX as well.

**Comment by zainab-amir** [comment]
@bmtcril I believe it went to their personal email address and they missed that. Ahtesham added the 2U email address to their github account today and they should now be able to receive the invite.
Email address: aquraish@2u.com

**Comment by bmtcril** [comment]
Thanks @zainab-amir , the invitation has been re-sent. Let me know if they run into any issues.
