### ISSUE TITLE
[GH Request] Onboard <MorneL>

### ISSUE THREAD

**Issue by kmedina2u** [openedx/tcril-engineering#693]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

Morne Lotze, @MorneL

### Start Date

6 March 2023

### Urgency

Medium (< 2 weeks)

### Special Requests

Email: mlotze@2u.com

**Comment by arbrandes** [comment]
ACKing the request: I'll get to it in the next 24 hours.
