### ISSUE TITLE
[GH Request] Merge Repo Health Workflow PR

### ISSUE THREAD

**Issue by UsamaSadiq** [openedx/tcril-engineering#694]
### Firm Name

2U

### Urgency

High (< 3 days)

### Problem/Request

Merge the PR https://github.com/openedx/.github/pull/52 to add reusable Repo Health Workflow which will migrate the `Repo Health Job` from Jenkins to GitHub Actions.

### Reasoning

`arbi-bom` has moved all of the jobs from Jenkins to GitHub Actions. The Repo Health job responsible for generating repo health dashboard is the last one in the process.
It was decided to host the reusable workflow in the `openedx/.github` repo to make it accessible for the organisations other than 2U as well. For further details, check the discussion on the issue  https://github.com/edx/edx-arch-experiments/issues/66.

**Comment by arbrandes** [comment]
Merged!
