### ISSUE TITLE
[GH Request] Add ecommerce maintainer

### ISSUE THREAD

**Issue by colinbrash** [openedx/tcril-engineering#695]
### Firm Name

2U

### Urgency

High (< 3 days)

### Requested Change

Please add
Jawad Khan - @jawad-khan
to the team
ecommerce-maintainers - https://github.com/orgs/openedx/teams/ecommerce-maintainers

### Reasoning

Jawad needs write permission to ecommerce in order to do his in-app purchase work.  He had such permission in the past but recently had issues with GitHub and he is no longer part of this team for some reason.

**Comment by arbrandes** [comment]
Acknowleged: I'll get to this today.

**Comment by arbrandes** [comment]
I invited @jawad-khan to the team!
