### ISSUE TITLE
[GH Request] Onboard JodyBaileyy, LuyandaMarvin, and danielleEriksen

### ISSUE THREAD

**Issue by hmccauley** [openedx/tcril-engineering#697]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

Jody Bailey, @jodybaileyy, jbailey@2u.com

Luyanda Marvin Dladla, @LuyandaMarvin, ldladla@2u.com

Danielle Eriksen, @danielleEriksen, deriksen@2u.com

### Start Date

9 March 2023

### Urgency

Low (2 weeks)

### Special Requests

user has requested push-pull-all permissions for all accounts 

this is via HUB ticket 01430423

**Comment by arbrandes** [comment]
@georgebabey, thanks!  I'd also like to add @hmccauley as a known requester: can I have their name and email as well?

**Comment by hmccauley** [comment]
my full name is Hunter McCauley and my email is hmccauley@2u.com! I am from the HD team 😁

**Comment by hmccauley** [comment]
thank you!
