### ISSUE TITLE
Rewrite Declaration of Commitment and get it signed

### ISSUE THREAD

**Issue by sarina** [openedx/tcril-engineering#7]
https://openedx.atlassian.net/wiki/spaces/COMM/pages/3216900524/Revised+Declaration+of+Commitment+to+the+Core+Contributor+Program

**Comment by sarina** [comment]
Update 12/1: The declaration is rewritten and awaiting signatures.

**Comment by sarina** [comment]
@antoviaque welcome to the tcril team's public issue tracker! I was going to co-assign this issue to you to give you credit for the immense amount of thought & help you've put into it. I'm new to using GH Issues but it seems for now you can only assign people who've commented on the issue. So if you want to be co-assigned let me know :)

BTW the board we're building up for public viewing is available at https://github.com/orgs/openedx/projects/8/views/1 - once repos are moved into the openedx org, we'll put repo-specific issues into the appropriate place, and let this project be geared to more "meta" issues (like, well, this one!)

**Comment by antoviaque** [comment]
@sarina Thank you for thinking of this! It would be an honor to share this ticket's assignation with you :)

And also thank you for being so open and collaborative on those topics - it's a pleasure to work on them with you.

**Comment by sarina** [comment]
2U has signed the declaration:

![image](https://user-images.githubusercontent.com/1985317/151867785-4f49a0b3-f927-4241-92c4-049c4c391ca6.png)

Final steps on this ticket are reaching out to new community members and letting them know about the document.

**Comment by sarina** [comment]
I'm going to mark this as Done. I reached out to the only two orgs with CCs who haven't signed - EDU Werkstatt and FCCN. I will continue emailing them as needed, but I think since the major signatories have now all signed, it is merely an ongoing task to make sure new members learn about this document.
