### ISSUE TITLE
[Forum Request] The forum needs a "Working Groups -> DevOps" subcategory

### ISSUE THREAD

**Issue by regisb** [openedx/tcril-engineering#702]
### Firm Name

Overhang.IO

### Urgency

Medium (< 2 weeks)

### Problem/Request

The devops working group needs a "DevOps" subcategory for the #working-groups category on the Open edX forum. I first asked about this here: https://discuss.openedx.org/t/proposal-devops-interest-group-structure/8881/17

Is this the right place to ask about forum administration stuff? If not, where should I be asking? 

Cc @feanil @sarina who are both forum administrators.

### Reasoning

I expect that the forum subcategory will be the primary place of discussion for the working group.

**Comment by arbrandes** [comment]
I don't have enough permissions to do it, so I'm gonna have to defer to somebody else.  I'll look into exactly who, today.
