### ISSUE TITLE
Move Open edX specific  ReadTheDocs projects to the Open edX specific RTD user

### ISSUE THREAD

**Issue by feanil** [openedx/tcril-engineering#71]
A ReadTheDocs project can have multiple maintainers, but the username of a maintainer can't be updated.  So the best option to keep things clear is to:
1. Make a new `openedx` ReadTheDocs user
2. Add them as a maintainer on all the openedx projects.
3. Remove the `edx` user as maintainer?  (@nedbat , are there may be reasons not to do this?)

AC:
- Figure out which read the docs projects need to move to the Open edX user.
  - Rational for decisions are clearly understoond and written down for future reference
- There is a clear separation of ownership of RTD projects.

**Comment by feanil** [comment]
The ` openedx-rtd-maintainer` user has been created, it's associated with the `readthedocs-maintainer@openedx.org` mailing list.

Next: We'll add this user as a maintainer to all the openedx RTD projects.

**Comment by nedbat** [comment]
I don't know of a reason to keep edx as a maintainer, though we haven't finished separating things out. I guess we can always add it back later if needed.

**Comment by feanil** [comment]
@nedbat good point, I removed `edx` as a maintainer for all projects that are not coming out of the `edx-documentation` repo since the ownership of those is already clear.  For the `edx-documentation` related projects I've left both users as owners for now.

**Comment by feanil** [comment]
This work is complete, the `openedx-rtd-maintainer` is now the only maintainer for projects that are not specific to edX Inc.  except for the ones that come from the `edx-documentation` repo.  The work to figure out what to do with projects in that repo is in progress and is being tracked in https://github.com/openedx/tcril-engineering/issues/49
