### ISSUE TITLE
Jira/Confluence Separation

### ISSUE THREAD

**Issue by sarina** [openedx/tcril-engineering#81]
Work with 2U IT to come up with a clean way of splitting the Jira/Confluence spaces such that tCRIL is left with an instance that meets their needs whilst respecting 2U's privacy requirements.

[Working spreadsheet](https://docs.google.com/spreadsheets/d/1zucEUhZBoAJUsA-f311O3QbNxcsszCoSSPzI9yD2ohw/edit#gid=0) (access restricted)

Working with @wesmason on the 2U side.

**Comment by sarina** [comment]
Sent the spreadsheet over to 2U, putting in blocked until that's addressed

**Comment by sarina** [comment]
@wesmason is there going to be more needed from the 2U side on this?

**Comment by wesmason** [comment]
@sarina -- We're primarily focused on our Google Workspace Migration right now. I'm hoping to turn my attention back to this in the next 2 weeks.

**Comment by sarina** [comment]
Sounds good @wesmason - please let me know if/when I can be of help 🙆🏻‍♀️

**Comment by sarina** [comment]
Closing out this ticket as it doesn't represent anything actionable. When 2U reaches out with steps for tCRIL to take, we will make new tickets.
