### ISSUE TITLE
[GH Request] Add instructional videos to docs.openedx.org

### ISSUE THREAD

**Issue by ehuthmacher** [openedx/tcril-engineering#815]
### Firm Name

Eden

### Urgency

Low (2 weeks)

### Problem/Request

Please link the instructional videos from the following YouTube playlist to the correlating documentation on docs.openedx.org: https://www.youtube.com/watch?v=IwuGccK49m8&list=PL87xhvJSz2W5AhGcra8ojmxqIGSUetiZY 

### Reasoning

Additional resources for Open edX end users/course authors.

**Comment by arbrandes** [comment]
I figure this would've been better created as an issue in the docs site as opposed to a GH request, but no matter: it was a nice tour of both the docs site and the excellent how-to videos we have, now!  The PR is up for review: https://github.com/openedx/docs.openedx.org/pull/355

**Comment by ehuthmacher** [comment]
Thank you @arbrandes !
