### ISSUE TITLE
Brainstorm and track ideas for tCRIL Open edX Conference talks

### ISSUE THREAD

**Issue by ormsbee** [openedx/tcril-engineering#90]
(Note: Call for proposals is open until Feb 20th -Kyle)

Proposal tickets:

- [x] #141 
- [x] #143
- [x] #142 
- [x] #144 
- [x] #145 
- [x] #154 
- [ ] #155  [3/11 - shifting to conference prep ticket #190)
- [x] #156 
- [x] #157

**Comment by sarina** [comment]
I'm considering giving a talk with Xavier about updates to the Core Contributor program, as well as its current state, and practical tips to becoming a CC and how to get your new contributors into the CC program. We'd first be generic to the whole program, then touch on dev-specific things as needed.

I would be happy to present something for "The State of Open edX" talk. I'm not sure what the topics there will be but am interested (maybe that's where a Core Contributor update should live, with the practical tips being a BOF or dev summit thing)

**Comment by feanil** [comment]
Couple of Ideas:

* Something around how tCRIL engineering is currenty operating and what we're working on.("tCRIL Origin Story")  People don't necessarily know the details of what we are and how things are going to work, it might be helpful to tell them about us and what we're working on(in particular to make it clear what we're not working on.)
* Not a talk but I'd love to do a working session around docs.  Focusing on doc layout/information architecture and talking through critical basic info we're missing.

**Comment by ehuthmacher** [comment]
Yes, those are great ideas! @sarina @feanil could you formalize your session proposals [here. ](https://sessionize.com/2022-open-edx-conference). @feanil Just indicate in the notes section that you are interested in conducting a working session rather than a talk.

**Comment by jmakowski1123** [comment]
@feanil Re: 1 - This might be a great space to introduce and talk about the evolving tCRIL Roadmap too

Per standup, finding the appropriate space to share findings from the survey and corresponding market research.

I'd also like to do a working session around the Community Roadmap. By April it might be in the context of a platform/product working group.

**Comment by sarina** [comment]
Hi @ehuthmacher - this right now is just a brainstorming doc - we are hoping to do a bunch of ideation before landing on talks. Once we have formal talk proposals, we will submit them don't worry!

**Comment by ehuthmacher** [comment]
@sarina Ok, sounds great. Thank you!

**Comment by kdmccormick** [comment]
With the native installation removed in Maple and Devstack on the chopping block, I think it'd be good to have something about Tutor on the agenda.

Ideas:
1. Tutor roadmap presentation - recent imcprovements, what's next, etc.
2. Tutor plugin API tutorial and/or plugin hacking session

For (1), I'd need Regis's help and also would want to be mindful of not being redundant with his recent end-of-year celebration presentation.

For (2) I could probably swing that whether or not I had help.

**Comment by e0d** [comment]
@kdmccormick Standup Tutor could be a great topic for Tuesday Tutorials.
@feanil I think origin story material should be part of the "State of Open edX" which I think will be on Day 1 after the keynote.
@arbrandes Where to start hacking could be a Tutorial as well.

**Comment by ormsbee** [comment]
Lightning talk suggestions (technical):

* Content Outlives Features
* Course Teams Make Mistakes: Handling Content Changes

**Comment by ormsbee** [comment]
I would love to give one on a new Learning Core Platform, if I could make it to the conference. 😞  Anyone else interested in trying it?

**Comment by jmakowski1123** [comment]
Closing this ticket in favor of individual tickets for presentation proposal tracking.

**Comment by kdmccormick** [comment]
@ormsbee I have interest, but I am not sure I could swing it alongside a Tutor workshop.
