### ISSUE TITLE
Create production instance for hosting courses

### ISSUE THREAD

**Issue by sarina** [openedx/tcril-engineering#93]
Create a production environment (likely via a community provider) where we can develop and host courses such as developer training and Open edX demonstration.

**Comment by sarina** [comment]
Emailed some questions out last Friday, awaiting response.

**Comment by sarina** [comment]
hey @e0d - want to chat about this per my recent email. I'm interested in a course site as distinct from a sandbox prod site. I know Kyle is keen on running that production site ourselves so we don't get too far away from understanding site operator pain. I don't care if my courses site is running on the last named release - that I'd like to be stable and have a far reach.

If a community member wants to help us run a sandbox site now, I don't think that's a problem - it also wouldn't be a problem for us to even have a parallel sandbox tracking master that's well suited for testing (like IMS conformance testing) and keeping us up to speed on the operator perspective.

However my current interest is in getting that courses site up. What are your thoughts there? Should we find a second provider for that?

**Comment by sarina** [comment]
@arbrandes I actually 100% agree with you, I just _also_ think that right now, our time is better spent on other projects, especially until things get a bit more stable with us, our roadmap, etc. However right now I want to start running community courses, so I think a provider may be the best option (also, it doesn't hurt us to learn what being a provider customer is like).

**Comment by arbrandes** [comment]
@sarina, sure, makes sense.

Maybe there's a middle ground, though.  What if we paid a provider to deploy and maintain an instance in a way that:

a) we could review and approve (no proprietary or unrepresentative deployment methods)
b) have direct access to ourselves (SSH, databases, the whole shebang)
c) eventually inherit for in-house maintenance

I realize this is still not quite turn-key, but may be a something to discuss up front with any provider: "you host our couses however you like now, but the plan is to move to this new way when possible". 

Idea: (co-?)finance the development of [Grove](https://discuss.openedx.org/t/tech-talk-demo-deploying-multiple-open-edx-instances-onto-a-kubernetes-cluster-with-tutor/4641), which seems like a nice way to scale Tutor.  (Yeah, I know, totally biased suggestion. :P)

**Comment by sarina** [comment]
Juan at eduNEXT has agreed to host an instance for courses for tCRIL. I have spoken with Nell and we'll wait till next week to begin hammering out most details such as privacy policy, site URL, etc. We would like to use the Open edX logo temporarily as tCRIL has no logo; [draft of request here](https://docs.google.com/document/d/1sEYYQyRPBYOEnoJP7AV26_CffrRHWXMWxEBb8gyt3so/edit#) -- 2U has to approve this ask.

**Comment by sarina** [comment]
We have the hosted environment set up; PM me for details, as it's not yet publicly available. Will make a follow-up ticket with the remaining tasks.
