### ISSUE TITLE
The DemoX course needs to have videos fixed

### ISSUE THREAD

**Issue by nedbat** [openedx/tcril-engineering#94]
The openedx/edx-demo-course repo needs a tiny bit of love: the YouTube links don’t work, because Google made them private back in July.  We haven’t found the YouTube account that hosts them, so we can’t fix them at YouTube.  A fix is to download three of them from AWS, upload them to the openedx YouTube account, update the course, and re-export the course.

This course is not used on edx.org, the demo course there diverged a while ago.

These are the four videos in the course.  Three of them are available at AWS:
1) Video: Welcome!
YouTube URL:  https://youtu.be/b7xgknqkQk8
Download URL:  https://s3.amazonaws.com/edx-course-videos/edx-edx101/EDXSPCPJSP13-H010000_100.mp4

2)  Science and Cooking Chef Profile: JOSÉ ANDRÉS
YouTube URL: https://youtu.be/CCxmtcICYNc
Download URL: not available 

3) Video
YouTube URL: https://youtu.be/qWxm7CA2v2
Download link: https://s3.amazonaws.com/edx-course-videos/harvard-heroes/HARHEROESP13-H00700_100.mp4

4) Connecting a Circuit and a Circuit Diagram
YouTube URL: https://youtu.be/o2pLltkrhGM
Download link: https://s3.amazonaws.com/edx-course-videos/mit-6002x/6002-Tutorial-00010_100.mov

**Comment by Carlos-Muniz** [comment]
I think the missing video may be from [The Science of Cooking Professional Certificate Program](https://www.edx.org/professional-certificate/harvardx-the-science-of-cooking).

**Comment by ehuthmacher** [comment]
I have re-uploaded the three videos to the Open edX YouTube account.

**Comment by Carlos-Muniz** [comment]
### New Open edX Youtube URLs

Video: Welcome!
URL: https://youtu.be/c6YBGhZBB80

Video: Poetry Discussion
URL: https://youtu.be/rKbzh2DWBX4

Video: Connecting a Circuit and a Circuit Diagram
URL: https://youtu.be/xUIM7LWLsEY
