### ISSUE TITLE
setup scheduled reminders for Openedx repos

### ISSUE THREAD

**Issue by muneebGH** [openedx/tcril-engineering#97]
Hi, i want to setup Scheduled reminders for some events on openedx repositories like PR reviews etc as i have setup on edx
![Screenshot 2022-01-31 at 6 58 35 PM](https://user-images.githubusercontent.com/49611774/151825583-60ee0d97-ccfd-422a-935a-3fa70984bb3f.png)

--------------------------------------------------------------
**But facing this**
![Screenshot 2022-01-31 at 6 56 29 PM](https://user-images.githubusercontent.com/49611774/151825649-d55d5497-7be9-4fe3-862c-3b9b2acdb7f8.png)

**Comment by kdmccormick** [comment]
Hi @muneebGH , if you open a new issue using one of our request templates then our on-call engineer will take a look: https://github.com/openedx/tcril-engineering/issues/new/choose
