### ISSUE TITLE
Interview Structure & Questions for FE Engineer

### ISSUE THREAD

**Issue by sarina** [openedx/tcril-engineering#99]
### job posting

TBD, current postings aren't right

### following links available to tCRIL-only folx

[30-60-90](https://docs.google.com/document/d/19mDxfc9y0_rf2g5S4_EvUDL-0uaC7yEQbNKLz7_WbKY/edit?usp=sharing)

[original jd](https://docs.google.com/document/d/1EncssAHMxo-yn4LTbXjtXwmbJV2HxepGE8Ngymi-KXE/edit)

### to be created in private docs

- [x] Phone screen questions (light technical, weed-out)
- [x] Technical interview 1 question(s)
- [ ] Technical interview 2 question(s)
- [x] Identify who will lead and, if desired, shadow question 1
- [x] Identify who will lead and, if desired, shadow question 2
- [x] Behavioral questions

**Comment by arbrandes** [comment]
Status update: intend to have this up for review today (over the weekend, if necessary).
